### ISSUE TITLE
Copyright comments removed with alwaysStrict

### ISSUE THREAD

**Issue by jbrimeyer** [Microsoft/TypeScript#12307]
Copyright comments are stripped from the generated output when using both alwaysStrict and removeComments.

For example, invoking the compiler as:

`tsc --removeComments --alwaysStrict test.ts`

**TypeScript Version:**  2.1.1

**Code**

```ts
/*!
This is a copyright comment
*/

/*
This is a regular comment
*/

function tester() {
	// This is a test comment
}
```

**Expected behavior:**

```ts
/*!
This is a copyright comment
*/
"use strict";
function tester() {
}

```

**Actual behavior:** 

```ts
"use strict";
function tester() {
}
```

**Comment by electricessence** [comment]
Doesn't have to be ```alwaysStrict```.  All comments are removed now with ```'removeComments:true```.
Changed some time between 2.0.6 and 2.1.1
[Bug]

**Comment by rbuckton** [comment]
@jbrimeyer, @electricessence in which version of the compiler are you seeing this issue?

**Comment by jbrimeyer** [comment]
@rbuckton 2.1.1 for me

**Comment by electricessence** [comment]
Yes. 2.1.1

**Comment by rbuckton** [comment]
Would either of you be willing to try using typescript@next to see whether this issue is persisting for you? It seems like a recent change may have already addressed this issue.

**Comment by jbrimeyer** [comment]
It does appear to be fixed in 2.2.0-dev.20161117

**Comment by electricessence** [comment]
Will check it out...
Just some context I noticed.  It was only when imports were being used.

**Comment by electricessence** [comment]
I take back what I said.  This is not fixed.
I'm using the latest build for today 1121.
And it is stripping out the ```/*!``` comments.

**Comment by electricessence** [comment]
I've verified that stripping out the ```/*!``` comment occurs when there are imports and remains when there is not.

**Comment by electricessence** [comment]
Another point of interest: Shouldn't the copyright comment be retained in the companion declaration files?

**Comment by electricessence** [comment]
@mhegazy you marked this as fixed.  But I'm not seeing this working properly in the latest dev build.
I'm also seeing even with ```removeComments:false``` the ```/*!``` comment is removed. :(

**Comment by yuit** [comment]
The original issue is fixed in the latests build but as @electricessence  mentions copyright comment is removed when using import both in .js and .d.ts files.... with out import copy right comment is retained in both .js and .d.ts

**Comment by electricessence** [comment]
@yuit right, I think at one point I was able to get this issue to go away but it was a very 'touchy' thing that if lines were inserted in the wrong spot or if there was an extra CR or something it would break. :(

I've been able to get my code to render correctly now, but I'm guessing the 'touchiness' still exists?

**Comment by electricessence** [comment]
https://github.com/electricessence/TypeScript.NET/commit/06f04a6c4f8ae37c7a3fb1d88380dde2f4de0556
This is the checkin I made that got the code to render correctly.
Apparently padding the copyright comment with 1 CR between it and the imports are what made it work.

**Comment by yuit** [comment]
After looking closely about this, it is not a bug that we remove copy-right comment when `--removeComments true`without empty line between copyright comment and first statement. Without the empty line, copyright comment will be considered as leading comment of the first statement. Thus it get removed because we will have no way to differentiate between leading comment and detached comment without using empty line
