### ISSUE TITLE
Visual Studio 2017 is compiling JS file without associated TS file

### ISSUE THREAD

**Issue by styfle** [Microsoft/TypeScript#14827]
**TypeScript Version:**  2.1.5

**Code**
Get master branch from here:
https://github.com/styfle/TypeScriptReproBug

**Expected behavior:**
Do not compile `.js` files if there is no matching `.ts` file.

**Actual behavior:**
The `.js` files are modified and a `.js.map` file is generated.

## More Info

I opened an existing 2015 project in VS 2017, edited a `.d.ts` file, saved, and VS started compiling a lot of files....files that do not have a `.ts` associated with them 😨 

![image](https://cloud.githubusercontent.com/assets/229881/24255569/450d89d8-0fbc-11e7-8f31-1c75d188d96e.png)

Then I looked at git changes in Team Explorer tab and I can see that a bunch of `.js` files were modified and a bunch of `.js.map` files were added.

![image](https://cloud.githubusercontent.com/assets/229881/24255545/32badf2e-0fbc-11e7-8d72-bde7be819705.png)

@billti Please review the code. Thanks!

**Comment by billti** [comment]
Thanks. I just tried this and couldn't repro, then realized I was running TypeScript 2.2. Switching to 2.1 (that comes with VS 2017) I could repro.

If you could try using TypeScript 2.2 (as outlined in https://github.com/Microsoft/TypeScript/issues/14529#issuecomment-287517438 ) and confirm this fixes the issue, at least we'll know this is already addressed somehow (I couldn't spot the exact commit which would have fixed it).

**Comment by styfle** [comment]
I haven't got around to testing this but is there a new version of TypeScript going to be released with a 2017 update?

**Comment by styfle** [comment]
I just realized `<TypeScriptToolsVersion/>` is set to `1.8`.

I went ahead and tried to reproduce with the latest Visual Studio released May 10, 2017 - version 15.2 (26430.04).

Without any changes to `<TypeScriptToolsVersion/>` the bug is still present, however changing `<TypeScriptToolsVersion/>` to `2.2` fixes the bug.

**Comment by billti** [comment]
Thanks for confirming it's fixed in the latest release.

**Comment by styfle** [comment]
@billti I just had this happen to me again today. I am using Version 15.2 (26430.6) now.

**Comment by styfle** [comment]
Is this supposed to be fixed with selecting TypeScript 2.1 or only in 2.2?

**Comment by crh225** [comment]
Im on 2.3.3 and it is happening to me also
