### ISSUE TITLE
.csproj settings don't work during Visual Studio Rebuild or Clean

### ISSUE THREAD

**Issue by Kaelum** [Microsoft/TypeScript#16532]
**TypeScript for Visual Studio 2015:**  2.3.3

Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3

During a Rebuild, the following .csproj settings do not work; however, they do appear to work during a **Build**:

```
<TypeScriptEnabled>false</TypeScriptEnabled>
<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
```

Since we are required to have the output .js files in source control, we see the following error for every file that is not checked out, due to the TypeScript being built during a **Rebuild**:

```
12>C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.3\build\Microsoft.TypeScript.targets(326,5): error MSB3061: Unable to delete file "<filepath removed>.js". Access to the path '<filepath removed>.js' is denied.
```

For now we have to perform a **Build** after every **Rebuild**, but it would be nice if these options worked during **Rebuild**s.

P.S.  I just learned that the same errors also occur during a **Clean**.

**Comment by mhegazy** [comment]
rebuild just calls clean then rebuild. looks like we are not checking the flags on clean.

**Comment by Kaelum** [comment]
UPDATE: 06/19/2017

Today, I ran into another problem and opened #16630.  Fortunately, @yuit was able to help me fix the issue, which appears to be just one more issue with the **ComponentModelCache** folder and corrupted contents.  After deleting that folder and allowing VS 2015 to rebuild the contents, that issue was fixed.

Then I tried a rebuild, and guess what?  This issue no longer appears to be an issue.  I'll continue to watch for the issue, but this issue may also be related to **ComponentModelCache** folder corruption issues.

**Comment by minestarks** [comment]
@Kaelum I don't think clearing the mef cache is what did it. I verified that this issue still exists under certain conditions.

At the moment, the trick to getting Clean/Rebuild to ignore your .js files is to delete the ```tsc.out``` file in the output directory (e.g. ```obj/Debug```). This file gets generated when the project is built.

Can you tell me a bit more about your build process? When _do_ you actually build your TypeScript files?

Note: Any reason you have  ```<TypeScriptEnabled>``` set to false? That's an internal flag only used by the language service, not the build.

**Comment by Kaelum** [comment]
@minestarks, I did delete the entire solution folder and reload from TFS, so that would have deleted the file.  If it pops up again, I'll try what you've described.

Our build process is fairly simple.  Since the output is transpiled code, we don't allow our build servers to build it, and it is only done within VS upon file save.  We have siloes for each application, and a dedicated tsconfig.json for each application in a folder under **~/Scripts/apps**, and support code in folders under **~/Scripts/modules**.  We use **outFile** to place the transpiled output, and declaration, into the **~/Scripts** folder.

We used the following .csproj settings based on statements made in other threads, as we never want any TypeScript to be transpiled when we do a build.  Only file saves should transpile the TypeScript:

```
<TypeScriptEnabled>false</TypeScriptEnabled>
<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
```

If the first setting doesn't need to be used, or shouldn't be, let me know.  The overall application is an enterprise application built on ASP.NET MVC,  Before we started using TypeScript, we had a mess left by a contractor, which required us to use Babel and many other tools that we don't want to be tied to.  The code that I wrote was extremely easy to convert over, but we're still trying to just get the basics working in this other code.

**Comment by minestarks** [comment]
Thanks @Kaelum. I would go ahead and remove ```TypeScriptEnabled``` for A) it's not used by the build, just the VS language service and B) the Microsoft.TypeScript.targets import sets that right back to true anyway so it probably has no effect.

The bug with ```TypeScriptCompileBlocked``` and Clean will be fixed in the next release.

**Comment by Kaelum** [comment]
@minestarks I removed the line from the project today.  Thank you for fixing this so quickly.

Have a great week!
