### ISSUE TITLE
No compiler was found at C:\Program Files (x86)\Microsoft SDKs\TypeScript\tsc.exe

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#2039]
Hi,

I installed Visual Studio 2015 CTP 5, added a brand new TypeScript project and I get this error.

```
1>------ Rebuild All started: Project: TypeScriptHTMLApp1, Configuration: Debug Any CPU ------

1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(102,5): 
       error : Your project file uses a different version of the TypeScript compiler and tools 
       than is currently installed on this machine.  
       No compiler was found at C:\Program Files (x86)\Microsoft SDKs\TypeScript\tsc.exe.  
       You may be able to fix this problem by changing the <TypeScriptToolsVersion> 
        element in your project file.

1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(102,5): 
      error MSB6004: The specified task executable location 
       "C:\Program Files (x86)\Microsoft SDKs\TypeScript\tsc.exe" is invalid.

========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

The folder `C:\Program Files (x86)\Microsoft SDKs\TypeScript` looks like this:

![image](https://cloud.githubusercontent.com/assets/1106823/6204718/ecac1164-b54b-11e4-992f-d92c9426d960.png)

I've tried a "Repair" on the VS 2015 install, but that didn't fix anything. (On an aside, before repair the file `C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.4\tsc.exe` was missing; the repair installed that file.)

The relevant sections of the projects configuration for the (brand new) TypeScript project look like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <ProjectGuid>{62C15C1C-014D-4D4D-854C-E61A8067406B}</ProjectGuid>
    <ProjectTypeGuids>{349c5851-65df-11da-9384-00065b846f21};{fae04ec0-301f-11d3-bf4b-00c04f79efbc}</ProjectTypeGuids>
    <OutputType>Library</OutputType>
    <OutputPath>bin</OutputPath>
    <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <TypeScriptToolsVersion>1.4</TypeScriptToolsVersion>
    <UseIISExpress>true</UseIISExpress>
    <IISExpressSSLPort />
    <IISExpressAnonymousAuthentication />
    <IISExpressWindowsAuthentication />
    <IISExpressUseClassicPipelineMode />
  </PropertyGroup>

  <PropertyGroup>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">12.0</VisualStudioVersion>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace>TypeScriptHTMLApp1</RootNamespace>
  </PropertyGroup>
  <Import Project="$(MSBuildBinPath)\Microsoft.CSharp.targets" />
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\WebApplications\Microsoft.WebApplication.targets" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\WebApplications\Microsoft.WebApplication.targets')" />
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <TypeScriptRemoveComments>false</TypeScriptRemoveComments>
    <TypeScriptSourceMap>true</TypeScriptSourceMap>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <TypeScriptRemoveComments>true</TypeScriptRemoveComments>
    <TypeScriptSourceMap>false</TypeScriptSourceMap>
  </PropertyGroup>
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets')" />
</Project>
```

Points to note: MSBuild is not looking for the version folder in `C:\Program Files (x86)\Microsoft SDKs\TypeScript` spite of `TypeScriptToolsVersion` being set to `1.4`.

How do I fix this?

**Comment by danquirk** [comment]
Very strange, good info though, definitely some suspicious behavior in a couple spots there.

**Comment by paulvanbrenk** [comment]
What does the targets file look like?

"C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\TypeScript\Microsoft.TypeScript.targets"

**Comment by NoelAbrahams** [comment]
@paulvanbrenk, the `Microsoft.TypeScript.targets` file from the `v12` folder is below.

In the meantime I have got this working - not exactly sure how. I think the fix is to uninstall the VS 2013 powertool and re-install it *after* VS 2015 is installed. Seems to be related to #1177 

I guess to find the root cause of this problem, one must get hold of the `v12` `.targets` file on a machine that does not have VS 2015 installed.

```XML
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>
    <VsToolsPath Condition="'$(VsToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VsToolsPath>
  </PropertyGroup>

  <UsingTask TaskName="TypeScript.Tasks.VsTsc" AssemblyFile="$(VSToolsPath)\TypeScript\TypeScript.tasks.dll" />

  <PropertyGroup>
    <CompileDependsOn>
      CompileTypeScript;
      $(CompileDependsOn);
    </CompileDependsOn>
    <PublishPipelineCollectFilesCore>
      $(PublishPipelineCollectFilesCore);
      CompileTypeScript;
    </PublishPipelineCollectFilesCore>
    <CleanDependsOn>
      $(CleanDependsOn);
      TypeScriptClean
    </CleanDependsOn>
    <BuiltProjectOutputGroupDependsOn>
      CompileTypeScript;
      $(BuiltProjectOutputGroupDependsOn);
    </BuiltProjectOutputGroupDependsOn>
  </PropertyGroup>

  <PropertyGroup>
    <GetCopyToOutputDirectoryItemsDependsOn>
      $(GetCopyToOutputDirectoryItemsDependsOn);
      GetTypeScriptCopyToOutputDirectoryItems;
    </GetCopyToOutputDirectoryItemsDependsOn>
  </PropertyGroup>

  <PropertyGroup>
    <CfgPropertyPagesGuidsAddCSharp>{d4683cae-88c4-4b85-863d-ac8014f3ba36}</CfgPropertyPagesGuidsAddCSharp>
    <CfgPropertyPagesGuidsAddVB>{d4683cae-88c4-4b85-863d-ac8014f3ba36}</CfgPropertyPagesGuidsAddVB>
    <CfgPropertyPagesGuidsAddTypeScript>{d4683cae-88c4-4b85-863d-ac8014f3ba36}</CfgPropertyPagesGuidsAddTypeScript>
  </PropertyGroup>

  <PropertyGroup>
    <!-- Indicates to the language service that this project supports TypeScript -->
    <TypeScriptEnabled>true</TypeScriptEnabled>

    <!-- Controls Compile-on-Save in the IDE -->
    <TypeScriptCompileOnSaveEnabled Condition="'$(TypeScriptCompileOnSaveEnabled)' == ''">true</TypeScriptCompileOnSaveEnabled>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TypeScriptBuildConfigurations)' == ''">
    <PreferredUILang Condition="'$(BuildingInsideVisualStudio)' == 'true' and '$(PreferredUILang)' == ''">$([System.Globalization.CultureInfo]::CurrentUICulture.Name)</PreferredUILang>

    <TypeScriptBuildConfigurations Condition="'$(TypeScriptRemoveComments)' == 'true'">$(TypeScriptBuildConfigurations) --removeComments</TypeScriptBuildConfigurations>
    <TypeScriptBuildConfigurations Condition="'$(TypeScriptNoImplicitAny)' == 'true'">$(TypeScriptBuildConfigurations) --noImplicitAny</TypeScriptBuildConfigurations>
    <TypeScriptBuildConfigurations Condition="'$(TypeScriptGeneratesDeclarations)' == 'true'">$(TypeScriptBuildConfigurations) --declaration</TypeScriptBuildConfigurations>
    <TypeScriptBuildConfigurations Condition="'$(TypeScriptModuleKind)' != '' and '$(TypeScriptModuleKind)' != 'none'">$(TypeScriptBuildConfigurations) --module $(TypeScriptModuleKind)</TypeScriptBuildConfigurations>
    <TypeScriptBuildConfigurations Condition="'$(TypeScriptOutFile)' != ''">$(TypeScriptBuildConfigurations) --out &quot;$(TypeScriptOutFile)&quot;</TypeScriptBuildConfigurations>
    <TypeScriptBuildConfigurations Condition="'$(TypeScriptOutDir)' != ''">$(TypeScriptBuildConfigurations) --outDir &quot;$(TypeScriptOutDir)&quot;</TypeScriptBuildConfigurations>
    <TypeScriptBuildConfigurations Condition="'$(TypeScriptSourceMap)' == 'true'">$(TypeScriptBuildConfigurations) --sourcemap</TypeScriptBuildConfigurations>
    <TypeScriptBuildConfigurations Condition="'$(TypeScriptTarget)' != ''">$(TypeScriptBuildConfigurations) --target $(TypeScriptTarget)</TypeScriptBuildConfigurations>
    <TypeScriptBuildConfigurations Condition="'$(TypeScriptNoResolve)' == 'true'">$(TypeScriptBuildConfigurations) --noResolve</TypeScriptBuildConfigurations>
    <TypeScriptBuildConfigurations Condition="'$(TypeScriptAdditionalFlags)' != ''">$(TypeScriptBuildConfigurations) $(TypeScriptAdditionalFlags)</TypeScriptBuildConfigurations>
    <TypeScriptBuildConfigurations Condition="'$(TypeScriptMapRoot)' != ''">$(TypeScriptBuildConfigurations) --mapRoot &quot;$(TypeScriptMapRoot)&quot;</TypeScriptBuildConfigurations>
    <TypeScriptBuildConfigurations Condition="'$(TypeScriptSourceRoot)' != ''">$(TypeScriptBuildConfigurations) --sourceRoot &quot;$(TypeScriptSourceRoot)&quot;</TypeScriptBuildConfigurations>
    <TypeScriptBuildConfigurations Condition="'$(TypeScriptCodePage)' != ''">$(TypeScriptBuildConfigurations) --codepage $(TypeScriptCodePage)</TypeScriptBuildConfigurations>
    <TypeScriptBuildConfigurations Condition="'$(TypeScriptCharset)' != ''">$(TypeScriptBuildConfigurations) --charset $(TypeScriptCharset)</TypeScriptBuildConfigurations>
    <TypeScriptBuildConfigurations Condition="'$(TypeScriptEmitBOM)' == 'true'">$(TypeScriptBuildConfigurations) --emitBOM</TypeScriptBuildConfigurations>
    <TypeScriptBuildConfigurations Condition="'$(TypeScriptNoLib)' == 'true'">$(TypeScriptBuildConfigurations) --noLib</TypeScriptBuildConfigurations>
    <TypeScriptBuildConfigurations Condition="'$(TypeScriptPreserveConstEnums)' == 'true'">$(TypeScriptBuildConfigurations) --preserveConstEnums</TypeScriptBuildConfigurations>
    <TypeScriptBuildConfigurations Condition="'$(TypeScriptSuppressImplicitAnyIndexErrors)' == 'true'">$(TypeScriptBuildConfigurations) --suppressImplicitAnyIndexErrors</TypeScriptBuildConfigurations>

    <!-- noEmitOnError default is 'true', this ensures a proper incremental build behavior, where outputs are not generated in the presence of an error. -->
    <TypeScriptBuildConfigurations Condition="'$(TypeScriptNoEmitOnError)' != 'false'">$(TypeScriptBuildConfigurations) --noEmitOnError</TypeScriptBuildConfigurations>

    <TypeScriptBuildConfigurations Condition="'$(PreferredUILang)' != ''">$(TypeScriptBuildConfigurations) --locale $(PreferredUILang)</TypeScriptBuildConfigurations>
  </PropertyGroup>

  <PropertyGroup>
    <TypeScriptToolsVersion Condition="'$(TypeScriptToolsVersion)'==''">1.4</TypeScriptToolsVersion>
    <TscToolPath Condition="'$(TscToolPath)' == ''">$(MSBuildProgramFiles32)\Microsoft SDKs\TypeScript</TscToolPath>
    <TscToolPath Condition="'$(TypeScriptToolsVersion)' != ''">$(TscToolPath)\$(TypeScriptToolsVersion)</TscToolPath>
    <TscToolExe Condition="'$(TscToolExe)' == ''">tsc.exe</TscToolExe>
    <TscYieldDuringToolExecution Condition="'$(TscYieldDuringToolExecution)' == ''">true</TscYieldDuringToolExecution>
  </PropertyGroup>

  <ItemGroup>
    <ProjectCapability Include="TypeScript" />
  </ItemGroup>

  <Target Name="PreComputeCompileTypeScript">
    <VsTsc
      ToolPath="$(TscToolPath)"
      ToolExe="$(TscToolExe)"
      Configurations="$(TypeScriptBuildConfigurations) COMPUTE_PATHS_ONLY"
      FullPathsToFiles="@(TypeScriptCompile)"
      YieldDuringToolExecution="$(TscYieldDuringToolExecution)"
      OutFile="$(TypeScriptOutFile)"
      OutDir="$(TypeScriptOutDir)"
      ProjectDir="$(ProjectDir)"
      ToolsVersion ="$(TypeScriptToolsVersion)"
      >
      <Output TaskParameter="GeneratedJavascript" ItemName="GeneratedJavascript" />
    </VsTsc>
    <AssignTargetPath Files="@(GeneratedJavascript)" RootFolder="$(MSBuildProjectDirectory)">
      <Output TaskParameter="AssignedFiles" ItemName="GeneratedJavascriptWithTargetPath" />
    </AssignTargetPath>
    <ItemGroup>
      <FilesForPackagingFromProject Include="@(GeneratedJavascriptWithTargetPath->'%(Identity)')"/>
      <ContentWithTargetPath Include="@(GeneratedJavascriptWithTargetPath->'%(Identity)')"/>
      <Content Include="@(GeneratedJavascript->'%(Identity)')"/>
    </ItemGroup>
  </Target>

  <Target Name="CompileTypeScript" Condition="'$(BuildingProject)' != 'false'" DependsOnTargets="PreComputeCompileTypeScript" Inputs="@(TypeScriptCompile)" Outputs="@(GeneratedJavascript)">
    <VsTsc
      ToolPath="$(TscToolPath)"
      ToolExe="$(TscToolExe)"
      Configurations="$(TypeScriptBuildConfigurations)"
      FullPathsToFiles="@(TypeScriptCompile)"
      YieldDuringToolExecution="$(TscYieldDuringToolExecution)"
      OutFile="$(TypeScriptOutFile)"
      OutDir="$(TypeScriptOutDir)"
      ProjectDir="$(ProjectDir)"
      ToolsVersion ="$(TypeScriptToolsVersion)"
      >
      <Output TaskParameter="GeneratedJavascript" ItemName="GeneratedJavascript" />
    </VsTsc>
  </Target>

  <Target Name="GetTypeScriptCopyToOutputDirectoryItems">
    <AssignTargetPath Files="@(TypeScriptCompile)" RootFolder="$(MSBuildProjectDirectory)">
      <Output TaskParameter="AssignedFiles" ItemName="TypeScriptCompileWithTargetPath" />
    </AssignTargetPath>
    <Message Text="Adding items with BuildAction=TypeScriptCompile to the same collections that will be populated (with items of other BuildActions) by the GetCopyToOutputDirectoryItems target"/>
    <ItemGroup>
      <AllItemsFullPathWithTargetPath            Include="@(TypeScriptCompileWithTargetPath->'%(FullPath)')" Condition="'%(TypeScriptCompileWithTargetPath.CopyToOutputDirectory)'=='Always' or '%(TypeScriptCompileWithTargetPath.CopyToOutputDirectory)'=='PreserveNewest'"/>
      <_SourceItemsToCopyToOutputDirectoryAlways Include="@(TypeScriptCompileWithTargetPath->'%(FullPath)')" Condition="'%(TypeScriptCompileWithTargetPath.CopyToOutputDirectory)'=='Always'"/>
      <_SourceItemsToCopyToOutputDirectory       Include="@(TypeScriptCompileWithTargetPath->'%(FullPath)')" Condition="'%(TypeScriptCompileWithTargetPath.CopyToOutputDirectory)'=='PreserveNewest'"/>
    </ItemGroup>
  </Target>

  <Target Name="TypeScriptClean" DependsOnTargets="PreComputeCompileTypeScript">
    <Delete Files="@(GeneratedJavascript)" />
  </Target>
</Project>

```

**Comment by jakobehn** [comment]
Had the same issue, both with VS 2015 Preview and CTP5. After installing VS2015, I get this error both in VS2013 and VS2015.

It is resolved by running repair on TypeScript 1.4

**Comment by ahmedalejo** [comment]
Having the same issue after installing VS 2015 Preview and CTP5.
Typescript compilation in VS2013 stopped working

**Comment by ahmedalejo** [comment]
Found out why the error occurs but not what provoked it upon installing VS 2015 Preview and CTP5 

in the file
```
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\TypeScript\Microsoft.TypeScript.targets
```
```
<PropertyGroup>
    <TypeScriptToolsVersion Condition="'$(TypeScriptToolsVersion)'==''">1.1</TypeScriptToolsVersion>
    <TscToolPath Condition="'$(TscToolPath)' == ''">$(MSBuildProgramFiles32)\Microsoft SDKs\TypeScript\</TscToolPath>
    <TscToolExe Condition="'$(TscToolExe)' == ''">tsc.exe</TscToolExe>
    <TscYieldDuringToolExecution Condition="'$(TscYieldDuringToolExecution)' == ''">true</TscYieldDuringToolExecution>
  </PropertyGroup>
```
which builds a ```TscToolPath``` as ```C:\Program Files (x86)\Microsoft SDKs\TypeScript\tsc.exe```
that doesn´t exist.

while in the file
```
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets
```
```
  <PropertyGroup>
    <TypeScriptToolsVersion Condition="'$(TypeScriptToolsVersion)'==''">1.4</TypeScriptToolsVersion>
    <TscToolPath Condition="'$(TscToolPath)' == ''">$(MSBuildProgramFiles32)\Microsoft SDKs\TypeScript</TscToolPath>
    <TscToolPath Condition="'$(TypeScriptToolsVersion)' != ''">$(TscToolPath)\$(TypeScriptToolsVersion)</TscToolPath>
    <TscToolExe Condition="'$(TscToolExe)' == ''">tsc.exe</TscToolExe>
    <TscYieldDuringToolExecution Condition="'$(TscYieldDuringToolExecution)' == ''">true</TscYieldDuringToolExecution>
  </PropertyGroup>
```

which builds a correct ```TscToolPath``` as ```C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.4\tsc.exe```

**Comment by jakobehn** [comment]
I just installed CTP6 that was release yesterday and I didn't experience the same problem. After upgrade, TypeScript still works

**Comment by kip9000** [comment]
Repairing TypeScript 1.4 from Control Pane/Uninstall Programs solves this problem. But having to restart the machine is just ridiculous.

**Comment by paulvanbrenk** [comment]
Thanks for the update.

I'll see what I can do about the restarts, but that may be a limitation of the setup components we're using...

**Comment by paulvanbrenk** [comment]
This should be fixed in the next version we release.

**Comment by bhallaheemanshu** [comment]
Hi, Is this problem fixed i am again getting this error in VS 2015 ( Asp.net Core ) I am using Typescript 1.8

**Comment by bhallaheemanshu** [comment]
@jakobehn It didn't resolved by repairing Typescript 1.8 . I even Reinstalled it Then Again Repaired it But error is still there

**Comment by bhallaheemanshu** [comment]
@kip9000 and @paulvanbrenk 

I have reinstalled it from control panel and Error is still there . I am using Typescript 1.8 . I am thinking It should have been fixed . Not sure if I am making any mistake

**Comment by bhallaheemanshu** [comment]
@paulvanbrenk This Error Only Came When I Use Asp.net Core

**Comment by paulvanbrenk** [comment]
@bhallaheemanshu is there a TypeScriptToolsVersion in the project file, if not can add it and set it to 1.8 (See the TypeScript HTML Application if you're unsure).

**Comment by bhallaheemanshu** [comment]
@paulvanbrenk I tried adding 1.8 in <TypescriptToolsVersion>1.8 But that didn't worked . Actually tsc.exe was missing on my side . But weird thing is i tried installing Typescript again with One Restart of my Box and unistall But it was not generating again tsc.exe 

Then I got that From Other Box and it fluently fixed it .

**Comment by fabsenet** [comment]
I experienced the same here. After installing typescript 1.8 the folder C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8 contains 38 files with tsc.exe missing. Copying the tsc.exe from a different machine fixes the issue.

Maybe a hint: I have a user with limited rights and to install typescript i was using a different account with admin rights. Windows 7, domain joined

**Comment by mhegazy** [comment]
> Maybe a hint: I have a user with limited rights and to install typescript i was using a different account with admin rights. Windows 7, domain joined

consider using the [nuget package](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Integrating%20with%20Build%20Tools.md#nuget) instead.

**Comment by selganor74** [comment]
I have solve the 1.8 issue having node installed globally on my machine and creating the file tsc.cmd in the path "C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8" with this content

```
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0tsc" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\tsc" %*
)
```

then I have changed "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets"

and 

C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\TypeScript\Microsoft.TypeScript.targets

replacing

`    <TscToolExe Condition="'$(TscToolExe)' == ''">tsc.exe</TscToolExe> `

with

`    <TscToolExe Condition="'$(TscToolExe)' == ''">tsc.cmd</TscToolExe> `
