### ISSUE TITLE
Compiler OOM in watch mode and with --d

### ISSUE THREAD

**Issue by aldendaniels** [microsoft/TypeScript#21140]
Process is running out out of memory on TS `2.6.2` in watch mode.

To reproduce:
 1. Run `tsc --noemit --watch --project .`
 2. Edit a file

The process hangs for a minute or so, then crashes with a node out-of-memory exception. 

This does not appear to be related to strict generic checks (see  #19662), as the exception still occurs when running `tsc --noemit --watch --noStrictGenerics --project .` (presuming that the `--noStrictGenerics` flag overrides the `.tsconfig`).

This is possibly a dup of #19253. It's a large project (2700+ files) and we're hitting performances challenges generally so project size is likely a factor. I can't share the project as the code is proprietary, but would be happy to jump on a screen share to further diagnose if that would be helpful.

cc: @mhegazy

**Comment by mhegazy** [comment]
Can you try `typescript@next`?
Can you share the project otuside of github? we wold be happy to sign any required NDA's to get access to the code base.

**Comment by aldendaniels** [comment]
@mhegazy thanks for the awesome support. In `typescript@next` the initial watch run never completes (a different problem).

In TS 2.6 it seems that the OOM exception only occurs on certain files (but there it does occur reliably). On other files the incremental watch works, but is slow (10+ seconds for a change that affects the local scope of a single function).

Running MacOS. Trace (although don't expect it to be useful) is:
```

<--- Last few GCs --->

[8826:0x103000000]   426050 ms: Mark-sweep 1402.7 (1458.8) -> 1402.7 (1455.8) MB, 1498.3 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1498 ms) last resort GC in old space requested
[8826:0x103000000]   427533 ms: Mark-sweep 1402.7 (1455.8) -> 1402.7 (1455.8) MB, 1481.8 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2fc54a1a5ee1 <JSObject>
    2: getRelationKey(aka getRelationKey) [/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:~27132] [pc=0x11326b6b0ec6](this=0x2fc5ccb82311 <undefined>,source=0x2fc551d97001 <Type map = 0x2fc53121d481>,target=0x2fc574935979 <Type map = 0x2fc53121d481>,relation=0x2fc529348871 <Map map = 0x2fc568f048d9>)
    3: isTypeRelatedTo(aka isTypeRelatedTo) [/Users/alden/Projects/krypton/nod...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 5: v8::internal::Factory::NumberToString(v8::internal::Handle<v8::internal::Object>, bool) [/usr/local/bin/node]
 6: v8::internal::Runtime_NumberToString(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x11326a40463d
[1]    8826 abort      tsc --noemit --watch --project .
```

I've reached out internally to see if we can give you access with an NDA. Will follow up when I hear back.

**Comment by sheetalkamat** [comment]
@aldendaniels Just want to make sure you dont run into this exception when you run tsc without watch option?

**Comment by aldendaniels** [comment]
@sheetalkamat That's correct. The exception only occurs in watch mode.

**Comment by aldendaniels** [comment]
@mhegazy To circle back on getting a repo - preference on our end would be to start digging on a screen-share to get a repro before granting access to the repo due to possible overhead on getting the NDA signed on both ends.

Let me know if this is something you'd be open to and thanks for the help regardless. It's worth noting that this issue isn't critical for us, because the IDE integration still works as well as the non-watch mode. We don't make heavy use of watch internally ATM.

**Comment by mhegazy** [comment]
I think we can arrange for a screen sharing session.

**Comment by aldendaniels** [comment]
Nice - thank you! Email is alden [at] coda [dot] io. Should be available to jump on a call during west-coast business hours.

**Comment by adavidof** [comment]
Fixed for me with `"typescript": "2.8.0-dev.20180213"`

**Comment by sheetalkamat** [comment]
@aldendaniels can you give a try to typescript@next to see if your issue still repros? If the issue still repros can you also try out environment variables and options as mentioned in #21243 to see if any of that helps?

**Comment by aldendaniels** [comment]
@sheetalkamat For starters, my baseline behavior as changed. We've upgraded to `2.7.2` and now when I run `tsc --noemit --watch --project .` the process hangs indefinitely (and burns CPU) but doesn't crash. 

I tried on `typescript@2.8.0-dev.20180308` and the process crashed with the following traceback:
```
7:41:27 AM - Starting compilation in watch mode...


/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:60890
                throw e;
                ^

Error: Debug Failure. False expression: Target symbol and symbol do not have the same name
    at getLiteralTypeFromPropertyName (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:26229:30)
    at Object.map (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:515:29)
    at getLiteralTypeFromPropertyNames (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:26241:36)
    at getIndexType (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:26249:33)
    at instantiateType (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:27069:28)
    at instantiateType (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:27072:91)
    at getTypeOfInstantiatedSymbol (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:23502:32)
    at getTypeOfSymbol (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:23524:24)
    at getTypeOfParameter (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:33998:24)
    at getTypeAtPosition (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:34010:53)
```

**Comment by sheetalkamat** [comment]
That assert failure is #22403 and is already fixed. Our nightly builds are not being published and is tracked in issue #22455. Once that is resolved you would be able to try out typescript@next

**Comment by aldendaniels** [comment]
@sheetalkamat Looks like that issue is fixed but there's still no build out - please let me know when the build is out and I'll retry

**Comment by Bnaya** [comment]
@aldendaniels looks like there's a new version `'2.8.0-dev.20180314': '2018-03-14T06:38:06.997Z' `

**Comment by aldendaniels** [comment]
@Bnaya thanks for the heads up. Looks like we get a new error now:

```
8:47:12 AM - Starting compilation in watch mode...


/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:61401
                throw e;
                ^

Error: Debug Failure. False expression: Deferring unused identifier check twice
    at registerForUnusedIdentifiersCheck (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:36999:26)
    at checkFunctionOrMethodDeclaration (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:36995:13)
    at checkMethodDeclaration (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:36110:13)
    at checkSourceElement (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:39110:28)
    at Object.forEach (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:306:30)
    at checkClassExpressionDeferred (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:38165:16)
    at checkDeferredNodes (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:39293:25)
    at checkSourceFileWorker (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:39317:17)
    at checkSourceFile (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:39300:13)
    at getDiagnosticsWorker (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:39355:17)
```

**Comment by sheetalkamat** [comment]
@aldendaniels The bug for the exception you were seeing, just got fixed. Please try out build that will be released tonight.

**Comment by aldendaniels** [comment]
@sheetalkamat Good news! Will do.

**Comment by mohsen1** [comment]
Getting `Deferring unused identifier check twice` in our project with 2.8 as well

**Comment by sheetalkamat** [comment]
@aldendaniels were you able to try the latest build out to see if the issue is fixed. Thanks

**Comment by aldendaniels** [comment]
Sorry, thanks for the ping. Now I'm getting this on `2.9.0-dev.20180323`:

```
Starting compilation in watch mode...


/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:2424
            throw e;
            ^

Error: Debug Failure. 272
    at bindThisPropertyAssignment (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:18480:30)
    at bindWorker (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:18224:29)
    at bind (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:18128:13)
    at visitNode (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:11188:24)
    at Object.forEachChild (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:11413:24)
    at bindEachChild (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:17085:16)
    at bindChildrenWorker (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:17182:21)
    at bindChildren (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:17055:17)
    at bind (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:18134:21)
    at /Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:17061:68
```

**Comment by sheetalkamat** [comment]
@aldendaniels Sorry that you are hitting different issues when trying our nightly builds. The exception you saw has been fixed. Can you try latest nightly build. Thank you.

**Comment by aldendaniels** [comment]
Hi @sheetalkamat looks like we're pack to the OOM error again on `2.9.0-dev.20180329`

```
9:29:28 PM - Starting compilation in watch mode...



<--- Last few GCs --->

[33124:0x104800000]   175648 ms: Mark-sweep 1405.1 (1452.9) -> 1405.1 (1451.9) MB, 1228.7 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1229 ms) last resort GC in old space requested
[33124:0x104800000]   176969 ms: Mark-sweep 1405.1 (1451.9) -> 1405.1 (1451.9) MB, 1321.2 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0xf627dd25ee1 <JSObject>
    2: /* anonymous */(aka /* anonymous */) [/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:62691] [bytecode=0xf62c9ae4b21 offset=0](this=0xf6255782311 <undefined>,_a=0xf6250f8f2d9 <JSArray[2]>)
    4: next [/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:672] [bytecode=0xf62c9ae48f9 offset=37](this=0xf6250f8f231 <Object map = 0xf6201244309>)
    5: arrayFrom [/...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/alden/Projects/krypton/build/.dev-coda-node/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/Users/alden/Projects/krypton/build/.dev-coda-node/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/Users/alden/Projects/krypton/build/.dev-coda-node/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/alden/Projects/krypton/build/.dev-coda-node/bin/node]
 5: v8::internal::Factory::NewByteArray(int, v8::internal::PretenureFlag) [/Users/alden/Projects/krypton/build/.dev-coda-node/bin/node]
 6: v8::internal::TranslationBuffer::CreateByteArray(v8::internal::Factory*) [/Users/alden/Projects/krypton/build/.dev-coda-node/bin/node]
 7: v8::internal::compiler::CodeGenerator::PopulateDeoptimizationData(v8::internal::Handle<v8::internal::Code>) [/Users/alden/Projects/krypton/build/.dev-coda-node/bin/node]
 8: v8::internal::compiler::CodeGenerator::FinalizeCode() [/Users/alden/Projects/krypton/build/.dev-coda-node/bin/node]
 9: v8::internal::compiler::PipelineImpl::FinalizeCode() [/Users/alden/Projects/krypton/build/.dev-coda-node/bin/node]
10: v8::internal::compiler::PipelineCompilationJob::FinalizeJobImpl() [/Users/alden/Projects/krypton/build/.dev-coda-node/bin/node]
11: v8::internal::Compiler::FinalizeCompilationJob(v8::internal::CompilationJob*) [/Users/alden/Projects/krypton/build/.dev-coda-node/bin/node]
12: v8::internal::OptimizingCompileDispatcher::InstallOptimizedFunctions() [/Users/alden/Projects/krypton/build/.dev-coda-node/bin/node]
13: v8::internal::StackGuard::HandleInterrupts() [/Users/alden/Projects/krypton/build/.dev-coda-node/bin/node]
14: v8::internal::Runtime_StackGuard(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/alden/Projects/krypton/build/.dev-coda-node/bin/node]
15: 0x211cc648463d
[1]    33124 abort      tsc --noemit --watch --project .
```

**Comment by sheetalkamat** [comment]
@aldendaniels Can you please try out typescript@next and see if this issue still repros. If it does can you get me the log by using ```--extendedDiagnostics```. Can you also see if the issue repros when doing normal build with ```--d``` option. That is ```tsc --d``` without ```--watch``` and ```--noemit```

**Comment by aldendaniels** [comment]
Hi @sheetalkamat - it does still crash in watch mode. Using extended diagnostics, I can see where it freezes:
```
... [hundreds of file watchers] ...

FileWatcher:: Added:: WatchInfo: /Users/alden/Projects/krypton/node_modules/typescript/lib/lib.dom.d.ts 250 Source file
FileWatcher:: Added:: WatchInfo: /Users/alden/Projects/krypton/node_modules/typescript/lib/lib.es2016.d.ts 250 Source file
FileWatcher:: Added:: WatchInfo: /Users/alden/Projects/krypton/node_modules/typescript/lib/lib.es2015.d.ts 250 Source file
FileWatcher:: Added:: WatchInfo: /Users/alden/Projects/krypton/node_modules/typescript/lib/lib.es2015.core.d.ts 250 Source file
FileWatcher:: Added:: WatchInfo: /Users/alden/Projects/krypton/node_modules/typescript/lib/lib.es2015.collection.d.ts 250 Source file
FileWatcher:: Added:: WatchInfo: /Users/alden/Projects/krypton/node_modules/typescript/lib/lib.es2015.generator.d.ts 250 Source file
FileWatcher:: Added:: WatchInfo: /Users/alden/Projects/krypton/node_modules/typescript/lib/lib.es2015.promise.d.ts 250 Source file
FileWatcher:: Added:: WatchInfo: /Users/alden/Projects/krypton/node_modules/typescript/lib/lib.es2015.iterable.d.ts 250 Source file
FileWatcher:: Added:: WatchInfo: /Users/alden/Projects/krypton/node_modules/typescript/lib/lib.es2015.symbol.d.ts 250 Source file
FileWatcher:: Added:: WatchInfo: /Users/alden/Projects/krypton/node_modules/typescript/lib/lib.es2015.proxy.d.ts 250 Source file
FileWatcher:: Added:: WatchInfo: /Users/alden/Projects/krypton/node_modules/typescript/lib/lib.es2015.reflect.d.ts 250 Source file
FileWatcher:: Added:: WatchInfo: /Users/alden/Projects/krypton/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts 250 Source file
FileWatcher:: Added:: WatchInfo: /Users/alden/Projects/krypton/node_modules/typescript/lib/lib.es5.d.ts 250 Source file
FileWatcher:: Added:: WatchInfo: /Users/alden/Projects/krypton/node_modules/typescript/lib/lib.es2016.array.include.d.ts 250 Source file
FileWatcher:: Added:: WatchInfo: /Users/alden/Projects/krypton/node_modules/typescript/lib/lib.dom.iterable.d.ts 250 Source file
FileWatcher:: Added:: WatchInfo: /Users/alden/Projects/krypton/node_modules/typescript/lib/lib.scripthost.d.ts 250 Source file
DirectoryWatcher:: Added:: WatchInfo: /Users/alden/Projects/krypton/node_modules/@types 1 Type roots

^[[B
<--- Last few GCs --->

[57040:0x105000000]   166546 ms: Mark-sweep 1401.6 (1475.4) -> 1401.5 (1475.4) MB, 1296.9 / 0.0 ms  allocation failure GC in old space requested
[57040:0x105000000]   167876 ms: Mark-sweep 1401.5 (1475.4) -> 1401.5 (1443.4) MB, 1329.3 / 0.0 ms  last resort GC in old space requested
[57040:0x105000000]   169091 ms: Mark-sweep 1401.5 (1443.4) -> 1401.5 (1442.9) MB, 1214.9 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0xf5142a257c1 <JSObject>
    1: set(this=0xf5155ba4e39 <Map map = 0xf51a46048d9>,0xf51fc95cc91 <String[13]: 236302,236301>,1)
    2: recursiveTypeRelatedTo(aka recursiveTypeRelatedTo) [/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:~30017] [pc=0x34713ae20bbf](this=0xf5109e822d1 <undefined>,source=0xf51737829e9 <Type map = 0xf51a465f481>,target=0xf51737829b9 <Type map = 0xf5153393349>,reportErrors=0xf510...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/alden/Projects/krypton/build/.dev-coda-node/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/Users/alden/Projects/krypton/build/.dev-coda-node/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/Users/alden/Projects/krypton/build/.dev-coda-node/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/alden/Projects/krypton/build/.dev-coda-node/bin/node]
 5: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/Users/alden/Projects/krypton/build/.dev-coda-node/bin/node]
 6: v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Rehash(v8::internal::Handle<v8::internal::OrderedHashMap>, int) [/Users/alden/Projects/krypton/build/.dev-coda-node/bin/node]
 7: v8::internal::Runtime_MapGrow(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/alden/Projects/krypton/build/.dev-coda-node/bin/node]
 8: 0x34713a4842fd
 9: 0x34713a53251e
```

Running `tsc --d --project . ` also crashes with the same OOM error

**Comment by weswigham** [comment]
@aldendaniels Can you run `tsc --extendedDiagnostics --noEmit --project .` and post the output (should have times and numbers) so we can get an idea of how large the project is (in terms of our internal objects), or does that crash, too?

**Comment by weswigham** [comment]
Yeah, that OOM isn't related to declarations or watch mode at all (and it runs oom while still typechecking) - without a repro it's going to be incredibly hard to debug! Then again, you said the project was >2700 files, right? Projects of that size are usually _incredibly_ sensitive to increased memory usage on our part (even slightly) because they're already at or near the process limit. Does the project compile if you run the compiler with more memory allocated to node? (eg, `node --max_old_space_size=4096 /path/to/tsc.js --otheroptions`) If it _does_ then it's just that our memory usage went up a bit and the project is too large for us to build all at once now (but we have some upcoming stuff that could help), if it doesn't, then there's a serious bug causing us to consume exponential memory for _something_ that's going to be hard to fix without a repro of some kind.

**Comment by aldendaniels** [comment]
@weswigham Yes, pumping the memory allotment for node does the trick. Sorry for the red herring. I'd been using an alias a coworker had added for the normal run, so I didn't realize we'd bumped the memory requirement until running in watch mode. You're correct that this isn't watch-mode related.

> We have some upcoming stuff that could help

This would be great. Generally, typescript performance is becoming painful for us. We migrated from flow to typescript sometime back - it's been a good conversion on several fronts, but performance has been inferior - admittedly it's not an apples-to-apples comparison as we we've typed more code since the conversion. Still, we noticed the difference immediately. I realize that our project is larger than most and there's optimizations we can make by compartmentalizing our builds, etc.

Examples include:
 1. High memory usage.
 2. 10 second TS overhead running a test
 3. Slower webpack builds
 3. Over a minute on a fast laptop to typecheck the repo
 4. For some reason VSCode is responsive but Webstorm is slow

I realize there's no easy fix (feel free to close this issue) but thought I'd drop the feedback as you evaluate prioritization choices.

**Comment by aldendaniels** [comment]
@mhegazy Thank you! This would be great. Can you shoot me an email (alden at coda dot io) and we can take it from there?

**Comment by mhegazy** [comment]
my email is `mhegazy` at `microsoft` dot `com`.

**Comment by aldendaniels** [comment]
Thanks! Moved to email.

**Comment by RyanCavanaugh** [comment]
@aldendaniels are you still hitting this? mhegazy no longer works on TypeScript so we'll need to get a fresh copy of the repro if so
