### ISSUE TITLE
TSServer IntelliSense breaks when typing path with ../../..s

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#23556]
_From @gabrielruss on April 19, 2018 17:16_

- VSCode Version: 1.22.2
- OS Version: Windows 10

Steps to Reproduce:

1. Try to import a file multiple layers deep
2. After doing step 1 a few times, Intellisense will break and you will need to restart in order to get it back.

Does this issue occur when all extensions are disabled?: Yes

![2018-04-19 13_14_34](https://user-images.githubusercontent.com/8887997/39007438-d09bae48-43d3-11e8-9154-2c525755d640.png)

_Copied from original issue: Microsoft/vscode#48224_

**Comment by mjbvz** [comment]
Can you please test upgrading to `typescript@next` in your workspace by following these instructions: https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions

**Comment by mjbvz** [comment]
_From @gabrielruss on April 20, 2018 0:35_

1. Updated global typescript package with `npm install -g typescript@next`
2. opened VSCode `code --disable-extensions .`

Issue remains

![broke](https://user-images.githubusercontent.com/8887997/39024776-0bd51dae-4411-11e8-941a-e585026e9972.gif)

**Comment by mjbvz** [comment]
Moving over to TS repo to continue investigation. 

@gabrielruss Can you try collecting the  TypeScript server logs:

1. Add `"typescript.tsserver.log": "verbose"` to your user settings and restart VSCode.
2. Reproduce the issue
3. In VS Code in a js file, run the TypeScript: Open TS server log command`. This should open a folder with a `tsserver.log` file in it

Look for errors, stack traces, or other suspicious info near the end of the logs. If you can share the logs I or someone on the TS team can try looking through them to see what is going on

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by gabrielruss** [comment]
Here you go. 
[tsserver.zip](https://github.com/Microsoft/TypeScript/files/1930389/tsserver.zip)

**Comment by sheetalkamat** [comment]
@gabrielruss  can you please try out typescript@next I believe this is fixed now.

**Comment by gabrielruss** [comment]
I thought I installed typescript@next via the `npm install -g` command yesterday but I tried again just now. When I do a `npm list -g --depth=0` it says that I have `typescript@2.9.0-dev.20180420`. Here is another log with the issue still happening. Is there some cached version of TypeScript I am using or something? 

[tsserver.zip](https://github.com/Microsoft/TypeScript/files/1933190/tsserver.zip)

**Comment by mjbvz** [comment]
@gabrielruss After install, you need to then select that version of TypeScript in your workspace: https://code.visualstudio.com/Docs/languages/typescript#_using-the-workspace-version-of-typescript 

We don't activate it automatically for security reasons

**Comment by gabrielruss** [comment]
OH ok sorry that I missed that the first time. Well I got the new version going and I was still able to reproduce it unfortunately. Here is the file.

[tsserver.zip](https://github.com/Microsoft/TypeScript/files/1933250/tsserver.zip)

**Comment by sheetalkamat** [comment]
@gabrielruss From the log i cannot see any completion request that took more than 200ms. There were only two project updates that were 1s long (initial one and after adding all the typings for your project) that you can expect with such a large project.

**Comment by gabrielruss** [comment]
Ok I am not sure what happened before but yeah...I can't reproduce now that I double checked. Sorry about the confusion. Thank you all so much for the help! So I guess this fix will be included in 2.9?

**Comment by sheetalkamat** [comment]
@gabrielruss Yes.
