### ISSUE TITLE
Crash in getJSDocTags on `const a = b = () => 0;`

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#24963]
**TypeScript Version:**  3.0.0-dev.20180609

**Code**

**a.js**
```ts
/** doc */
const a = b = () => 0;
```

**Expected behavior:**

No crash.

**Actual behavior:**

```
Error: Debug Failure. False expression.
    at getJSDocTags (/home/andy/.nvm/versions/node/v10.1.0/lib/node_modules/typescript/lib/tsc.js:10444:22)
    at getFirstJSDocTag (/home/andy/.nvm/versions/node/v10.1.0/lib/node_modules/typescript/lib/tsc.js:10451:24)
    at Object.getJSDocType (/home/andy/.nvm/versions/node/v10.1.0/lib/node_modules/typescript/lib/tsc.js:10428:19)
    at getContextualSignature (/home/andy/.nvm/versions/node/v10.1.0/lib/node_modules/typescript/lib/tsc.js:34131:32)
    at checkFunctionExpressionOrObjectLiteralMethod (/home/andy/.nvm/versions/node/v10.1.0/lib/node_modules/typescript/lib/tsc.js:36920:43)
    at checkExpressionWorker (/home/andy/.nvm/versions/node/v10.1.0/lib/node_modules/typescript/lib/tsc.js:37846:28)
    at checkExpression (/home/andy/.nvm/versions/node/v10.1.0/lib/node_modules/typescript/lib/tsc.js:37779:42)
    at checkBinaryLikeExpression (/home/andy/.nvm/versions/node/v10.1.0/lib/node_modules/typescript/lib/tsc.js:37393:29)
    at checkBinaryExpression (/home/andy/.nvm/versions/node/v10.1.0/lib/node_modules/typescript/lib/tsc.js:37385:20)
    at checkExpressionWorker (/home/andy/.nvm/versions/node/v10.1.0/lib/node_modules/typescript/lib/tsc.js:37867:28)
```

CC @sandersn

**Comment by mhegazy** [comment]
@sandersn can you take a look.

**Comment by sandersn** [comment]
The assert is the one that detects duplicated jsdoc tags. `() => 0` is getting `doc` added twice.

**Comment by MLoughry** [comment]
Is there any plan to release a 2.9.3 with this fix?

**Comment by larssn** [comment]
Pretty please?

**Comment by RyanCavanaugh** [comment]
TypeScript 3.0 is out, which contains a fix for this issue and doesn't have any major breaking changes associated with it. I'd recommend upgrading to that version as we don't plan to backport a new 2.9 release at this time.

**Comment by larssn** [comment]
Thanks Ryan, we're stuck using 2.9.2 due to Angular 6 though. Thanks anyway.

**Comment by rodrigoEclipsa** [comment]
also this with angle 6, can we solve it in some way?

**Comment by andy-ms** [comment]
@rodrigoEclipsa Try looking for double assignments `a = b = c` in your program and breaking them up to `b = c; a = b;`.

**Comment by ClemensSchneider** [comment]
Just in the progress of upgrading from Angular 5 to 6 and stumbled upon this issue, too. As there aren't any plans for Angular 6 to be upgraded to TypeScript 3 and there aren't any plans to backport this fix to the TypeScript 2.9 branch it seems that there isn't any chance to upgrade to Angular 6 :(

**Comment by mrowles** [comment]
Does anyone have a fix for angular@6 yet? I don't have any double assignments, it's  referencing`crypto-js@^3.1.9-1` for me

**Comment by stormit-vn** [comment]
I am facing this issue too, waiting for resolutions

**Comment by sandersn** [comment]
It's probably easiest to fix crypto-js since that's the library everybody on this thread depends on.

**Comment by sandersn** [comment]
Actually, I wonder why crypto-js is being checked. If it has a d.ts file, then it should never check the JS file at all. For future investigation:

1. Do you have allowJs on? 
2. Do you have `@types/crypto-js` installed?

**Comment by mrowles** [comment]
It also fails with @types/crypto-js installed, but have not tried allowJs yet, will check in a minute

**Comment by mrowles** [comment]
@sandersn allowJS true/false makes no difference. I've tried a number of combinations.

My specific problem, and I'd garner a bet that this would be most peoples, it appears that it's the AWS Cognito suite that is using this library. `aws-amplify`, which uses another library `amazon-cognito-identity-js` that utilizes `crypto-js`.

**Comment by stormit-vn** [comment]
I  got the same error when trying to use `aws-amplify`. Hope we can find out a solution to fix this issue soon

**Comment by sandersn** [comment]
@stormit-vn Does angular 7 still use typescript 2.9?

@mrowles @stormit-vn I modified crypto-js. Can you try installing from my branch to see if it works? I think this is the command:  `npm install git://github.com/sandersn/crypto-js.git#typescript-2.9-workaround`.

**Comment by D2KX** [comment]
@sandersn Angular 7 is targeting TypeScript 3.1.3, but is not released yet (currently in release candidate stage). Haven't checked if it fixes the issue, but am probably going to, because I also suffer from this issue with my Angular 6 + AWS Amplify app (crypto-js dep.).

**Comment by mrowles** [comment]
@sandersn Thanks for your efforts mate, very much appreciated. Unfortunately this didn't seem to work in my project, with various configs. I get these errors, perhaps I need to fork and update `amazon-cognito-identity-js`:

```
70% building modules 1178/1178 modules 0 activeModuleNotFoundError: Module not found: Error: Can't resolve 'crypto-js' in '/Users/username/workspace/project/node_modules/amazon-cognito-identity-js/es'
    at factory.create (/Users/username/workspace/project/node_modules/webpack/lib/Compilation.js:547:10)
    at factory (/Users/username/workspace/project/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/Users/username/workspace/project/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/Users/username/workspace/project/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /Users/username/workspace/project/node_modules/neo-async/async.js:2772:7
    at /Users/username/workspace/project/node_modules/neo-async/async.js:6730:13
    at normalResolver.resolve (/Users/username/workspace/project/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/Users/username/workspace/project/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/Users/username/workspace/project/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/username/workspace/project/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at resolver.doResolve (/Users/username/workspace/project/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/username/workspace/project/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/username/workspace/project/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at hook.callAsync (/Users/username/workspace/project/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/username/workspace/project/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:12:1)
    at resolver.doResolve (/Users/username/workspace/project/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/Users/username/workspace/project/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn40 (eval at create (/Users/username/workspace/project/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:372:1)
    at resolver.doResolve (/Users/username/workspace/project/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:23:37)
    at hook.callAsync (/Users/username/workspace/project/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/username/workspace/project/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at hook.callAsync (/Users/username/workspace/project/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn1 (eval at create (/Users/username/workspace/project/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:24:1)
    at hook.callAsync (/Users/username/workspace/project/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/username/workspace/project/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at resolver.doResolve (/Users/username/workspace/project/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/username/workspace/project/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/username/workspace/project/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at hook.callAsync (/Users/username/workspace/project/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/username/workspace/project/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:12:1)
    at resolver.doResolve (/Users/username/workspace/project/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/Users/username/workspace/project/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn41 (eval at create (/Users/username/workspace/project/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:384:1)
    at hook.callAsync (/Users/username/workspace/project/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/username/workspace/project/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:12:1)
    at resolver.doResolve (/Users/username/workspace/project/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
resolve 'crypto-js' in '/Users/username/workspace/project/node_modules/amazon-cognito-identity-js/es'
  Parsed request is a module
  using description file: /Users/username/workspace/project/node_modules/amazon-cognito-identity-js/package.json (relative path: ./es)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in /Users/username/workspace/project/src
        using description file: /Users/username/workspace/project/package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /Users/username/workspace/project/package.json (relative path: ./src/crypto-js)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/username/workspace/project/src/crypto-js doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/username/workspace/project/src/crypto-js.mjs doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/username/workspace/project/src/crypto-js.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/username/workspace/project/src/crypto-js.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/username/workspace/project/src/crypto-js.json doesn't exist
            as directory
              /Users/username/workspace/project/src/crypto-js doesn't exist
      looking for modules in /Users/username/workspace/project/node_modules
        using description file: /Users/username/workspace/project/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /Users/username/workspace/project/node_modules/crypto-js/package.json (relative path: .)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/username/workspace/project/node_modules/crypto-js is not a file
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/username/workspace/project/node_modules/crypto-js.mjs doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/username/workspace/project/node_modules/crypto-js.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/username/workspace/project/node_modules/crypto-js.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/username/workspace/project/node_modules/crypto-js.json doesn't exist
            as directory
              existing directory
                use ./index.js from main in package.json
                  using description file: /Users/username/workspace/project/node_modules/crypto-js/package.json (relative path: .)
                    Field 'browser' doesn't contain a valid alias configuration
                    using description file: /Users/username/workspace/project/node_modules/crypto-js/package.json (relative path: ./index.js)
                      no extension
                        Field 'browser' doesn't contain a valid alias configuration
                        /Users/username/workspace/project/node_modules/crypto-js/index.js doesn't exist
                      .mjs
                        Field 'browser' doesn't contain a valid alias configuration
                        /Users/username/workspace/project/node_modules/crypto-js/index.js.mjs doesn't exist
                      .ts
                        Field 'browser' doesn't contain a valid alias configuration
                        /Users/username/workspace/project/node_modules/crypto-js/index.js.ts doesn't exist
                      .js
                        Field 'browser' doesn't contain a valid alias configuration
                        /Users/username/workspace/project/node_modules/crypto-js/index.js.js doesn't exist
                      .json
                        Field 'browser' doesn't contain a valid alias configuration
                        /Users/username/workspace/project/node_modules/crypto-js/index.js.json doesn't exist
                      as directory
                        /Users/username/workspace/project/node_modules/crypto-js/index.js doesn't exist
                using path: /Users/username/workspace/project/node_modules/crypto-js/index
                  using description file: /Users/username/workspace/project/node_modules/crypto-js/package.json (relative path: ./index)
                    no extension
                      Field 'browser' doesn't contain a valid alias configuration
                      /Users/username/workspace/project/node_modules/crypto-js/index doesn't exist
                    .mjs
                      Field 'browser' doesn't contain a valid alias configuration
                      /Users/username/workspace/project/node_modules/crypto-js/index.mjs doesn't exist
                    .ts
                      Field 'browser' doesn't contain a valid alias configuration
                      /Users/username/workspace/project/node_modules/crypto-js/index.ts doesn't exist
                    .js
                      Field 'browser' doesn't contain a valid alias configuration
                      /Users/username/workspace/project/node_modules/crypto-js/index.js doesn't exist
                    .json
                      Field 'browser' doesn't contain a valid alias configuration
                      /Users/username/workspace/project/node_modules/crypto-js/index.json doesn't exist
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project@0.0.1 webpack: `node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "config/webpack.prod.js" "--mode" "production" "--progress" "--profile" "--bail"`
npm ERR! Exit status 1
```

I believe angular@7 removes the <2.10 dependency.

**Comment by sandersn** [comment]
@mrowles Can you try something like

```
$ cd node_modules/crypto-js
$ npm install
$ npm run build     # I needed to install grunt first
```

I suspect that the version installed from github doesn't have files in the right places.

It's also possible that 3.1.9-1 didn't get installed in the top-level node_modules, but underneath amazon-cognito-identity, and that the github-installed version isn't being resolved at all.

**Comment by D2KX** [comment]
FWIW, I did a very brief test with a straight-forward upgrade to Angular 7.0.0-rc.1, Angular CLI 7.0.0-rc.3 and TypeScript 3.1.x with an AWS-Amplify/crypto-js project that failed before and it actually works now.

**Comment by mrowles** [comment]
Wonder what is different? I upgraded to the following and still no luck, exactly the same errors (even after a clean npm install):
```
"dependencies": {
  "@angular/animations": "7.0.0-rc.1",
  "@angular/cdk": "6.4.7",
  "@angular/common": "7.0.0-rc.1",
  "@angular/compiler": "7.0.0-rc.1",
  "@angular/core": "7.0.0-rc.1",
  "@angular/forms": "7.0.0-rc.1",
  "@angular/material": "6.4.7",
  "@angular/material-moment-adapter": "6.4.7",
  "@angular/platform-browser": "7.0.0-rc.1",
  "@angular/platform-browser-dynamic": "7.0.0-rc.1",
  "@angular/platform-server": "7.0.0-rc.1",
  "@angular/router": "7.0.0-rc.1",
  "aws-amplify": "1.1.6",
  ...
  "crypto-js": "^3.1.9-1",
  ...
},
"devDependencies": {
  "@angular-devkit/build-angular": "0.8.5",
  "@angular-devkit/build-optimizer": "0.8.5",
  "@angular/cli": "7.0.0-rc.3 ",
  "@angular/compiler-cli": "7.0.0-rc.1",
  "@angular/language-service": "7.0.0-rc.1",
  "@types/crypto-js": "3.1.43",
  ...
  "typescript": "3.1.3",
  ...
}
```

I also tried to use @sandersn PR sha to no avail :(

**Comment by mrowles** [comment]
I have updated the following packages and my errors have changed, so possibly resolving the previous problems in case it works for the others:

```
devDependencies: {
  "@angular-devkit/build-optimizer": "0.9.0-rc.3",
  "@ngtools/webpack": "7.0.0-rc.3",
  "uglifyjs-webpack-plugin": "2.0.1",
}
```

My errors are now potentially related to something else:

```
ERROR in ./node_modules/amazon-cognito-identity-js/es/CognitoUser.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'flags' of undefined
    at isRelatedTo (/Users/username/workspace/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:40600:28)
```

I've installed `amazon-cognito-identity-js@3.0.3` which still didn't fix this issue, but this might be a config issue with webpack or some such, i'll keep digging.

**Comment by sandersn** [comment]
Well, it’s still a crash in tsc, but in a different place. Can you run `node <tsc-path-inside-angular-devkit> —version` and see if or something newer?

**Comment by mrowles** [comment]
@sandersn It is using 8.9.4, so I downgraded my version to the same (from 9.x) but still no luck.

**Comment by mrowles** [comment]
With the actual release of angular@7 today, along with @ngtools/webpack@7.0.1 + @angular-devkit/build-optimizer@0.10.1 - this is now working!

Big thanks to @sandersn for the help dude!

**Comment by stormit-vn** [comment]
Thank you all for your help. We now able to build the bundler. 

Cheers!

**Comment by MikeAlexMartinez** [comment]
Is there a fix for this issue if you are still using Angular v6?

**Comment by JamDoughnnut** [comment]
For Angular v6 try version 3.1.2-2

**Comment by chenghongm** [comment]
following @andy-ms comment, I manually broken down all double assignment  a= b = c  into a= b; b= c  in these two files of ./node_modules/crypto-js/core.js and ./node_modules/crypto-js/cipher-core.js; **then error gone!!**

my angular version: 

![image](https://user-images.githubusercontent.com/39807264/142283299-d49bf936-47ad-4b78-9e32-d59858b995bd.png)
