### ISSUE TITLE
JSDoc @typedef not working as expected

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#25386]
_From @ffxsam on June 29, 2018 16:44_

 

- VSCode Version: 1.24.1
- OS Version: macOS 10.13.5

`@typedef` support seems a bit buggy. There are a couple of things going on, but related.

First, typdefs with properties don't seem to work as expected. I have the following file, `funcs.js`:

```js
/**
 * API options.
 * @typedef {Object} ApiOptions
 * @property {number} artificialDelay Number of milliseconds for an artificial delay
 * @property {boolean} debug Debug mode
 */

/**
 *
 * @param {string} url URL to call
 * @param {ApiOptions} [options] API options
 */
export function apiCall(url, options = {}) {}
```

And in `index.js`, I import `apiCall` but the JSDoc hints don't show the properties of `ApiOptions`:

<img width="501" alt="screen_shot_2018-06-29_at_11_17_05_am__2_" src="https://user-images.githubusercontent.com/12532733/42103245-192acde6-7b8e-11e8-905f-ad03b69d1e56.png">

Also, typdefs should be able to be "exportable". I modified `funcs.js` to this:

```js
/** @module api */

/**
 * API options.
 * @typedef {Object} module:api.ApiOptions
 * @property {number} artificialDelay Number of milliseconds for an artificial delay
 * @property {boolean} debug Debug mode
 */

/**
 *
 * @param {string} url URL to call
 * @param {module:api.ApiOptions} [options] API options
 */
export function apiCall(url, options = {}) {}
```

I added a new file called `middle.js`:

```js
import { apiCall } from './funcs';

/**
 *
 * @param {module:api.ApiOptions} options
 */
export function test(options) {}
```

VSCode doesn't seem to understand this usage at all:

<img width="381" alt="screen_shot_2018-06-29_at_11_42_20_am__2_" src="https://user-images.githubusercontent.com/12532733/42104322-b7b5d85e-7b91-11e8-91b8-d4ec9ac7015b.png">

It would be great if VSCode fully supported this for projects that aren't using TypeScript.

Does this issue occur when all extensions are disabled?: Yes

_Copied from original issue: Microsoft/vscode#53348_

**Comment by mjbvz** [comment]
_From @Lenophie on June 30, 2018 22:10_

What's weird is Intellisense/VSCode already exports typedef across a project by default BUT it can fail if the custom type uses other custom types.
Here are some test cases.
*****
Declaration of ```CustomType``` in a file :
![image](https://user-images.githubusercontent.com/40424734/42129265-744a1226-7cc0-11e8-8bb5-70b5dff3d173.png)
Declaration of a variable of type ```CustomType```  in another file :
![image](https://user-images.githubusercontent.com/40424734/42129270-a3bf8734-7cc0-11e8-83b1-8058f0079f30.png)
*Quick info works.* 👍 
*Displayed type is correct.* 👍 
*Displayed type property is correct.* 👍 
*****
Declaration of ```CustomType``` using another custom type ```CustomType2``` in a file :
![image](https://user-images.githubusercontent.com/40424734/42129286-11b7a406-7cc1-11e8-8b43-df61d217a54c.png)
Declaration of a variable of type ```CustomType```  in another file :
![image](https://user-images.githubusercontent.com/40424734/42129289-389dd5b8-7cc1-11e8-83d2-94bfe7b2c20a.png)
*Quick info doesn't work.* 👎 
*****
Declaration of ```CustomType``` using another custom type ```CustomType2``` AND declaration of a variable of type ```CustomType``` in the same file :
![image](https://user-images.githubusercontent.com/40424734/42129293-735b244e-7cc1-11e8-9286-21a7ea72e32c.png)
*Quick info works.* 👍 
*Displayed type is correct.* 👍 
*Displayed type property is correct.* 👍 
*****
Declaration of ```CustomType``` AND declaration of a variable of type ```CustomType``` in the same file BUT declaration of ```CustomType2``` in another file :
![image](https://user-images.githubusercontent.com/40424734/42129303-a8638424-7cc1-11e8-8af0-e53b4708fa68.png)
*Quick info works.* 👍 
*Displayed type is correct.* 👍 
*Displayed type property is wrong.* 👎 
*****
I hope this breakdown of different cases help solve the issue !

**Comment by mjbvz** [comment]
Please try upgrading your workspace to use `typescript@next` by following [these instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions). Which of these issues still exists when using typescript@next?

**Comment by andy-ms** [comment]
The `{module:api.ApiOptions}` syntax isn't currently supported. If you enable `"checkJs": true` in `compilerOptions` in your `tsconfig.json`, you'll see errors at JSDoc that's not supported.

**Comment by ffxsam** [comment]
I installed `typescript@next` globally and updated my VSCode settings as such:

This still doesn't show the options:

![image](https://user-images.githubusercontent.com/12532733/42234203-61763558-7eb9-11e8-968d-3d4531b5efae.png)

However, if I start to type an option, it does display. I think I shouldn't have to start typing in order to see what options are available.

![image](https://user-images.githubusercontent.com/12532733/42234239-89f3dc1a-7eb9-11e8-88ff-35c3c0ddc2cb.png)

**Comment by mhegazy** [comment]
here is what i see on `typescript@next`:

![image](https://user-images.githubusercontent.com/8000722/42244672-c9f7aee8-7eca-11e8-8d83-a40f117b2015.png)

**Comment by bennidi** [comment]
I see a similar behavior when using a typedef reference in @return tag
```js

/**
 * @typedef {object} CancelReservationResult
 * @property {number} updated 1 if the vehicle was updated, zero otherwise
 * @property {boolean} [vehicle] - The updated vehicle
 * @property {boolean} [reservation] - The former reservation of the updated vehicle
 * @memberof VehicleService
 */
//some code in between
  /**
   * @summary Remove a reservation from a vehicle if that reservation is owned by the given user
   *
   * @param {Object} params
   * @param {Number} vehicleId The vehicle that will have its reservation removed
   * @param {Number} userId The user holding the reservation
   * @returns {VehicleService.CancelReservationResult}
   */
  // service method declaration...
```

The returns section in intellisense is completely empty. I have tried referencing the type with different patterns. jsdoc picks it up correctly.

**Comment by andy-ms** [comment]
@bennidi I created #25579 which is likely the issue there.

**Comment by Lenophie** [comment]
The imports problem highlighted in my previous comment seem to be fixed in the latest VSCode version. (All the custom types on this screenshot come from a different file)
![image](https://user-images.githubusercontent.com/40424734/42619373-2a0002ba-85b8-11e8-8f53-bd32439150b7.png)
🍾 🍾 🍾 🍾 🍾

**Comment by ffxsam** [comment]
@Lenophie I'm not familiar with that syntax, what is it?

**Comment by mhegazy** [comment]
Should be working correctly in latest drop of TypeSript (`typescript@next`). VSCode ships with an older version of TypeScript. Please see [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) documentation for more details on updating your VSCode to use a different version of TypeScript.

**Comment by waynebloss** [comment]
After setting VSCode to use `typescript@next`, typedefs again work as expected.

Here is what I did:

1.)
```sh
> mkdir \usr && cd \usr
> npm install typescript@next
```
2.) Change vscode settings:

```json
{
  "typescript.tsdk": "C:\\usr\\node_modules\\typescript\\lib",
}
```

3.) Restart VSCode

**Comment by ffxsam** [comment]
None of the above works for me.

![image](https://user-images.githubusercontent.com/12532733/42654442-3c593f28-85de-11e8-8f08-91b5e752d8ce.png)

`options` is never spelled out as showing what the options are. But in the actual JS file where the `ApiOptions` typedef is defined, it at least shows it (though it doesn't list the properties in the popup):

![image](https://user-images.githubusercontent.com/12532733/42654535-87777f56-85de-11e8-9c6f-de4f7d9590f3.png)

But if I get to that final argument and hit ctrl-space to trigger suggestions, I see the properties:

![image](https://user-images.githubusercontent.com/12532733/42654569-a71877ca-85de-11e8-9a4a-6719ed9312aa.png)

I've tried stable TypeScript and `typescript@next`.

**Comment by andy-ms** [comment]
@ffxsam The `{module:api.ApiOptions}` syntax isn't supported. Try just `@typedef {Object} ApiOptions` and reference it with `{ApiOptions}` (in the same module) or `{import("./funcs").ApiOptions}` (from a different module).

**Comment by ffxsam** [comment]
@andy-ms I did change my syntax to use `import()` instead. It still doesn't work for me.

**Comment by andy-ms** [comment]
OK, could you write down the full updated example? For example, the following is working for me:

**a.js**
```js
/**
 * @typedef {object} T
 * @property {number} x
 */
export {};
```

**b.js**
```js
/** @type {import("./a").T} */
const o = { x: 0 };
```

Did discover #25624 though.

**Comment by ffxsam** [comment]
Confirmed, I started a fresh folder with three simple files and it works (even with the built-in version of TypeScript), though maybe not ideally.

**core.js**
```js
/**
 * @typedef {object} ApiOptions
 * @property {boolean} debugMode
 * @property {number} delay
 */

/**
 * Does stuff.
 * @param {ApiOptions} [options]
 */
export function magic(options) {}
```

**helpers.js**
```js
import { magic } from './core';

/**
 * Wrapper func.
 * @param {import('./core').ApiOptions} [options]
 */
export function wrapper(options) {
  magic(options);
}
```

**index.js**
```js
import { wrapper } from './helpers';

wrapper({});
```

Now, in index.js, when I type `wrapper({`, it would be nice if it expanded `ApiOptions` and showed me what the options were. I swear it did this once, but I haven't seen it do this since then. Instead, I see this:

![image](https://user-images.githubusercontent.com/12532733/42945699-a88b8c0a-8b2e-11e8-8ba1-52804bc3f9ff.png)

If I hit the key shortcut for Trigger Suggest, though, then I see the individual options in the typedef:

![image](https://user-images.githubusercontent.com/12532733/42945733-c1ef1194-8b2e-11e8-988e-13b4d231a76e.png)

**Comment by ffxsam** [comment]
Ah, never mind. I was missing the `import` in my referenes to `ApiOptions`. Also, it works fine in JS files, but not Vue files, so this is now a Vetur issue.

**Comment by chrisaljoudi** [comment]
@ffxsam hey—sorry to hijack, and this has obviously been a while. I've been trying to get the exact behavior you're talking about: the individual options/properties defined inside a `typedef` to expand automatically inside what VS Code shows in its tooltip. I simply cannot get that behavior to occur. It always seems to require doing the Trigger Suggest keyboard shortcut.

Is this still 'working' for you? Is doing something special/particular needed?

**Comment by ffxsam** [comment]
Hey @chrisaljoudi, I honestly couldn't tell you, as I've stopped using JSDoc and entirely use TypeScript annotations to document my stuff, and it works like a charm.

**Comment by qiulang** [comment]
I am using vscode 1.51 (the latest one as in 2020.12) but I still can't get typedef object's property show. So I stick with

```
 * @param {Object}  objectA
 * @param {number} objectA.property1
 * @param {string} objectA.property2
```

**Comment by sageyx2002** [comment]
> I am using vscode 1.51 (the latest one as in 2020.12) but I still can't get typedef object's property show. So I stick with
> 
> ```
>  * @param {Object}  objectA
>  * @param {number} objectA.property1
>  * @param {string} objectA.property2
> ```

This however does not work on a return statement. If you want to use `@returns` you'll have to use `@typedef` on the return statement or use `@returns {{ foo: string, bar: number }}` which can be really annoying especially for larger objects. If you do use typedef, you'll have to follow the link to the function and then hover over the return tag, to see the parameters of the returned object, instead of getting a breakdown of the object when you hover the initial function.

I would love if that was fixed by default, because as of now, this looks like
```js
function myFooBar(foo: string, bar: number): fooBar
```
with fooBar having no description on hover and no direct link, when using JSDoc like so:
```js
/**
 * @param {string} foo
 * @param {number} bar
 * @returns {fooBar}
 */
function myFooBar(foo, bar) {
    /**
     * @typedef {object} fooBar
     * @property {string} fooBar.foo
     * @property {number} fooBar.bar
     */    
    return { foo, bar };
};
```

but I get a much more clear

```js
function myFooBar(foo: string, bar: number): {
    foo: string;
    bar: number;
}
```
when I use JSDoc like so:
```js
/**
 * @param {string} foo
 * @param {number} bar
 * @returns {{ foo: string, bar: number }}
 */
function myFooBar(foo, bar) {
    return { foo, bar };
};
```
which is.. awful - of course this is an example, and whether or not you would write a typedef for a function this small is irrelevant, but for some bigger projects this could make things a lot more convenient  -if I have to constantly hop between modules, I'm wasting more time going back and forth than understanding the 30+ key objects I may work with.
