### ISSUE TITLE
Property ? is missing in wrong type

### ISSUE THREAD

**Issue by domoritz** [microsoft/TypeScript#28017]
I'm seeing a regression where code that works in 3.1 does not work in tsnext. It seems like typescript is not looking at the right type (`ContourTransform`) and tried to match against a different type (`WordcloudTransform`).

**TypeScript Version:**  @next (3.2) but not 3.1

**Search Terms:** Property ? is missing in type

**Code**

https://github.com/vega/vega-typings/blob/master/tests/spec/examples.ts#L3394

**Expected behavior:**

The tests should not fail and they work fine in ts 3.1. 

**Actual behavior:**

https://travis-ci.org/vega/vega-typings/jobs/444180003

```
ERROR: 3394:3  expect  TypeScript@next compile error: 
Type '({ name: string; url: string; transform: { type: "filter"; expr: string; }[]; } | { name: string; source: string; transform: { type: "contour"; x: { expr: string; }; y: { expr: string; }; size: { signal: string; }[]; count: { ...; }; }[]; })[]' is not assignable to type 'Data[]'.
  Type '{ name: string; url: string; transform: { type: "filter"; expr: string; }[]; } | { name: string; source: string; transform: { type: "contour"; x: { expr: string; }; y: { expr: string; }; size: { signal: string; }[]; count: { ...; }; }[]; }' is not assignable to type 'Data'.
    Type '{ name: string; source: string; transform: { type: "contour"; x: { expr: string; }; y: { expr: string; }; size: { signal: string; }[]; count: { signal: string; }; }[]; }' is not assignable to type 'Data'.
      Type '{ name: string; source: string; transform: { type: "contour"; x: { expr: string; }; y: { expr: string; }; size: { signal: string; }[]; count: { signal: string; }; }[]; }' is not assignable to type '{ url: string | SignalRef; } & { name: string; on?: OnTrigger[] | undefined; format?: FormatJSON | FormatSV | FormatDSV | ({ type: "topojson"; property?: string | undefined; } & { ...; }) | ({ ...; } & { ...; }) | { ...; } | SignalRef | undefined; transform?: Transform[] | undefined; }'.
        Type '{ name: string; source: string; transform: { type: "contour"; x: { expr: string; }; y: { expr: string; }; size: { signal: string; }[]; count: { signal: string; }; }[]; }' is not assignable to type '{ url: string | SignalRef; }'.
          Property 'url' is missing in type '{ name: string; source: string; transform: { type: "contour"; x: { expr: string; }; y: { expr: string; }; size: { signal: string; }[]; count: { signal: string; }; }[]; }'.
```

**Comment by weswigham** [comment]
@domoritz is it fixed in the latest nightlies?

**Comment by domoritz** [comment]
Not yet: https://travis-ci.org/vega/vega-typings/jobs/445364587

**Comment by mattmccutchen** [comment]
Minimal example:
```ts
type Transform =
  ({ type: "contour"; size: [string]; } & ({ a?: number } | { b?: number }))
  | { type: "tree"; [k: string]: any; };

const transform: Transform = {
  type: 'contour',
  size: ['width'],
};
```

**Comment by domoritz** [comment]
I'm still seeing this issue in `TypeScript@next` but not in `3.1`.

**Comment by mattmccutchen** [comment]
Yes, it seems that this is a different bug from #27975.

**Comment by domoritz** [comment]
This is still a problem in the latest nightly.

**Comment by domoritz** [comment]
@weswigham @mattmccutchen Any updates on this? Is this a bug or should I change my code?

**Comment by domoritz** [comment]
@weswigham What does the "Needs investigation" label mean?

**Comment by weswigham** [comment]
In this case it just means that we need to investigate from the beginning to see what's causing the problem - for most bugs it's evident from the behavior, but I'm unsure here.

**Comment by RyanCavanaugh** [comment]
I don't know what this is getting at. Please log a new issue with a self-contained repro if something is needed. Thanks!
