### ISSUE TITLE
When implements interface in typescript adds import before element

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#28165]
_From @inferius on October 11, 2018 8:6_

 

Hi, implements interface in typescript auto adds import with absolute path before element of class.

- VSCode Version: 1.28.0
- OS Version: Windows 10

Steps to Reproduce:
![ezgif-1-cab6cff57ba4](https://user-images.githubusercontent.com/7590016/46789397-99fc9800-cd3c-11e8-9b20-f0271207a971.gif)

Does this issue occur when all extensions are disabled?: Yes

_Copied from original issue: Microsoft/vscode#60606_

**Comment by mjbvz** [comment]
Please try upgrading your workspace to use `typescript@next` by following [these instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions). Do you still see this error after upgrading?

**Comment by mjbvz** [comment]
Thanks for testing. Can you please share your tsconfig and a basic description of your project structure

**Comment by mjbvz** [comment]
_From @DanTup on October 23, 2018 9:3_

@mjbvz I see this too. I've pushed a branch with a repro here:

https://github.com/Dart-Code/Dart-Code/tree/vscode-60606-repro

Clone the `vscode-60606-repro` branch, open `src/pub/pub_task_provider.ts` and then use the quick-fix to implement the interface. I changed it to `typescript@latest` and see the same issue.

<img width="564" alt="screen shot 2018-10-23 at 9 57 51 am" src="https://user-images.githubusercontent.com/1078012/47349141-db7d3380-d6aa-11e8-8739-bde7cc05df9f.png">
<img width="1155" alt="screen shot 2018-10-23 at 9 57 56 am" src="https://user-images.githubusercontent.com/1078012/47349142-db7d3380-d6aa-11e8-81bc-36d74bd481de.png">
<img width="235" alt="screen shot 2018-10-23 at 10 03 01 am" src="https://user-images.githubusercontent.com/1078012/47349144-db7d3380-d6aa-11e8-9d7e-60eeed844f70.png">

(using `* as vs` in the import correctly puts `vs.` prefixes instead of import calls).

**Comment by MeirionHughes** [comment]
Any update on this? just seems to have been kicked into the long grass.

**Comment by weswigham** [comment]
We'd probably take PRs to fix it ❤️

**Comment by mjbates7** [comment]
Still occurring - running insiders 1.38.0 build. Any updates or thoughts? It's generating code like this: (angular)

![image](https://user-images.githubusercontent.com/4522738/63550829-64fbcd00-c52b-11e9-8770-c5ab4b27d3d5.png)

**Comment by weswigham** [comment]
That code is technically equivalent to the version where an import statement is used, just not as pretty - hence why this hasn't been the highest priority for us, and why I said we'd take a PR to fix it~ ❤️

**Comment by keotl** [comment]
I opened a PR which forces private aliases for implemented interface types. However, pointers would be appreciated for adding automatic importation. 

![giphy](https://user-images.githubusercontent.com/25084248/63899028-500ab800-c9c9-11e9-9379-cf9c8999180a.gif)

**Comment by weswigham** [comment]
You'd want to query for the same type nodes that we do today (complete with import types), but then traverse the node tree looking for instances of `ImportTypeNode`s, and transform them into a normal type reference by replacing the `import(...)` part with a generated name, and then adding an `import * as generatedName from "..."` statement. Then you can get smarter, like using named imports rather than namespace, and merging with existing import statements where possible.

**Comment by keotl** [comment]
I pushed a new version with automatic imports.
![giphy](https://user-images.githubusercontent.com/25084248/64013819-aa516900-caee-11e9-80a3-bb85b685bf09.gif)
This would be ready for review/testing.

**Comment by JulianLang** [comment]
So, what's the status here?

**Comment by avol-io** [comment]
any news?

**Comment by andrewbranch** [comment]
This was fixed by #36615 which is included in TypeScript 3.8.

Unfortunately, #34995, the issue I was assigned, was never marked as a duplicate of this one, and so I was never aware of the existence of this issue or the great work by @keotl at #33126. Sadly this happens from time to time in a repo with thousands of issues, but my apologies for the mixup nonetheless, particularly to @keotl.
