### ISSUE TITLE
Javascript error which isn't one: 'type arguments' can only be used in a .ts file

### ISSUE THREAD

**Issue by masbaehr** [microsoft/TypeScript#29235]
- VSCode Version: 1.31-insider 
- OS Version: Windows 10 Pro

![image](https://user-images.githubusercontent.com/38694044/50550137-76c1f480-0c6a-11e9-88ec-295b82619374.png)

**Comment by mjbvz** [comment]
confirmed using typescript@3.3.0-dev.20190101

The pattern that causes issues is:

```
if((0)<0>(0)){ }
```

**Comment by fatcerberus** [comment]
Hmm, it appears to think the stuff inside `<>` is a type argument, in this case it’s `<(n|0)|(e|0)>` which I guess the compiler thinks is a type union...

My instinct is that the error message should probably be removed entirely and the compiler just treat it as a normal `<` or `>` operator when inside a `.js` file.

**Comment by DanielRosenwasser** [comment]
Basic idea is that when the file is a JS/JSX file, don't try to parse type arguments for

- call expressions
- new expressions
- tagged template strings
- JSX
- decorators (I don't even think we currently do at all)

**Comment by sheetalkamat** [comment]
@DanielRosenwasser I don't think not parsing type arguments is correct fix. We do that so we can report better errors.
The above example in typescript file is an error too?
```
a.ts:1:4 - error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'Number' has no compatible call signatures.

1 if((0)<0>(0)){ }
     ~~~~~~~~~


Found 1 error.
```

**Comment by DanielRosenwasser** [comment]
It's a type error in TypeScript, but it would've parsed as different but syntactically valid JavaScript. In this case, that code is generated my another program, so saying "that's not valid JS" is weird.

**Comment by weswigham** [comment]
No, like, the issue moreso that we shouldn't be interpreting that pattern as type arguments in any language variant, ideally.

**Comment by weswigham** [comment]
We could trim back the scope of what we parse as type arguments, however - while `x<y>(z)` is reasonably a call with type arguments, `(x)<y>(z)` is... less so, IMO.

**Comment by weswigham** [comment]
For anyone interested and reading this issue, `parseCallExpressionRest` in `parser.ts` is where we handle this.

**Comment by fatcerberus** [comment]
What I was getting at was there's no guarantee that a minifier won't produce code that looks exactly like `x<y>(z)`.  Even in the code sample in the OP you can see it comes dangerously close to doing so--the parentheses are only present because it does `x|0` which binds more loosely than greater than/less than.  Variables in general aren't parenthesized.

**Comment by fatcerberus** [comment]
That being said, I agree it would be nice to keep the error for the benefit of people trying to write TS code in a `.js` file; I'm just not sure if that's practical.

**Comment by Kingwl** [comment]
I have a (work in progress) tried on my branch https://github.com/Kingwl/TypeScript/commit/9143748fdfe787be63629d80a51ca3e977070768  but I'm not sure that is expected

**Comment by Dalzhim** [comment]
I have the same kind of problem and I've been searching for hours for a workaround that I could use without any success. I am using Emscripten to compile some C++ code into JavaScript. It produces a JavaScript file. I have to import the generated *.js file from within a *.tsx file in order to leverage the exposed functions.

I have tried using the `// @ts-ignore` both before the `import` and before the line where the error is reported. I have tried using the `// @ts-nocheck` comment at the beginning of the generated file. There doesn't seem to be any way to silence this false positive.

**Comment by DanielRosenwasser** [comment]
I think this is fixed by https://github.com/microsoft/TypeScript/pull/36673, right?

**Comment by Dalzhim** [comment]
I am not sure whether or not I did the test correctly. I have modified my `package.json` file entry to : `"typescript": "microsoft/TypeScript#f308ac136d420a71819616207a0358b8d369a9cc"` and ran `npm install` afterwards. After doing that, the error remains when I compile my project.

```TS8011: Type arguments can only be used in TypeScript files.
TS1139: Type parameter declaration expected.```

**Comment by Dalzhim** [comment]
I have successfully cloned mprobst/TypeScript:parse-js and built the package. It seems to crash with the following error :

```
ERROR in ./src/client/app/index.js
Module build failed (from ./node_modules/ts-loader/index.js):
Error: Debug Failure. Unexpected node.
Node ComputedPropertyName was unexpected.
    at bindThisPropertyAssignment (/TypeScript/lib/typescript.js:32648:30)
    at bindWorker (/TypeScript/lib/typescript.js:32280:29)
    at bind (/TypeScript/lib/typescript.js:32160:13)
    at visitNode (/TypeScript/lib/typescript.js:18468:24)
    at Object.forEachChild (/TypeScript/lib/typescript.js:18884:21)
    at bindEachChild (/TypeScript/lib/typescript.js:30688:16)
    at bindChildrenWorker (/TypeScript/lib/typescript.js:30783:21)
    at bindChildren (/TypeScript/lib/typescript.js:30658:17)
    at bind (/TypeScript/lib/typescript.js:32171:21)
    at bindEach (/TypeScript/lib/typescript.js:30680:21)
    at visitNodes (/TypeScript/lib/typescript.js:18473:24)
    at Object.forEachChild (/TypeScript/lib/typescript.js:18864:21)
    at bindEachChild (/TypeScript/lib/typescript.js:30688:16)
    at bindChildrenWorker (/TypeScript/lib/typescript.js:30783:21)
    at bindChildren (/TypeScript/lib/typescript.js:30658:17)
    at bind (/TypeScript/lib/typescript.js:32171:21)
    at visitNode (/TypeScript/lib/typescript.js:18468:24)
    at Object.forEachChild (/TypeScript/lib/typescript.js:18850:24)
    at bindEachChild (/TypeScript/lib/typescript.js:30688:16)
    at bindChildrenWorker (/TypeScript/lib/typescript.js:30783:21)
    at bindChildren (/TypeScript/lib/typescript.js:30658:17)
    at bind (/TypeScript/lib/typescript.js:32171:21)
    at visitNode (/TypeScript/lib/typescript.js:18468:24)
    at Object.forEachChild (/TypeScript/lib/typescript.js:18538:21)
    at bindEachChild (/TypeScript/lib/typescript.js:30688:16)
    at bindChildrenWorker (/TypeScript/lib/typescript.js:30783:21)
    at bindChildren (/TypeScript/lib/typescript.js:30658:17)
    at bind (/TypeScript/lib/typescript.js:32171:21)
    at bindEach (/TypeScript/lib/typescript.js:30680:21)
    at visitNodes (/TypeScript/lib/typescript.js:18473:24)
    at Object.forEachChild (/TypeScript/lib/typescript.js:18783:21)
    at bindEachChild (/TypeScript/lib/typescript.js:30688:16)
    at bindChildrenWorker (/TypeScript/lib/typescript.js:30783:21)
    at bindChildren (/TypeScript/lib/typescript.js:30658:17)
    at bindContainer (/TypeScript/lib/typescript.js:30639:17)
    at bind (/TypeScript/lib/typescript.js:32174:21)
    at /TypeScript/lib/typescript.js:30664:94
    at bindEach (/TypeScript/lib/typescript.js:30680:21)
    at bindEachFunctionsFirst (/TypeScript/lib/typescript.js:30664:13)
    at bindChildrenWorker (/TypeScript/lib/typescript.js:30774:21)
    at bindChildren (/TypeScript/lib/typescript.js:30658:17)
    at bindContainer (/TypeScript/lib/typescript.js:30604:17)
 @ multi @babel/polyfill ./src/index.js bundle[1]
```

**Comment by IvanRomanovski** [comment]
Any updates on this?

**Comment by jakebailey** [comment]
This is an old issue, but this was definitely fixed by #36673 in TS 4.2.
