### ISSUE TITLE
The future of the "private" keyword

### ISSUE THREAD

**Issue by G-Rath** [microsoft/TypeScript#31670]
This is a somewhat "catch-all" issue to serve as a place of discussion for [a question that is sure to come up](https://github.com/microsoft/TypeScript/pull/30829#issuecomment-497237013) given the [advancement](https://github.com/microsoft/TypeScript/issues/9950) of [Private-Named Instance Fields](https://github.com/microsoft/TypeScript/pull/30829): 

----
### What is the future of the "private" keyword in TypeScript?

That's the general question - following are some short-and-sweet Q&As that I've pulled up for visibility.

#### Is TypeScript going to depreciate it, and aim towards phasing it out in favor of the private field operator?

> [Our current plan is to leave the current private behavior as-is.](https://github.com/microsoft/TypeScript/issues/31670#issuecomment-497370201)

#### Is it going to be supported in the form of a transformer , turning `private bar` into `#bar`?

> [definitely "no" because that would require type-directed emit.](https://github.com/microsoft/TypeScript/issues/31670#issuecomment-497370557)

#### Would #-fields allow modifiers like readonly?

> [Yes, readonly is meaningful inside the class](https://github.com/microsoft/TypeScript/issues/31670#issuecomment-497767555)

#### Will public #x, private #x and protected #x be an error?

> [Yes](https://github.com/microsoft/TypeScript/issues/31670#issuecomment-497767555)

#### Will it be possible to assign #-fields from the constructor parameters, the same way as the current parameter-properties work (i.e., constructor (private x) and constructor (#x))?

> [No](https://github.com/microsoft/TypeScript/issues/31670#issuecomment-497767555)

#### What visibility rules will apply between private entities and #-entities? What if I use a private-entity from a #-entity, or vice versa? Seems that #-entites are 'more' private than private-entities, in some sense. :)

> [The visibility of a method doesn't change which properties it's allowed to access](https://github.com/microsoft/TypeScript/issues/31670#issuecomment-497767555)

#### Would it be possible to [do the following](https://github.com/microsoft/TypeScript/issues/31670#issuecomment-497723569):
```
class Foo {
    bar: string;
    #baz: number;
}
const foo: Foo = { bar: 'bar' };
```

> [No. The given object is not a substitute for Foo; the same reasoning about cross-member access requiring private members to be present applies here](https://github.com/microsoft/TypeScript/issues/31670#issuecomment-497767555)

**Comment by AnyhowStep** [comment]
I would personally prefer to keep the `private` keyword. To me, it looks way<sup>way<sup>way</sup></sup> better than `#`. And is more clear in its intent, to me. And I wouldn't want to have to go back and do a regex replace for `private` to `#`.

**Comment by RyanCavanaugh** [comment]
Our current plan is to leave the current `private` behavior as-is.

Reasons for this:
 * We don't make breaking changes for no reason, and nothing external is forcing people to move off of compile-time `private`
 * There are legitimate use cases for compile-only privacy, e.g. `private` fields can be read from unit tests (I realize some people find this personally distasteful, but this is not universal)
 * Lots of people don't like the `#` syntax so why force it on them
 * Without `WeakMap` (which not all runtimes have) there's no good equivalent downleveling for hard runtime privacy

As for a transformer, probably not? It's simple to replace these with a regex if you're motivated.

**Comment by RyanCavanaugh** [comment]
Oh the other interpretation of "transformer" would be "Would TS emit `private` as `#`", the answer to which is definitely "no" because that would require type-directed emit.

**Comment by fatcerberus** [comment]
FWIW I don’t find the type-directed emit argument that strong in this case; it’s a stretch to call `private` “type info” IMO (also we’re emitting the *class itself*, so we could just say it’s an alias for `#` and thus not really type info at all).  That said, changing TS to emit private members as `#` would be a massive, **massive** breaking change (at runtime too!), so that’s plenty good reason to avoid going that route as far as I’m concerned.

> way<sup>way<sup>way</sup></sup>

I found this way funnier than I should have, I think.

**Comment by fatcerberus** [comment]
> When I found out # was being proposed instead of just private, I thought I was experiencing the Mandela effect.

On a related note, it’s good to know I’m not the only person who thought I had been dropped into Bizarro World when I first found out about the `#` sigil.

**Comment by RyanCavanaugh** [comment]
> FWIW I don’t find the type-directed emit argument that strong in this case; it’s a stretch to call private “type info” IMO (also we’re emitting the class itself, so we could just say it’s an alias for # and thus not really type info at all).

Remember that private fields allow cross-instance access. Consider something like this:

```ts
class A {
  private y = 0;

  method(arg: A) {
    console.log(arg.y);
  }
}
```
The "correct" `#`-based emit of this would require type information on `arg` in order to detect that `y` should be rewritten to `#y`

**Comment by fatcerberus** [comment]
Yeah, I see what you mean now, basically `obj.foo` is ambiguous without type info if there’s a possibility it can “really mean” `obj.#foo`.  Thanks, hadn’t thought of the cross-instance case.

**Comment by mheiber** [comment]
Other sometimes-advantages of OG `private` is that `private` fields show up in `JSON.stingify` output and can show up in `console.log`.

**Comment by gsathya** [comment]
Hi I was pointed to this thread by folks regarding the runtime performance concerns mentioned in https://github.com/microsoft/TypeScript/issues/31670#issuecomment-497370201. (For some background, I implemented private fields in V8)

> private fields have much better runtime perf, especially in downlevel scenarios

Can you expand on this? My understanding is that typescript private is downleved to public property access. AFAIK, the extra overhead for ES private is just one machine load for loading the `PrivateName` backing the property when compared to public property access. I don't expect this to be of significant runtime overhead. Is there something else?

**Comment by zhuravlikjb** [comment]
A few more questions that weren't asked yet (it seems):
1. Would #-fields allow modifiers like `readonly`?
2. Will `public #x`, `private #x` and `protected #x` be an error?
3. Will it be possible to assign #-fields from the constructor parameters, the same way as the current parameter-properties work (i.e., `constructor (private x)` and `constructor (#x)`)?
4. What visibility rules will apply between `private` entities and `#`-entities? What if I use a private-entity from a #-entity, or vise versa? Seems that #-entites are 'more' private than private-entities, in some sense. :)
Thanks.

**Comment by nicojs** [comment]
5. Would it be possible to do this?
```ts
class Foo {
    bar: string;
    #baz: number;
}
const foo: Foo = { bar: 'bar' };
```
 or is `#baz` part of the shape of `Foo`? (hope not).

**Comment by RyanCavanaugh** [comment]
> AFAIK, the extra overhead for ES private is just one machine load for loading the PrivateName backing the property when compared to public property access. I don't expect this to be of significant runtime overhead. Is there something else?

I over-extrapolated; I'll trust your assessment on this. I've updated the comment to be more accurate.

**Comment by RyanCavanaugh** [comment]
> Would #-fields allow modifiers like readonly?

Yes, `readonly` is meaningful inside the class

> Will public #x, private #x and protected #x be an error?

Yes

> Will it be possible to assign #-fields from the constructor parameters, the same way as the current parameter-properties work (i.e., constructor (private x) and constructor (#x))?

No

> What visibility rules will apply between private entities and #-entities? What if I use a private-entity from a #-entity, or vice versa? Seems that #-entites are 'more' private than private-entities, in some sense. :)

The visibility of a method doesn't change which properties it's allowed to access

> Would it be possible to do this? (structurally skip a # member)

No. The given object is not a substitute for `Foo`; the same reasoning about cross-member access requiring `private` members to be present applies here

**Comment by fatcerberus** [comment]
> The given object is not a substitute for Foo; the same reasoning about cross-member access requiring private members to be present applies here

I’m not sure I understand the rationale of this; for TS-private this makes sense because of JS interop (the “private” property is actually public from JS POV); for `#` fields, only the class itself can access it, even at runtime, and therefore as long as the rest of the shape matches, it should be fine from a duck-typing POV.

Is there a case I’m missing where the above substitution wouldn’t be safe?

**Comment by ljharb** [comment]
Private fields seem like they’d require a nominal, not structural, type, since they’re like a brand.

**Comment by RyanCavanaugh** [comment]
`private ` fields already create a nominal brand; `#` fields will too

**Comment by RyanCavanaugh** [comment]
Just to spell it out:
```ts
class Foo {
    bar: string = '';
    #baz: number = 0;
    check(other: Foo) {
        console.log(other.#baz);
    }
}
const foo: Foo = { bar: 'bar', check: (other: Foo) => undefined };
const realFoo = new Foo();
// Runtime error
realFoo.check(other);
```

**Comment by trusktr** [comment]
That shouldn't be allowed, right?

**Comment by fatcerberus** [comment]
No, that’s totally normal in most OO languages in my experience - a class can freely access private members of other instances of itself.  Same goes for the proposed `#` class field syntax.

**Comment by hax** [comment]
> As for a transformer, probably not? It's simple to replace these with a regex if you're motivated.

@RyanCavanaugh Though it seems easy to replace TS `private _foo` to `#foo` or vice versa, it actually have many semantic differences and very likely cause many bugs/breaking changes in the whole ecosystem. I suggest TS would give caveat to warn the programmers when land private fields: it will be very dangerous to change `private _foo` to `#foo` naively in current code base.

---

Then some thought about `private` and `#`:

I understand why TS team decide to support both `private foo` and `#foo`, but to be honest, it will cause more and more problems in *long term* to have two different private mechanism. Every newcomers will wonder which one I should use, every team need to decide which one should we adopt...

There would at least three options: 
1. only use TS private
2. only use #foo
3. use both

When some programmers/teams with difference preference work together there would be arguments, again and again.

Note, TS private and `#foo` have differences, there may be some use cases which is only possible or much better in one mechanism, but in most use cases, from the engineering viewpoint, there is no much difference. So the benefits of two mechanism never meet their cost.

Such arguments would be a bit like the holy war of Tab vs Space, both side have valid reasons but in the engineering viewpoint they are trivial. Unfortunately, not like tab/space which can be converted seamlessly, `private foo` and `#foo` can not be converted easily as my explanation before. This means the decision would never be trivial.

I hope TS team could have a long-term view about this issue. We should not force the programmers and the whole ecosystem to take the cost of two mechanism.

I understand the current situation is largely caused by TC39. The design of TypeScript, as the downstream of the design of ECMAScript, is forced to face such dilemma (not only private field, but also potential big breaking changes due to public fields). As class fields proposal already stage 3, it's very impossible to ask TC39 guys to revisit the issues. But I always think it's wrong to transfer the ten people cost of committee to millions people cost of the whole community.

**Comment by rjgotten** [comment]
> We should not force the programmers and the whole ecosystem to take the cost of two mechanism.

As long as Microsoft's own tooling uses TypeScript-based language services also for regular JS, you don't really have the luxury of only supporting one.

If you want to settle on using only one, then the best case scenario is to support only one _at a time_. That is: `private foo` only in `.ts` files and `#foo` only in `.js` files.

Anything else is either going to piss off TS developers or JS developers.

**Comment by jimbuck** [comment]
I love the fact that TypeScript's `private` can still be accessed for situations like unit testing. For internal classes I have no reason to use the JS `#` sigil. On the other hand, for externally accessible classes I see where the `#` sigil provides value, by protecting users of your library from accessing internal fields.

So as annoying as it may seem, I'm glad it does not conflict with existing TypeScript syntax. I believe that TypeScript should continue to maintain "soft private" via `private x` and "hard private" via JS's `#x`.

**Comment by ljharb** [comment]
Private things aren’t supposed to be tested; you can use symbols for “soft private”.

**Comment by jimbuck** [comment]
@ljharb To be more clear, I don't mean directly testing private "things", I'm talking about unit testing public things (methods). There is a huge benefit in having access to `private` fields, it allows for easy mocking and assertions. Using Symbols can provide a similar experience, but I'd rather not have to change paradigms just to maintain functionality supported by the language since the very beginning.

**Comment by AnyhowStep** [comment]
Symbols created with `Symbol()` start to break when you have multiple copies of the same dependencies at different versions. Copy #1's `const privateField = Symbol()` is different from Copy #2's `const privateField = Symbol()`

The same when using `instanceof` tests on classes where you have multiple copies of the same package. Copy #1's `class A` is different from copy #2's `class A`.

**Comment by ljharb** [comment]
@AnyhowStep yes, it will - different instances will have different private fields, just like as if a closed-over WeakMap was being used.

**Comment by fatcerberus** [comment]
That kind of thing is exactly why `Array.isArray` was invented, IIRC.

**Comment by mbrowne** [comment]
Has there been any discussion about a compiler option that would let the user choose how TypeScript's `private` should be transpiled? I'm sure some people are fine with only compile-time private, whereas others might want hard private (via `#`, transpiled to WeakMaps in the meantime) or soft private (via symbols). Given that `private` is already baked into TypeScript, IMO it might as well do something useful and not be so easily circumvented at run-time. OTOH, I can see the argument for treating `private` as a legacy feature and always having it be a compile-time only feature, since we will have `#` also...

**Comment by mbrowne** [comment]
One correction/clarification: I am aware that TypeScript will support private fields (`#`), so personally I would not want to instruct the compiler to transpile `private` to `#`. Seems much less confusing and error-prone to just use `#` directly. But I tried to include what others might want in my above assessment. The option to transpile `private` to symbols is my main suggestion.

**Comment by RyanCavanaugh** [comment]
@mbrowne We don't have any plans to provide that as a compile step. You can already write your code that way with good typechecking via `unique symbol` if that's what you'd like to happen at runtime. The presence of `#` doesn't really change anything either way there.

**Comment by mbrowne** [comment]
The `private` modifier is a significantly more concise way to define properties than declaring symbols manually. And while I get your point that `#` doesn't change anything technically, I think the introduction of `#` presents an opportunity to create an _option_ for `private` to do something else, since ideally people will start using `#` for fields that should truly be private and `private` would just become a largely unused legacy feature.

However, my suggestion could easily be implemented as a 3rd party Babel plugin instead. It also depends on whether or not TC39 will pursue some other shorthand syntax for symbols, in which case it would make more sense to support that proposal (if someone created it) rather than working on a way for `private` to transpile to symbols.

**Comment by rjgotten** [comment]
> Symbols created with `Symbol()` start to break when you have multiple copies of the same dependencies at different versions. Copy # 1's `const privateField = Symbol()` is different from Copy # 2's `const privateField = Symbol()`

@AnyhowStep 
And that's why `Symbol.for` and `Symbol.keyFor` exist.
If you have pseudo-private members that you need to be able to access across boundaries, they're what you use.

Sure, that's not _really_ private anymore: but then, even the anonymous `Symbol()` never had guarantees of being private, because you could always access symbols using `Object.getOwnPropertySymbols` anyway. Quite analogous to how reflection facilities in languages such as C# also still allow you to pull up private class members.

>yes, it will - different instances will have different private fields.

@ljharb 
[No, it won't](https://github.com/tc39/proposal-class-fields/blob/master/PRIVATE_SYNTAX_FAQ.md#why-does-this-proposal-allow-accessing-private-fields-of-other-instances-of-the-same-class-dont-other-languages-normally-forbid-that). Different _classes_ will have different private fields. Different _instances_ of the _same_ class will have shared access to private fields of that class.

**Comment by jimbuck** [comment]
@rjgotten I think @ljharb means multiple instances of the same module (dependencies of dependencies, different versions, etc.). They won't be considered the same class, therefore you won't be able to access them between versions. Theoretically.

**Comment by rjgotten** [comment]
@jimbuck 
I suppose that's possible. It's a bit of a wash what was meant by 'instance' then.
(Bit of a loaded term in the context of classes.)

**Comment by ljharb** [comment]
@rjgotten the question was about different classes, but your clarification is correct.

**Comment by jimbuck** [comment]
@rjgotten Definitely a loaded term, maybe "module instance" is better. But I think the situation that @AnyhowStep describes is definitely possible, has there been any deeper discussion on that?

**Comment by RyanCavanaugh** [comment]
>  But I think the situation that @AnyhowStep describes is definitely possible, has there been any deeper discussion on that?

It's a feature, not a bug (seriously)

**Comment by jimbuck** [comment]
@RyanCavanaugh Hey, as long as there is awareness that different module instances (two versions of the same module) means separate classes and therefore no private access. Module resolution/version alignment will be far more important once `#` is actively used.

**Comment by matthewjh** [comment]
@RyanCavanaugh 

> > Will it be possible to assign #-fields from the constructor parameters, the same way as the current parameter-properties work (i.e., constructor (private x) and constructor (#x))?
> 
> No

Ryan, I kindly ask you to reconsider this. A lot of codebases have a significant number of classes making heavy use of `private` but also the constructor assignment shorthand. If those developers want to migrate over to hard-private fields, they will not be able to do so with a simple regex: a regex would easily cover `private x: string` but not the constructor assignment. I understand retaining both soft- and hard-privates, but it has to be easy to transition soft- to hard-privates, as you alluded to earlier re. using a regex. But with the above it's not going to be easy or possible with a simple regex at all. Frankly, this is going to be a royal pain to migrate to if constructor assignment shorthand isn't extended to support hard-privates. In code that uses constructor dependency injection, for example, this shorthand is used in a majority of classes and the reality is that the decision above is going to prevent migration and cause frustration and confusion. 

Also, I think it adds further incongruity. So TypeScript has this shorthand to create fields, and it can be used for `public`, `protected`, and `private` fields, but not for hard-private? That's not consistent. I understand the rationale behind not deviating from the ES specced syntax, but TypeScript already has the constructor shorthand whether people like it or not. It is already being used, whether people like it or not. Not extending this existing feature to a new type of field, given that it works for every other type of field, would be a big mistake, in my opinion, and make the language less intuitive.

**Comment by robpalme** [comment]
Thanks for highlighting the lack of [parameter properties](https://www.typescriptlang.org/docs/handbook/classes.html#parameter-properties) for `#private` names, @matthewjh.

> it has to be easy to transition soft- to hard-privates

On this specific point, it's worth noting that in the general case, migrating a codebase from soft-private to hard-private is unsafe, so any automated conversion would be hazardous.  This is because client code might be depending on those properties in all sorts of ways, e.g. for-in iteration, proxies, intentional access that casts away type safety, JS code that didn't realize there was any type safety to begin with... and more ways.  The cat is already out of the bag.  So my personal expectation is that hard-private will be used more for fresh code rather than refactoring existing code.

**Comment by matthewjh** [comment]
Thank you @robpalme. I'm not sure I agree with your expectation. In our codebase, which all-TS and quite tightly controlled, there are no "unsafe" accesses of soft-private properties. We used soft-privates not because we _want_ soft privacy but because it was the only option at the time.  We will certainly move to hard privates once they are available. 

In my view having a codebase where hard-privates are used for new classes and soft-privates for existing classes, i.e. an inconsistent mixture of the two based on creation date, rather than on intent and semantics, is something few developers would be happy with... I think more people will want to migrate than you think -- but that is just my opinion.

**Comment by kokushkin** [comment]
Honestly, I don't like # fields. But what I don't like even more is living with two private fields: private and #. If TypeScript is a superset of Javascript then "private" must be deprecated and deleted from the language in the 4th version. All these benefits which were mentioned above don't worth keeping two private fields. It's too confusing for people who use the language. The people for whom language was really created for. The majority of them. The language is not for creators of the language only!

**Comment by mbrowne** [comment]
@kokushkin I agree with the principle of what you're saying about making the language more user-friendly. If the old `private` fields truly became a legacy feature, they could be deprecated with a warning and then later on made available only via a special flag, if at all. But that's assuming that they're no longer needed, when in reality I think properties that are private only at compile time is a feature a lot of people would want to keep...so there would have to be a new syntax to declare such fields. And if the syntax for that still used `#`, it might still be confusing since `#foo` by itself indicates a field `foo` that's fully private at run-time.

There has been some discussion in the past at https://github.com/tc39/proposal-class-fields and https://github.com/tc39/proposal-decorators about using decorators to enable "soft private", i.e. fields that can still be accessed somehow outside the class (for the purpose of reflection, etc.). For example, there could be a `reflect` or `expose` decorator:

```js
class Demo {
  @reflect
  foo = 1
}
```

The idea is that the field would still be "private" in the sense that you couldn't access it directly, but it would still be available via some other reflection method, e.g. `Object.getOwnPropertySymbols()` or maybe a new API. (If it used symbols, then alternatively the decorator could just be called `@symbol`.)

I think this is something that the decorators proposal needs to figure out, and then we can figure out what hard private / soft private features make the most sense for TypeScript in the future.

**Comment by kokushkin** [comment]
Thank you, @mbrowne . It seems to be reasonable using decorators for these types of things. At the same time the more people see these two private definitions the more people will be confused. And they are already on the "classes" page of the Handbook! When I think they should be somewhere in a "deep dive" or smth until everything will be ready to make them primary. But before that, just think about how it would look like to having all this together with private and public methods of classes. Doesn't it seem to be awkward?
![image](https://user-images.githubusercontent.com/9853656/73119387-c1936600-3f69-11ea-811c-6eb257329db1.png)
I mean using # for private fields and "private" for private methods together!

**Comment by kokushkin** [comment]
I think I've got a little bit more holistic point of view by now. My statement is... if you want to keep your language as a superset of another language and at the same time keep it consistent - **you have to make more breaking changes**. **Because**, often, **the underlying language changes in a way  which not consistent with superstructures** of the superset language. Here are possible ways...

![Untitled](https://user-images.githubusercontent.com/9853656/73126776-55435180-3fbf-11ea-8231-27bbed86a7f9.png)
As for me, I would prefer the way II. And if we go the way number I, it would be great to keep the patch away from people's eyes.

**Comment by mbrowne** [comment]
There is an ECMAScript proposal for private methods that's already in stage 3:
https://github.com/tc39/proposal-private-methods#private-methods-and-fields

I don't know what is the status of implementing this in TS, but I assume it will happen, at which point it will be possible to use `#` for both private fields and methods.

**Comment by hax** [comment]
There will be lot of pains when use `#` and `private` together, this is one of the important reason why we 360 tech group as ECMA member already make the decision of vote for NO on class fields proposal in future meetings if the champions want to advance class fields to stage 4. Unfortunately, class fields proposal already achieve stage 3 several years ago before we join ECMA and TC39. And   implementers (include TypeScript) have their own decisions to implement any stage 3 proposals. We will see the consequences soon.

**Comment by mbrowne** [comment]
Thanks for the update @hax. I am glad that you and the 360 tech group are joining the TC39 committee and adding to the diversity of opinion there. But it sounds like you are also introducing bias if you have already made a decision to vote against advancing class fields to stage 4. This decision should be based in large part on feedback from people who have actually used private fields in production (and consuming libraries that use them). I don't think there's been enough of a data collection period yet to definitively conclude that rolling back class fields is justified. Unless there is real-world data showing that the new syntax is so confusing to people that it harms productivity and adoption, then it's premature to conclude that.

And aside from which issues are anticipated and which issues actually become significant among real-world users, all of this has to be weighed against alternative proposals and tradeoffs—for example, the fact that `private foo` syntax would make it impossible to achieve true run-time privacy (i.e. hard privacy). The point I was making about TypeScript is that they are merely following the proposed standard, and rejecting the standard to go in their own direction would have negative consequences. Of course the other side of the argument is that implementing private fields in TS was premature, which I disagree with even in the very unlikely event that the class fields proposal is dropped.

**Comment by RyanCavanaugh** [comment]
I think people are overthinking this. Every programming language has multiple ways of accomplishing the same endgoal with different trade-offs, even down to trivia like how you write the property keys in object literals (single quotes? double quotes? no quotes? computed string name?). `#` has its own problems and benefits, and `private` has its own problems and benefits. This is a boon, not a burden.

If you want to *work hard* to try to confuse yourself, sure, mix `#` and `private` in the same class. But if your goal was to write confusing code, there are much better options available to you already, and I don't think this helps you much.

If you don't want to actively sabotage your own codebase, pick one or the other, both will probably be fine in your application, and you can do some light reading ahead of time if you want to understand the difference.

**Comment by kokushkin** [comment]
What do you think, how many people will use it # feature in day to day practice? If the majority of them then it's not ready, because it's in dissonance with all other "private", "public", "protected". If it's only a very rare case, then please, put it somewhere away from regular "private", "public", "protected" in the handbook to prevent people's confusion.

**Comment by AnyhowStep** [comment]
My only gripe with `#` so far is that GitHub keeps thinking I'm trying to reference an issue, when I'm just trying to talk about private properties.

```ts
class Foo {
  #x //GitHub unhelpfully gives me an annoying dropdown
}
```

**Comment by hax** [comment]
@RyanCavanaugh 

> I think people are overthinking this. 

I think people are too optimistic in this topic ^_^ , the interesting part is the fans of TS normally in the other side, that's why they choose TS which can provide more protection than JS. Unfortunately the great success of TS also cause many ignorance of JS, many TS programmers just say: I don't care about JS any more, I just use TS! 

> Every programming language has multiple ways of accomplishing the same endgoal with different trade-offs, even down to trivia like how you write the property keys in object literals (single quotes? double quotes? no quotes? computed string name?). 

All these examples are just stylistic which I don't think comparable to this issue. Actually it's very dangerous that people think `#foo` vs `private foo` is just stylistic. In simple cases there is no much difference, but have subtle and significant consequences when interoperated with other code.

> `#` has its own problems and benefits, and `private` has its own problems and benefits. This is a boon, not a burden.

Understanding the difference of two incompatible private mechanism is definitely a burden. Especially `#priv` have many strangeness which rarely possible in traditional userland JS/TS classes. And such burden do not have enough benefit in most userland code.

> If you want to _work hard_ to try to confuse yourself, sure, mix `#` and `private` in the same class. 

I really hope TS documentation could add caveat for that.

> But if your goal was to write confusing code, there are much better options available to you already, and I don't think this helps you much.

The problem is , classes is very different than other language features, there is inheritance. Base classes and derived classes could in different packages. In many cases, you can't control the upstream and downstream of your classes. So there is no easy way to truly avoid mixing of `#` and `private`.

> If you don't want to actively sabotage your own codebase, pick one or the other, 

"Pick one" is easy to say but the cost of discussion/arguments/conflict/postmortem/refactoring of "pick one" will be paid by every team, every project, again and again. As I always say, we TC39 are transferring 100 people committee cost to 10,000,000 people community cost.

> both will probably be fine in your application, and you can do some light reading ahead of time if you want to understand the difference.

Actually it's very hard to understand all the consequence of `#priv`, programmers only be taught some buzz word like "true privacy" (sounds great!). For example the infamous proxy/membrane transparency issue, I bet there only 50% programmers could figure out proxy transparency issue in one hour, and 80% programmers would never figure out membrane at all. But they will face issues in a unfortunate day (for example, use instances with private fields and proxy-based libraries like MobX together). The worst part is you do not have any real solution of such issues except roll back your code from "true privacy" to "private" which is a not very "true" private. Who to blame? Most programmers would blame themselves. And some may blame TS: TS is not as good as I used to know... :-P

Anyway I am just the "people are overthinking this." 

But again, we will see what happened.

**Comment by hax** [comment]
> This decision should be based in large part on feedback from people who have actually used private fields in production (and consuming libraries that use them).

@mbrowne Unfortunately, when something is broadly used in production, it will be too late to remove it even it is heavily flawed. So it's meaningless to make "decision" that time.

Actually we are now in the way to such situation. 

And there is a logic problem that "feedback from people who have actually used private fields in production". We the frontend branch of tech committee of 360 tech group (consist of 10+ most experienced programmer, team leaders and architects of our group, most of them have 10+ years JS experience and at least half of them are heavy TS developers) already discussed the feature thoroughly, we have the conclusion that class fields have serious problems and we will never use it in our production code. Class fields is not a small feature, and several issues of them are interoperable issues with other code in complex context which will be very hard to track, we have no interest to take any risk to test it in our production code. But as your criteria, our opinion is not valid feedback because we didn't use it in production. The problem is if we already anticipate the worst result, why we want to use it in production?

**Comment by mbrowne** [comment]
@hax We could have a long discussion about process issues, but since this is the TypeScript repo, I'll just say that I do think the feedback of those who have investigated the feature but not used it in production is valuable (especially if they have investigated it deeply as you have done), but should definitely be considered together with feedback from usage in production. And we certainly saw some flaws in the current TC39 staging process with this feature that should be addressed in order to collect more real-world feedback (e.g. via Babel) before new features ship in browsers.

But I would ask TS users to keep JS users in mind here...JS users have wanted private state in their classes for a long time. The only other syntax I have seen that would allow for hard privacy at run-time (which I don't see as a requirement—I would be fine with soft run-time privacy—but many people do want it, including some TS users) is var/let/const syntax as in the classes 1.1 proposal and rdking's fork of that proposal. And personally, I think that TC39 is correct that that syntax is actually more confusing and problematic than the class fields (`#priv`) proposal. I wish more user testing had been done to verify this. But I think TypeScript's policy of implementing stage 3 ES proposals is a good policy—no one is forcing all users to immediately switch to the new syntax.

**Comment by franktopel** [comment]
> Then some thought about `private` and `#`:
> [...]
> There would at least three options:
> 
> 1. only use TS private
> 2. only use #foo
> 3. use both

You forgot the very probably option

4. use neither until the smoke clears, if ever

**Comment by spikyjt** [comment]
Like many here, I dislike the `#` syntax for private fields, but I dislike even more the (not very obvious) "compile-time only" nature of `private` in TS. It's one of many TS gotchas that has caught me out. In particular when working with JS libraries where you might expect `private` to behave in a logical manner, e.g. with Vue components which wraps all fields in accessors in order to manage state.

Since `#` fields are compiled to code that produces the same behaviour as a private field, when targeting es2019 and below (using `__classPrivateFieldSet` and `WeakMap`), surely the same could be done for fields marked `private`? Even if maintaining BC is a requirement, this could be optional with a suitable flag in tsconfig, for those of us who always expected `private` to actually be private and would prefer our future code to behave appropriately.

**Comment by bcis-kassel** [comment]
I don't get the point why it would be a breaking change to have a tsconfig flag "compilePrivateToHashtag" which is disabled by default. With the flag turned (by default) off the behaviour remains the same; no breaking change. But If you like to have hard privacy enabled by using the pirvate key word instead of the # syntax your are free to set the flag.

This solution would fit all needs:
People that want soft and hard privacy => flag off, using private and #
People that want soft privacy only => flag off, using private only
People that want hard privacy loving # syntax => flag on or off, using # only
People that want hard privacy loving private keyword => flag on, using private only

With optionally tslint enabled to prefer one syntax over the other.

**Comment by ljharb** [comment]
Why should anybody be given the ability to write new code that is nonstandard? The language has no private keyword and won’t have one; new code shouldn’t have one either.

**Comment by rjgotten** [comment]
> Why should anybody be given the ability to write new code that is nonstandard? The language has no private keyword and won’t have one; new code shouldn’t have one either.

_JavaScript_ has no access modifier keywords. But it doesn't have - e.g.  _type declarations_ either. That's why TypeScript is a superset.

There's no reason TypeScript shouldn't be allowed to map its `private` access modifier keyword onto `#`-methods moving forward; that's the discussion at hand here, afaict.

**Comment by nicojs** [comment]
It is a fair criticism to say: "you should use `#foo` rather than `private foo`", but it would be pretty opinionated and I feel like it's more in the realm of eslint plugins. There should be an eslint rule that forces you to use es privates, i.e. "prefer-es-private".

**Comment by ljharb** [comment]
There’s no value in using TS’s private keyword semantics when the #, alone, conveys “private”, in a standard way.

**Comment by RyanCavanaugh** [comment]
We're not going to add a flag for this. `#` means runtime private, `private` means compile-time private. There's nothing gained but confusion by adding a flag to conflate the two.

I know some people have aesthetic aversion to `#`, but I will use my "Ryan only gets to say this once a year" token here: *get over it*. JS syntax is JS syntax and TS isn't here to add literal pure sugar at the expense of comprehensibility.

**Comment by mbrowne** [comment]
It could still be nice to have an option to make `private` compile to some sort of _soft_ run-time privacy though. (So not `#`, but maybe symbols...)

**Comment by xhermosilla** [comment]
Is it planned in the future to transpile directly to #variable / #method instead of using a WeakMap

**Comment by owenallenaz** [comment]
If we're compiling for a es2021 target, shouldn't a true `#foo` compile to `#foo`? Right now it compiles to a `WeakMap` which I understand for compiling to older standards, but for the latest it doesn't seem like it should do that.

**Comment by mbrowne** [comment]
The [handbook](https://www.typescriptlang.org/docs/handbook/2/classes.html) states:

> When compiling to ES2021 or less, TypeScript will use WeakMaps in place of #.

I'm not sure why private fields didn't make it into the ES2021 target, but in any case it seems that the only way to get TS to output native private fields at the moment is to use `esnext` as the target:

```
"target": "esnext"
```

**Comment by ljharb** [comment]
Because class fields are in ES2022: https://github.com/tc39/proposals/blob/main/finished-proposals.md

**Comment by trusktr** [comment]
> It could still be nice to have an option to make `private` compile to some sort of _soft_ run-time privacy though. (So not `#`, but maybe symbols...)

I believe that's out of scope of TypeScript's goals (essentially the goal is to avoid producing new language features, and make only type syntax on top of standard JS), but compiling `private` to soft privacy using symbols, under an option, would in fact be pretty sweet.

**Comment by ArrayIterator** [comment]
2025! the private visibility modifier can be dangerous on some case, eg : doing Stringify object, the private modifier can be exposed on JSON.

**Comment by Finesse** [comment]
> There's nothing gained but confusion by adding a flag to conflate the two.

There is something gained. The #-fields can be shortened easily, similar to how function, class and variable names are minified. Tools like Terser replace long #-names with short garbage. This gives 2 advantages:
- Better concealing of the source code.
- Better code size deduction from minification.

Do you have other options for achieving these goals? Replacing all `private` fields with #-fields in the source code is a solution, but it's awkward for multiple reasons. Having `tsc` do a prepending of `#` to the private fields is such a simple and elegant solution, that I'm surprised it hasn't been implemented yet. I call it simple, because it can be done in a file using just the content of that file. That is, it doesn't violate `isolatedModules`.

> because that would require type-directed emit

Why is it allowed for `const enum`? It's also an elegant solution for source code concealing and code size deduction. What's the key difference?

**Comment by snarbles2** [comment]
> Having tsc do a prepending of # to the private fields is such a simple and elegant solution, that I'm surprised it hasn't been implemented yet. 

It really, really isn't that simple. `private` and `#` have different semantics. Transpiling the former to the latter can break things in all kinds of ways. 

You would have to change the meaning of `private`, but the (subjective) upsides of having a "soft-private" and backwards compatibility concerns make for a rather strong argument against doing so, to put it mildly. 

You could argue for having a compiler switch, but if people find it confusing that `#` and `private` mean similar but not identical things, you're not doing the world favors by adding into the mix that `private` could mean two different things depending on compiler version or settings.



> Why is it allowed for const enum? It's also an elegant solution for source code concealing and code size deduction. What's the key difference?

It is grandfathered in, a vestige from before TypeScript adopted the position against type-directed emit.

**Comment by irfanstract** [comment]
> the private visibility modifier can be dangerous on some case

so we should start warning against `private` and call for rewrite.

```diff 
     private lastChgd: number;
+    ^^^^^^^
+    classic 'private'. consider migrating to ES Private Fields.
```

```typescript
abstract class LivingDocument {
  private lastChgd: number;
  ...
}
```

> Why is it allowed for `const enum`?

certain transpiler(s) drop `const` and treat them like plain `enum` maybe?

**Comment by RyanCavanaugh** [comment]
You can add a lint rule if you don't want to use `private`. We're not going to break huge amounts of code for a "warning" that doesn't do anything.

**Comment by ljharb** [comment]
What about a tsconfig option that removes it entirely?

**Comment by snarbles2** [comment]
Why would you want to remove it? It has well understood semantics that can be useful. I'm not sure any of the considerations that factored into to the current state of affairs have changed meaningfully.

**Comment by RyanCavanaugh** [comment]
Why have a flag for banning `private` vs any other syntactic feature you might not like? I don't get the distinction

**Comment by rjgotten** [comment]
> Why have a flag for banning `private` vs any other syntactic feature you might not like? I don't get the distinction

Why have a flag for banning `any` then?
`private` arguably does more real-world harm than `any` - given private isn't actually private and the corpus of code written by neophytes with wrong expectations about it.

**Comment by ljharb** [comment]
@RyanCavanaugh there's a large qualitative difference between banning a type-space syntax and banning a value-space syntax, especially one that will never be standard, and whose emit provides false encapsulation.

@snarbles2 none of its semantics are useful - if you want truly private data, use JS private fields; if you don't, just use symbols or strings (like, a leading underscore, or whatever). `private` is no different than the latter.

**Comment by snarbles2** [comment]
Certainly not true. There are things you can do with `private` that you can't with `#private`, and `private` is still compiler enforced. This even comes up in vanilla JS, where you have to resort to _prefixes. 

You *can* use symbols for that purpose, I suppose, but I have a hard time buying that I should sacrifice ergonomics/readability to satisfy somebody else's notion of what's "right".

I'm usually the last person to make this suggestion, but a linter is the right solution here.

**Comment by mbrowne** [comment]
One thing that might help would be to say that the `private` keyword is deprecated in the official docs. Obviously it won't ever be removed because of the need to preserve backward compatibility, but it's non-standard and IMO it would make sense to officially deprecate it given native private and other options available.

**Comment by rjgotten** [comment]
> There are things you can do with `private` that you can't with `#private`

And you can only do those things because `private` is misnamed and actually at runtime is anything-but.

> I'm usually the last person to make this suggestion, but a linter is the right solution here.

An option in the compiler to disallow `private` - pretty much the same as the one that disallows `any` - for all intents and purposes **is** a linter option.


> You can use symbols for that purpose, I suppose, but I have a hard time buying that I should sacrifice ergonomics/readability to satisfy somebody else's notion of what's "right".

I would be all for TypeScript inventing a syntax for symbol usage that could desugar properly without runtime surface as well as make `unique symbol` easier to stomach within the typing system. Because woo-boy is that a pain in the dot-dot-dot to work with...
