### ISSUE TITLE
`keyof never` should be `never`

### ISSUE THREAD

**Issue by AnyhowStep** [microsoft/TypeScript#33025]
**TypeScript Version:**  3.5.1

**Search Terms:**

keyof never

**Code**

```ts
//Expected: type k = never
//Actual  : type k = string | number | symbol
type k = keyof never

```

**Expected behavior:**

`keyof never` should be `never`

**Actual behavior:**

`keyof never` is `string|number|symbol`

Intuitively, to me, if no values inhabit `never`, then the set of keys is the empty set (also `never`).

**Playground Link:** 

[Playground](http://www.typescriptlang.org/play/#code/PTCiA8AcFMGMBdoBMBcACeBPGaDWaBeNAO2gDdoAnAKBAEEEBXAQwBs010sd8iBneJQCWxAOZoAPiUYBbAEZVJaPpnkB7VtW7Q8hPNExqAZiXJVqQA)

**Related Issues:** 

Searching "keyof never" brought up 400+ total results, so...

**Comment by dragomirtitian** [comment]
Should it though ? `never` is the  subtype of all types. You can never create a value of this type that is true. But as the sub-type of all types i would expect it to be index-able by any value that can be an index. This is also supported by value-space behavior:

```ts
declare let o: never;
let v1 = o[""]
let v2 = o[1]
let v3 = o[Symbol()]
```
[play](https://www.typescriptlang.org/play/#code/CYUwxgNghgTiAEEQBd4HsBc8B2IBuIMA3AFBKp4CM8AvOgNoBEjAumSvHgEy0OVvlOAZl5p6AZQCeAWwBGaCAAoAlCyA)

**Comment by AnyhowStep** [comment]
`{ x : any }` is a subtype of all types `{ [k:string]:T}`

I wouldn't expect `{ x : any }[""]` to work, though

**Comment by RyanCavanaugh** [comment]
It some sense, it doesn't matter. `string | number | symbol` is a correct upper bound on all keys, though, so it's a sensical result. I don't see value in breaking any odd dependencies on the behavior either way.

**Comment by jcalz** [comment]
If one reasons that `keyof (A & B)` should always equal `keyof A | keyof B`, then `keyof never` needs to be an upper bound on keys, such as `string | number | symbol`.

**Comment by RyanCavanaugh** [comment]
@jcalz great point. The dual of that would actually be more important -- if `keyof (A | B)` is `(keyof A) & (keyof B)`, then setting `keyof never === never` would break `never` being the identity operand of union because `keyof (A | B | never)` would incorrectly be `never`.

**Comment by AnyhowStep** [comment]
> `string | number | symbol` is a correct upper bound on all keys

It's a correct upper bound on `keyof {x:any}`, too.
But the result of that is `"x"` and not `string | number | symbol` =P

-----

If we take it as an axiom that `keyof (A | B)` should **always** equal `(keyof A) & (keyof B)`, then I guess you're right that `keyof never === string | number | symbol` logically follows.

But why not apply union simplification first?

So `keyof (A | never)` is just `keyof A`

You would still get results consistent with current behaviour but `keyof never === never`.

-----

For `keyof (A & B)` if the intersection is `never`, shouldn't the result be `keyof never` and not `(keyof A) | (keyof B)`?

So, perform intersection simplification to get `keyof never` and get `never`.

You would still get results consistent with current behaviour but `keyof never === never`.

**Comment by AnyhowStep** [comment]
I guess it's that vacuous truth thing.

`keyof A` := `{ k : ∀x (x ∈ A → k is property of x) }` (optional properties count as properties, too)

When `A` is `never`, we have a vacuous truth,
```
∀x (¬x ∈ never)
-----
∴ ∀x (x ∈ never → k is property of x)
```

So, all keys `k` are keys of `never`.

-----

Whereas for `unknown`, there's always a counterexample for every `k`.

**Comment by fatcerberus** [comment]
Yep, contravariance (w.r.t. `keyof`) + principle of explosion.  `never` can act as any other type (Haskell's `absurd`, e.g., is based on this concept)--or rather, we can *pretend* it does because you can't soundly obtain such a value.  Therefore it gets the widest possible key.

It *is* a bit odd though in that you can't actually *index* a `never`.  That's probably where the confusion came in.

**Comment by weswigham** [comment]
FYI, for anyone reading: #30753 for context - back after we introduced `keyof`, `keyof never` _was_ `never` - this caused a bunch of issues (it's internally inconsistent, the result _does matter_, and it matters quite a bit), so we fixed it back in April.

The current behavior of `keyof` at its bounds is certainly more correct - you can convince yourself as such with a simple inductive argument:

Suppose I have an object, `{}`. We know `keyof` an object type is supposed to return the keys of said object, so `keyof {}` is `never`. `never` theoretically implements every conceivable function or property, but, as a set of allowable values, is empty (therefore, is the result when an object has no keys). Now suppose we add a property to our input object, `{x}`, and we look at `keyof {x}`. Out input has become more specific - the set of allowed values is smaller. Conversely, the result of `keyof` is now `"x"`. So our set of output values is now _larger_ - this inverse relationship continues as you add more and more properties to a type - `{x,y}` is a smaller set of values than `{x}`, while `"x" | "y"` is larger than just `"x"`. Now, remember what I said earlier - `never` conceptually implements _all_ properties - so the logical extreme - the _most specific_ type we can feed into `keyof` is `never`. That, in turn, produces the _broadest possible_ result - `string | number | symbol` (the union of all possible properties).

**Comment by fatcerberus** [comment]
Or just the principle of explosion: `never` (bottom ⊥) has no inhabitants and therefore having a value of this type puts you in a state of contradiction.  Therefore we can prove anything from it, including that it has all possible property keys.

**Comment by jack-williams** [comment]
_String Index Signatures_

![Index Signatures](http://giphygifs.s3.amazonaws.com/media/4pMX5rJ4PYAEM/giphy.gif)

**Comment by StreetStrider** [comment]
I still don't get the motivation behind this design, but it seemes like a complicated area. I agree that there may be a reason for current behavior.

However, I got specific scenario in mind which lead me here and this is why I think the current behavior is more broken.
[playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBA0hJUQXigZ2AJwJYDsDmAUKJFAGoCGANgK7QoDeUAHgFxQ7UC2ARhBlAF8i4aABFywcsiiMA2lADW8KLljKAumwo1oQgrmB8AZuQDG0AEIB7JlAA8oqBCaGcAE1RRxkgHwF6BIiIOOQYGFYA7vYwTi4Q7p5wID5QABRKIGwwAJRZsa4eivBWRl5QAPxQ1kx2ckUIqjGaXhLksjDqgilsOBAAbnwANAR6RtQ4psBYVjhVNvaOzgWe3uQpqW6tbKK5czWifgFBUBgQwNQYs6n0AlDknuQ4INkjBMIk1QD6q-YW+fGFap2R7JFIoP5LAGeIG4Ix8Fq+CoIqQ9fp8d6WGyfJKeOwQuIJPbAp4+MH1Ep7b6tPF+AD0tKgxExTGx8Fx+OWRJBpKg4P+hJhODh-FWKUqGQpP1RAwwbyZUAAKgBGXmUnF4my1ASkjGKgBMqq+6qBjHIbEYrCgKtu2r88oVAGZDVj1YwjFYrGwAOTcUJerpQelOUKUBA4KxTIwIGZQCLhfAqHBgajAN6mGboKDcFXgmzXO7m5hsa2DLOFy0Gm0veWKgAszpZ6qZFOzfgI6Zwmezn0wtGk2YAdCEwpFUl7yF6Xh2u0rPiZKKg6FmlUPQuEImPTJO5SJFQqG6yQKg7M3St3exA7buFQAxA9NkQt2fzxd+IA).

In short, I got `Box` type with some encapsulated data which is strongly typed. And I got two helper type functions, `Box_Data` and `Box_Keys`. I want the second one to be built on top of the first one to reuse code. However, if the first one resolves to `never` (which is desired), the second one would return key supertype (`string | number | symbol`), while I need it to be `never` as well. I need `never` because later I need to use `Box_Keys` in some predicate scenario but `extends never` and `extends string | number | symbol` got the opposite results. The second one is incorrect, since it says that my empty boxes are supertypes of my filled boxes, which is incorrect.

To fix this I need to replace line 16 with line 17. The difference is only syntax, but it lead to opposite behaviors. To fix this behavior I need to copy-paste logic. The difference is subtle, but it might took some time to track this down in complex codebases.

**Comment by RyanCavanaugh** [comment]
This is one way to think of it: `keyof` is a contravariant operation, so if its input is from the zero-width part of the triangle (`never`), then the output has to be whatever the largest possible part of the triangle is (`string | number | symbol`)

![image](https://user-images.githubusercontent.com/6685088/176029842-4d92fbbd-bf5a-41c2-aa32-7dbc84cde4b2.png)

**Comment by cevr** [comment]
@RyanCavanaugh i honestly could never remember nor understand what those words meant until this diagram. offtopic, but thank you for this

**Comment by HansBrende** [comment]
@AnyhowStep food for thought: your logic would make complete sense if `keyof` took the _union_ of keys over a union of objects rather than the _intersection_ of keys over a union of objects. And indeed, if you rewrite `keyof` to implement the former behavior via _distributing_ over the union:

```typescript
type KeyOf<T> = T extends unknown ? keyof T : never
```

Then you get the behavior you are expecting:

`KeyOf<never> === never`
