### ISSUE TITLE
module: esnext should append .js to imports

### ISSUE THREAD

**Issue by amitport** [microsoft/TypeScript#33588]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**
modules

**Code**
having a local-lib.ts

index.ts
```ts
import X from 'local-lib'
```

should compile with `"module": "esnext"` to:
```ts
import X from 'local-lib.js'
```

**Expected behavior:**
`.js` should be appended to imports of local es modules
(this is required in node and browser modules support)

**Actual behavior:**
no `.js`
**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
TypeScript always emits JavaScript code as written, and import statements are JavaScript code so aren't changed on emit. You should always write the import path that you want to appear in the emitted JS file.

**Comment by amitport** [comment]
@RyanCavanaugh hi give me a chance before closing...

1. typescript code can have different compilation targets. `target` + `module` in `tsconfig` should _determine_ and act differently when I'm using:
  1.1. commonjs don't touch extensions
  1.2 nodejs es6 module without `type: module` meaning it should have `.mjs` extensions
  1.3 browser es6 and nodejs `type: module` package meaning it should have `.js` extensions
2. I may actually compile in-place. Having hard-coded `.js` extension in typescript files will mean I'm importing previously generated '.js' files and those will be analysed instead of the imported typescript files.

**Comment by RyanCavanaugh** [comment]
We read comments on closed issues and you're able to comment on them; open/closed is simply an indicator of whether there's engineering work that needs to happen next. As I indicated, this is the intentional behavior of TypeScript, so there's no next steps in terms of code changes.

Those are all problems with JavaScript and should be addressed by whatever tool you would have fixed it with if you weren't using TypeScript. One of TypeScript's key design goals is that TypeScript always emits JavaScript code as written, and import statements are JavaScript code so aren't changed on emit.

**Comment by amitport** [comment]
Hi thank you for the responding, but I really just want to note that I still don't see how problem 1 is different from other problems addressed by typescript. For example, compiling imports to commonjs in the first place. It is just downleveling according to the `tsconfig`'s `target` (unfortunately, some targets have different extension handling)

Regarding problem 2, I don't know how it can be addressed outside of typescript, maybe I'm missing something (of course avoiding `in-place` compilation is an option, but it should not be a limitation  imposed by typescript IMO)

**Comment by grumd** [comment]
@RyanCavanaugh Is there a solution on how to make this code work then?

```js
// a.ts
export const a = 1;

// index.ts
import { a } from './a.ts';
console.log(a);
```

If I set the target to ESNext, it compiles into `a.js` and `index.js`. Doesn't matter if I type `import { a } from './a.ts';` or `import { a } from './a';` I get code that's unusable, because Node expects to see `./a.js'`. I can't run compiled code that Typescript emits with Node with ESNext.

**Comment by pvarga-dni** [comment]
For those ending up here from Google looking for a solution:

Write `import X from "./X.js"` (so ending in `.js`) in **`.ts(x)`** files, when outputting ESM. 
This is because the compiler's output will go to X.js and as mentioned above, import specifiers are not modified by TypeScript, so it won't add `.js` for you neither will it change `.ts` to `.js`.

**Comment by amitport** [comment]
@pvarga-dni this doesn't solve the issues I've mentioned above. Just motivates a reopening of this issue. As you said, Typescript will output the import string as is and during development will use the wrong file in in place compilation (.js instead of .ts).
@RyanCavanaugh
