### ISSUE TITLE
Add types for window.performance.getEntriesByType

### ISSUE THREAD

**Issue by third774** [microsoft/TypeScript#33866]
## Search Terms

getEntriesByType
PerformanceMark
PerformanceMeasure
PerformanceResourceTiming

## Suggestion

Add types for the [`getEntriesByType` API](https://developer.mozilla.org/en-US/docs/Web/API/Performance/getEntriesByType)

I found [this old issue (Jul 5, 2018)](https://github.com/microsoft/TypeScript/issues/25461) and saw that experimental API's are not included in `lib.dom.d.ts`. The following API's don't appear to have `experimental` warnings on them on the MDN docs. Hopefully this means these are no longer experimental and types can be added now?

https://developer.mozilla.org/en-US/docs/Web/API/PerformanceMark
https://developer.mozilla.org/en-US/docs/Web/API/PerformanceMeasure
https://developer.mozilla.org/en-US/docs/Web/API/PerformanceResourceTiming

## Use Cases

Getting specific strongly typed information for the entries when accessed via this API.

## Examples

```ts
// resources would be of type PerformanceResourceTiming[]
const resources = window.navigation.getEntriesByType("resource");

// resources would be of type PerformanceMeasure[]
const measures = window.navigation.getEntriesByType("measure");

// marks would be of type PerformanceMark[]
const marks = window.navigation.getEntriesByType("mark");

// paints would still be of type PerformanceEntryList
const paints = window.navigation.getEntriesByType("paint");
```

## Checklist

My suggestion meets these guidelines (not sure about the first one):

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by third774** [comment]
Doh! Tried to open a PR for this, but looks like the work is over in https://github.com/Microsoft/TSJS-lib-generator. Should I move this issue to that repo?

**Comment by TaylorPzreal** [comment]
Waiting the feature.

**Comment by DerGernTod** [comment]
any updates on this?

**Comment by HolgerJeromin** [comment]
This is fixed since a few versions. Probably 4.4 or even earlier.

**Comment by billyvg** [comment]
@HolgerJeromin That is a different issue that doesn't address the return type of `getEntriesByType()`, see https://www.typescriptlang.org/play?ssl=14&ssc=1&pln=14&pc=61#code/PTAEAUFMCcDMHtoFsCGA7AxpAcigbgJYDmKALgfGgCoFIFpEDaAugFAaUDOpoa+xZCmgCiaUtAKROoALygA7vQAm8eQDoADjATJ0WNUUilR4yZwBCATyqWtACgDkfQiXKUHASgDcrViAjaiKiYkABKUvAArtBYNHQMLOxcPNAR0VjScopoKupacEF6kAZGJhJSVjb2AESpnFExkNXevv5QBbohALKQKJzRkIkcaNygSL39dbIKyqqagZ36hsZi5RbWtpB21eN9A80+fmDtOsFYXSjQANZDyWOXV5kzOXP5p0UlK6YVGzWo1wdWscFmdIOAUPRSHF6EQkiMeBoIWIntlcvMOqDPmUzJVNttEZCDkA

**Comment by HolgerJeromin** [comment]
Ok, missed that detail. Current state models spec:
https://w3c.github.io/performance-timeline/#extensions-to-the-performance-interface

But yes could be more clear by adding overridingTypes:
https://github.com/microsoft/TypeScript-DOM-lib-generator#when-the-type-exists-but-is-wrong

BTW, added [type debug](https://www.typescriptlang.org/play?#code/PTAEAUFMCcDMHtoFsCGA7AxpAcigbgJYDmKALgfGgCoFIFpEDaAugFAaUDOpoa+xZCmgCiaUtAKROoALygA7vQAm8eQDoADjATJ0WNUUilR4yZwBCATyqWtACgDkfQiXKUHASgDcrEKH+gAHoA-Ky+YFBwiKiYkABKUvAArtBYNHQMLOxcPNCJKVjScopoKupaUbqxBkYmElJWNvYARHmcyamQzd7hAUGhvZE6MVgAspAonCmQWRxo3KBIE1NtsgrKqpra0XqQNcZi9RbWtpB2zUuT090+fgEhYX5DO7GjKNAA1rM5i+8fRetSpsKsNdvs6mZGqdzqhPjdevcBk9tlUsOAUPRSOl6ERsvMeBoMWIASUyltKiM9oYDqYGicWoTMfC7v4QkA) information to your playground link.

**Comment by schickling** [comment]
Is someone aware of any available NPM package that provides the missing types as a workaround for now?

**Comment by RyanCavanaugh** [comment]
Confirmed on 5.9, the requested specialization is still not there.

It'd be great if OP's code example were correct (it's `.performance` not `.navigator`) and clarified the current behavior

**Comment by DerGernTod** [comment]
If this is going to be worked on, I'd like to highlight that this also applies to `performance.getEntriesByName` - it supports a second argument specifying the type: https://developer.mozilla.org/en-US/docs/Web/API/Performance/getEntriesByName

I think it makes sense to type these function return types depending on the second argument, so that if I call e.g. `performance.getEntriesByName("myMark", "mark")`, I properly get a `PerformanceMark`.
