### ISSUE TITLE
disable certain global types for specific files, or specify type roots for specific files.

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#37053]
This continues some ideas from https://github.com/microsoft/TypeScript/issues/17042, which was closed by @microsoft (for inactivity, I think?).

## Search Terms

disable certain global types for specific files, specific type roots for certain files

## Suggestion

Ability to specify which `@types` (or in general, which specified `typeRoots`) apply to which files in a project.

## Use Cases

My project's `src` folder contains both `.ts` and `.test.ts` files, and I'd like an easy way for globals like `describe` to be defined only for the `.test.ts` files.

## Examples

Not sure, but maybe some sort of new options in `tsconfig.json` for specifying which `types` items, `lib` items, or `typeRoots` items apply to which files.

This would be a beneficial feature because various editors (aside from VS Code) look for a `tsconfig.json` file at the root of a project, and at the moment the only way to make types work in all files is to just provides all types for all files, which is undesirable because `describe` is not a function that is available in source files (as an example).

Example configuration: maybe instead of a `typeRoots` array, it can be an object like:

```js
"typeRoots": {
  "./src/**/*.test.ts": ["../path/to/test/types"], // test-only types
  "./src/**/*.ts": ["../path/to/@types"] // other types other files
}
```

Or something. That's just an example to get the idea rolling.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by trusktr** [comment]
The main concept is that we often need to install `@types` packages as devDependencies to use global types in things like tool configurations, scripts, tests, etc, and then those global types leak into source files (although they actually aren't available at runtime in those files).

**Comment by trusktr** [comment]
The the new `composite` feature (described in the [Project References](https://www.typescriptlang.org/docs/handbook/project-references.html) doc) allow this request to be possible now?

**Comment by trusktr** [comment]
This is quite an issue. It keeps popping up.

What we need is an _official_ and more robust way of managing which global types be included _or_ excluded.

Setting `types` to an empty array and manually listing all global types only to exclude, for example, a single global lib, is not ideal.

Here's a set of issues with people effectively asking for more control over global types:

- https://github.com/microsoft/TypeScript/issues/17042
- https://github.com/microsoft/TypeScript/issues/18588
- https://github.com/microsoft/vscode/issues/10285
- https://github.com/microsoft/TypeScript/issues/21189
- https://github.com/microsoft/TypeScript/issues/11917
- https://github.com/microsoft/TypeScript/issues/15933
- https://stackoverflow.com/questions/48704043/exclude-types-typings-in-installed-dependencies
- https://stackoverflow.com/questions/52621222/how-do-you-exclude-global-types-declared-in-typescript-definitions
- https://stackoverflow.com/questions/48427807/tsconfig-how-to-ignore-types-whatever-node-modules-for-a-specific-directory
- https://stackoverflow.com/questions/56188867/conflicts-with-global-types-in-typescript
- https://stackoverflow.com/questions/58507122/how-to-exclude-types-from-typescript-global-cache-users-user-library-caches
- https://stackoverflow.com/questions/41558661/ignore-bundled-d-ts-and-use-external-declarations

**Comment by aleclarson** [comment]
Can we get an official response on this?

It's very annoying when I'm working on a browser-related project, and `@types/node` leaks in because a package in `devDependencies` depends on it.

**Comment by aleclarson** [comment]
This seems to be the current proposal:
https://gist.github.com/RyanCavanaugh/702ebd1ca2fc060e58e634b4e30c1c1c

**Comment by Fallenstedt** [comment]
I experienced a global clash issue today, and reproduced it here 
https://github.com/Fallenstedt/ts-globals-clash

Say you had a monorepo with two packages `a` and `b`. 
* `a` uses the jasmine test runner
* `b` uses the jest test runner

The problem is `b`'s test files are only reading jasmine types...when they should have jest types. Having the ability to exclude types for specific directories would be amazing.

**Comment by RyanCavanaugh** [comment]
> Excluding type packages with file globbing sounds much nicer.

This is just going to create compile errors in lib files that need them (and they surely must need them, otherwise they wouldn't reference them in the first place). The problem here isn't that *random* definition files end up in your program, the problem is that *transitive dependencies* end up in your program even though they're immaterial to your particular use case.

**Comment by trusktr** [comment]
Hello everyone and @RyanCavanaugh (and @aleclarson because you pointed out Ryan's proposal). 

I've come up with a new compiler option idea that may solve some of the problems above (unless I missed that such a solution already exists):

https://github.com/microsoft/TypeScript/issues/42003

The hypothetical new `declareOnImportOnly`, when set to `true`, would prevent global and module augmentations from running unless you explicitly `import` the file that the augmentation code is inside of.

Rather than all `declare global` and `declare module` definitions eagerly making their way into your scope from any file in your project (including node_modules), they will all stay out, unless `import`ed.

This seems like a very practical role for `import` syntax to have (you get what you import).

**Comment by trusktr** [comment]
The reason for my previous comment is, apparently, global types are picked up even when `tsconfig.json` contains

```json
    "types": [],
    "typeRoots": []
```

and you've imported _anything_ from a package that has global types (even if you never import the files that `declare global`). It completely ignore `types` and `typeRoots` in this case.

> The problem here isn't that random definition files end up in your program, the problem is that transitive dependencies end up in your program even though they're immaterial to your particular use case.

@RyanCavanaugh Another problem is that some parts of one project need certain globals, while other parts of a project need other globals.

For example, having two forms of JSX in a project where some files need to pick up React's global JSX, and in the other files we want some other JSX types without React's JSX types polluting global.

**Comment by AlexGalays** [comment]
Everyone has the same issues, which indicate something must be done.

A purely browser project shouldn't be forced with ambient node types which almost always end up being loaded (I don't think we can fix it at this level as it would require every single lib and their dependencies to be a good actor) and pollute the global namespace.

**Comment by aleclarson** [comment]
@RyanCavanaugh I have a suggestion for [your proposal](https://gist.github.com/RyanCavanaugh/702ebd1ca2fc060e58e634b4e30c1c1c).

In addition to setting `strictEnvironment: true`, projects should have the option to include a specific `@types` package in any file matching a defined glob. My suggestion is to let the `types` option be a "glob map" like below:

```ts
// tsconfig.json
{
	"compilerOptions": {
		"types": {
			"**/__tests__/**": ["jest"],
			"src/node/**": ["node"],
			"src/client/**": ["lib:dom"]
		}
	}
}
```

**Comment by andreialecu** [comment]
One other use case for this would be when a misbehaving package adds a global type that it shouldn't.

For example, `@apollo/client` adds the following:

```ts
declare global {
    interface Observable<T> {
        ['@@observable'](): Observable<T>;
    }
}
```
(https://cdn.jsdelivr.net/npm/@apollo/client@3.3.12/utilities/observables/Observable.d.ts)

This conflicts with `rxjs`'s own `Observable` which creates editor issues in VSCode. A way to override this at the project level would be great.

See:
https://github.com/apollographql/apollo-client/issues/7839

> While this can be resolved by manually adding the import. It breaks editor auto import functionality as the editor thinks Observable is already a known type. This is a major pain as rxjs/Observable is used in nearly everywhere (angular app).

**Comment by sabberworm** [comment]
This is one of the few things about TypeScript that have irked me enough times over the years that I was going to open my own issue. But then I found this, which is sorta close enough, so I’m chiming in here:

IMO, global type declarations, despite the name, shouldn’t be made available globally at all. The “global” refers to them defining something in the global context. That doesn’t mean, however, that every file in a project should have access to it implicitly.

Especially in modules (files with `import`s or `export`s), where everything is side-effect-free and files are essentially meant to be isolated, having global types be implicitly available seems flat-out wrong.

## Suggestion 1

I suggest adding another opt-in “strict” option, to remain backwards compatible. Having it enabled would mean global declarations would only be available in the file that imported it explicitly and importing a type declaration with global types wouldn’t make it implicitly available in all other project files as well.

This way, tests could be compiled along with source files in the same tsconfig without the source files suddenly having `test`, `expect` and whatnot defined. Each test file would instead have to explicitly use `import 'test-framework'` or `/// <reference types="test-framework" />`.

## Suggestion 2

I think what lies at the core of this issue is that many module type declarations contain global declarations and exports, for legacy/UMD reasons. So one other partial solution would be ignore the global declarations when importing something from a module (as opposed to importing the module itself).

In this version, `import 'jquery'` and `/// <reference types="jquery" />` in any file (or `"types": ["jquery"]` in tsconfig) would still make the `$` global variable available in all files but `import $ from 'jquery'` would not.

This wouldn’t help much with the unit test example since many unit test frameworks’ typings only expose global declarations and have no exports declared, as the globals are injected by the test framework.

## Open questions

* How would either of these interact with the various options for `types` in tsconfig?
* How to handle local ambient module declarations (i.e. outside `typeRoots`)?
* Should the global declarations available to imported files be inherited?

**Comment by FrederickEngelhardt** [comment]
Any updates on this feature request? I've run into this limitation many times. 

Adding a global way to control typeRoots would really make things much easier than having to manage configuration via inheritance and overrides.

So far I've been creating child `tsconfig.json` files that scope types better. Also been generating config dynamically for builds especially if you need type completion for testing purposes but are not shipping those types in your build.

**Comment by samwightt** [comment]
Any updates on this? Dealing with an issue where `@types/express-jwt` modifies some types in the `express` namespace (which is _incredibly_ hard to track down because TypeScript never tells you that this is the case in its errors). I cannot remove the types because one of my packages depends on them. This means my only choice currently is to list out about 20-30 items in the `"types"` array, which just isn't ergonomic. And this is on a smaller project.

It's very annoying that something like this exists for 'inside the project' files but not for types. The current experience just isn't a good developer experience and is a **massive** annoyance on larger projects.

**Comment by luxalpa** [comment]
I don't have any suggestions, but another use case:

I want to use Storybook which internally adds `@types/react` with a vue.js project. Unfortunately the React types are overriding / merging the vue shims, therefore Vue's JSX syntax can not be used anymore :( Not sure what the solution to that problem is?

**Comment by publicvirtualvoid** [comment]
Monorepo using NX here - We build browser, NodeJS, and workers from a set of common libraries. The issues this aims to solve easy to make and very time-consuming to resolve.

**Comment by ajubin** [comment]
I've encounter a similar issue, when developing a web application with nextjs.

I have a function called `reportError` which is also a function declared in the global namespace [here](https://developer.mozilla.org/en-US/docs/Web/API/reportError) but this doesn't always exists.

I forgot to import my function but I got no warning from the ts compiler.

I've fixed this by renaming my function, but I'd love to remove `reportError` from the globals to prevent this issue to happen again

**Comment by zatloeri** [comment]
I am running into this while developing a app with `require` js environment.

I am using jest for testing, but as soon as I include `jest/utils` node global variables get pulled in and override global `requirejs` variables like `require` and `module` thus making the code intended for `requirejs` env not compile correctly.

For anybody looking for workaround ideas:
I have worked around this by splitting the project into two ts projects (app and jest tests) adding a `import './globalTypeOverride'` (where I have specified the global types I need for the code to compile) in my jest part of the project and using `declare` to redefine the global variables ad-hoc in jest (for example when I actually need to use Node `require`).

**Comment by lgarron** [comment]
> The reason for my previous comment is, apparently, global types are picked up even when `tsconfig.json` contains
> 
> ```json
>     "types": [],
>     "typeRoots": []
> ```
> 
> and you've imported _anything_ from a package that has global types (even if you never import the files that `declare global`). It completely ignore `types` and `typeRoots` in this case.
> 
> > The problem here isn't that random definition files end up in your program, the problem is that transitive dependencies end up in your program even though they're immaterial to your particular use case.
> 
> @RyanCavanaugh Another problem is that some parts of one project need certain globals, while other parts of a project need other globals.
> 
> For example, having two forms of JSX in a project where some files need to pick up React's global JSX, and in the other files we want some other JSX types without React's JSX types polluting global.

Having spent several hours trying to get `mocha` and `chai` types to work "without magic", this rings very much true.

One particular place I've recently found this frustrating is module augmentation for testing frameworks. `chai` provides:

```ts
const Assertion: typeof import("chai").Assertion = untypedAssertion;
Assertion.addMethod("identicalAlg", function (expected: string): Promise<void> {
  // ...
});
```

The following doesn't work:

```ts
declare module "chai" {
    // .. only augment Chai.Assertion
}
```

So I have to do this:

```ts
const Assertion: typeof import("chai").Assertion = untypedAssertion;
Assertion.addMethod("identicalAlg", function (expected: string): Promise<void> {
  // ...
});

declare global {
  export namespace Chai {
    interface Assertion {
      identicalAlg(expected: string): Promise<void>;
    }
  }
}
```

Now these types are available from every file in the project. But:

1) I only want this to be available in test files,
2) when the types are valid, which is only the case when `Assertion.addMethod` has happened in an import.

The current situation forces me to choose between several non-obvious behaviours that make it harder to make the project easy to maintain and contribute to.

(Of course, there are also issues like others have described in this thread, such as `@types/node` being available everywhere instead of only the files where `node:` modules are directly imported.)

**Comment by kesupile** [comment]
Any updates on this issue? 

It's something that has come up quite a few times recently. Personally, I think @aleclarson's [suggestion](https://github.com/microsoft/TypeScript/issues/37053#issuecomment-789769567) would be the most easy to understand while giving the most fine grained control.

**Comment by RyanCavanaugh** [comment]
The linked suggestion doesn't really solve anything IMO. If different parts of the program can "see" different global files, then they have different global scopes, and they have different interpretations *of the same type*.

Let's say you had something like this
```ts
// lib.object_rotation
interface Object {
  rotate(): void;
}
```
where file1 can "see" `lib.object_rotation` and file2 can't. What happens if you try to take an `Object` from file2 and give it to file1? Isn't it a type error, since it doesn't have a `rotate` method? What about assignability caching -- if file1 sees that `Object` is assignable to `Rotatable`, then file2 will have the same interpretation. So the entire assignability cache is now useless, or has an additional cache key of some kind.

These problems can be "solved" by the same mechanisms that we use for project references (IOW, separate compilations), but it's not clear what this extremely confusing per-file-global system would have *over* the existing solution of project references.

**Comment by muuvmuuv** [comment]
Eslit does a great job here with env and so on. Where you have a global and override scope. Whereas overrides can provide the same options as the toplevel scope but overrides object properties (or extends them) and arrays.

See https://github.com/angular-eslint/angular-eslint "Notes on eslint" for an example what I mean.

**Comment by kesupile** [comment]
> The linked suggestion doesn't really solve anything IMO. If different parts of the program can "see" different global files, then they have different global scopes, and they have different interpretations _of the same type_.
> 
> Let's say you had something like this
> 
> ```ts
> // lib.object_rotation
> interface Object {
>   rotate(): void;
> }
> ```
> 
> where file1 can "see" `lib.object_rotation` and file2 can't. What happens if you try to take an `Object` from file2 and give it to file1? Isn't it a type error, since it doesn't have a `rotate` method? What about assignability caching -- if file1 sees that `Object` is assignable to `Rotatable`, then file2 will have the same interpretation. So the entire assignability cache is now useless, or has an additional cache key of some kind.
> 
> These problems can be "solved" by the same mechanisms that we use for project references (IOW, separate compilations), but it's not clear what this extremely confusing per-file-global system would have _over_ the existing solution of project references.

True, but I don't think anyone asking for these changes would actually use the system in that way. If file1 and file2 share data, then usually they're either in the same environment or the interface between them is explicitly defined. If the interface isn't explicitly defined, it wouldn't be unsurprising if the compiler raised an error.

**Comment by clshortfuse** [comment]
Reproducible:

````
npm install @types/mocha
npm install typescript

mkdir test
echo context > test/test.js
npx tsc test/test.js
# should pass ^^^

mkdir src
echo context > src/src.js
npx tsc src/src.js
# should fail ^^^
````

We want `/src` to not include `@types/mocha` but everything else instead. I haven't found a way to make this happen. 

Perhaps `compilerOptions.tests` can work with a glob/regex pattern:

`/tsconfig.json`:

````json 
{
  "compilerOptions": {
    "types": ["!(mocha)", "*"]
  }
}
````

`/test/tsconfig.json`:
````json
{
  "compilerOptions": {
    "types": ["*"]
  }
}
````

**Comment by MicahZoltu** [comment]
Am I correct that if you want a web project that has tests which run in node (meaning `@types/node`) present, the only way to have `require` not be accessible to you web project is to have two separate `tsconfig.json` files and have `types: [...]` in the web tsconfig include every `@types/*` **except** `@types/node`?  There is no way currently to have a tsconfig that excludes a single `@types` folder?

**Comment by jsejcksn** [comment]
@MicahZoltu Assuming you want to include all other `@types` packages, yes — because it's an allow list.

From https://www.typescriptlang.org/tsconfig#types:

> If `types` is specified, only packages listed will be included in the global scope.

As a workaround in the absence of negated pattern matching: you could write a simple script to generate a complete list by reading dependencies from `package.json` (or the dir structure from `node_modules`) — and remove the ones you don't want to include.

**Comment by wongchichong** [comment]
for now, in install those types into another folder

` pnpm add -D types_react@npm:@types/react`

and refer it as needed in specific files

`/// <reference types="types_react" />`

**Comment by gernotpokorny** [comment]
Can somebody please summarize in short what the problem is in regards to why there's not much progress and this issue is still not solved after three years, given how serious it is? It's obvious that a glob pattern is needed (as OP already mentioned), because the problem is on a file basis.

**Comment by jsejcksn** [comment]
> Can somebody please summarize in short what the problem is in regards to why there's not much progress and this issue is still not solved after three years, given how serious it is? It's obvious that a glob pattern is needed (as OP already mentioned), because the problem is on a file basis.

@gernotpokorny Other tasks have been identified to be more important.

TypeScript is [Free Open Source Software](https://en.wikipedia.org/wiki/Free_and_open-source_software), so anyone (including you and me) can fix the issues — and even contribute our fixes upstream (using the Pull Request feature), so that everyone can benefit.

**Comment by gernotpokorny** [comment]
@jsejcksn What is more important then having clean types in TypeScript? ^^

Shouldn't this be at the top of the list after critical bugs?

**Comment by ajubin** [comment]
If you use eslint, you can use this rule https://eslint.org/docs/latest/rules/no-restricted-globals to disable some globals

If you want to enable/disable on certain file, you can use either `/* eslint-disable no-restricted-globals */` at the beggining of the file or use overrides proprerty in `eslintignore` to match a given list of pattern

**Comment by clshortfuse** [comment]
This may now be solved with `extends` in v5.0.0 though I haven't confirmed this personally yet:

https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-rc/#supporting-multiple-configuration-files-in-extends

**Comment by acusti** [comment]
> > Can somebody please summarize in short what the problem is in regards to why there's not much progress and this issue is still not solved after three years, given how serious it is? It's obvious that a glob pattern is needed (as OP already mentioned), because the problem is on a file basis.
> 
> @gernotpokorny Other tasks have been identified to be more important.
> 
> TypeScript is [Free Open Source Software](https://en.wikipedia.org/wiki/Free_and_open-source_software), so anyone (including you and me) can fix the issues — and even contribute our fixes upstream (using the Pull Request feature), so that everyone can benefit.

@jsejcksn is there a solution to this problem that core typescript maintainers have indicated support for that someone from outside that core group could implement and PR upstream? the only comments in this thread from a core member are https://github.com/microsoft/TypeScript/issues/37053#issuecomment-730725238 (in which @RyanCavanaugh indicates that a file glob pattern solution is inviable) and https://github.com/microsoft/TypeScript/issues/37053#issuecomment-1355747946 (in which @RyanCavanaugh reiterates that the “linked suggestion doesn't really solve anything IMO”).

over in #52433, which requests support for treating libs as a union (not an intersection, as they are right now) in order to support type checking code that runs in multiple environments, there’s https://github.com/microsoft/TypeScript/issues/52433#issuecomment-1405570230, which again indicates a posture that is generally closed towards any of the proposed solutions (“The problem we've had here in the past is that a huge amount of code can be seen to be running in one environment by inspection, but not in a way that's susceptible to static analysis.”), but it does end with this:

> There's nothing today stopping someone from auto-genning variant DOM/webworker/etc libraries with every top-level declaration marked possibly-`undefined`. Real-world usage of such output would be good evidence that this kind of feature would be usable in practice.

that’s a suggestion for a user-land-based solution that would help with the isomorphic problem-space described in #52433, but would do nothing to help with the issue here as described by Ryan Cavanaugh as:

>  _transitive dependencies_ end up in your program even though they're immaterial to your particular use case

all of this leaves me with two questions:

1. what is the solution for this problem that someone could work on that has any indication of support from any core typescript team members?
2. has anyone tried to auto-gen variant DOM/webworker/etc libraries with every top-level declaration marked possibly-`undefined`? if no one has, i’d be happy to give it a go and try to see if it solves any problems, though as a library consumer, not a library author, i’m not sure if there’s an existing auto-gen tool i can use to do that or if the assumption is that whoever creates those libs would need to also create the tools needed to parse and transform the existing libs in the way suggested. what i really want is to do something like `import type * as DOMTypes from 'dom'; export type OptionalDOM = Partial<DOMTypes>;`, so that i could continue to rely on the libs and not have to maintain a fork, but 🤷.

**Comment by dominictobias** [comment]
Driving me nuts. JSX is becoming a more and more popular choice on the server, but as soon as a React project imports **anything** from the server, like a strong typing contract for the API, all types in React break because the non-React JSX redefines JSX globally

**Comment by HitkoDev** [comment]
@acusti What I got from this whole debate is that the "right" way of dealing with this issue would be for libraries to provide a separate `globals.d.ts` file, and for the developers to include it as `{ "types": ["library/globals"] }` only where they actually rely on particular global values.

However, doing it that way is discouraged by the fact that most users would view it as an inconvenience rather than a feature, as well as being a major change for existing libraries, many of which are no longer actively maintained in the first place. So other than doing it _the wrong way_, I don't think there's another practical solution to this issue.

**Comment by richardsimko** [comment]
It's absolutely wild that importing any library that happens to have `/// <reference types="node" />` as a part of their type defs will leak the Node types to my global scope and there is no setting to avoid this behavior. IMO this is a huge foot gun and a massive bug in TypeScript and goes against the very purpose of having a type check.

For example importing a type from a library to use in a shared API interface (Which then gets imported in the client side code) will leak NodeJS types to the client.

**Comment by arkthur** [comment]
Is it possible to get more clarity on what kind of information is still missing to make this issue to still have the "Awaiting more feedback" tag?

**Comment by repulsio** [comment]
`@types/node` leaking into my browser projects out of my control is killing my dev experience...

**Comment by MicahZoltu** [comment]
> `@types/node` leaking into my browser projects out of my control is killing my dev experience...

You can workaround the issue with something like this.  You will have to explicitly list any `@types` packages you add, and remove them if you remove a project, but it can at least protect you from Node types leaking into browser project.
```jsonc
"typeRoots": [ "./node_modules/@types" ],
// add any @types here, empty array instead of default to prevent @types/node from being picked up
"types": [],
```
