### ISSUE TITLE
null checks are ignored in "unknown" narrowing

### ISSUE THREAD

**Issue by OmgImAlexis** [microsoft/TypeScript#37658]
**TypeScript Version:**  3.8.3 Nightly playground

**Search Terms:**

**Code**

```ts
const func = (value: unknown) => {
    const results = [];

    // 1
    if (typeof value === 'object' && value !== null) {
        results.push(1); // (parameter) value: object
    }
    // 2
    if (value !== null && typeof value === 'object') {
        results.push(2); // (parameter) value: object | null
    }
    // 3
    if (typeof value === 'object') {
        if (value !== null) {
            results.push(3); // (parameter) value: object
        }
    }
    // 4
    if (value !== null) {
        if (typeof value === 'object') {
            results.push(4); // (parameter) value: object | null
        }
    }
    // 5
    results.push(5); // (parameter) value: unknown
  
    return results;
};

console.log(func({})); // [1, 2, 3, 4, 5]
console.log(func(null)); // [5]
```

**Expected behavior:**
2 and 4 shouldn't have `null` as expected type.

**Actual behavior:**
`null` checks are being ignored depending on the order they're in.

**Comment by nmain** [comment]
The core problem here is https://github.com/microsoft/TypeScript/issues/4196.  The compiler has no way to express a type of `Exclude<unknown, null>` so the null check coming first does nothing.

However it seems 2) might be fixable as https://github.com/microsoft/TypeScript/issues/36709 was fixed.

**Comment by RyanCavanaugh** [comment]
@nmain is correct. We don't have any mechanism to produce a useful narrowing for `unknown !== null`, and CFA is naturally order-dependent.

**Comment by OmgImAlexis** [comment]
It hasn’t been addressed if this has been fixed by https://github.com/microsoft/TypeScript/pull/37134 or not. Should this still be closed?

**Comment by LeonardDrs** [comment]
Hi, I was about to post the same issue until I stumbled upon this one.
I can confirm that this is [not fixed](https://www.typescriptlang.org/play?ts=4.1.3#code/GYVwdgxgLglg9mABDAzgZTgWwKZQBYxgDmAFMHHAFyLgDWYcA7mAJTUBGFANtgIZIBvAFABIGMEQkAhOTgtEwkSIBOuEMqTBeXFNgDcogL5DRAelOIUvHIkYx8Zi+MmzEAXg+IwILl3mLzRBU1DUQtHX1HRGNRZxIoAE8AB2w4CVcpTwByOHYAK2xoLP9RYKh1TW1dAxEYsQkyCgA6PF4UAHlmAAVlOBTlRJIs9l5lYv9EQJIk0etcbGV5WWpcguhEAB8vHy5S1XLQ8OqjEzKKxChlEEiY0EhYBGR0LFwCYgAhVEaqGjB6JlYHG4fEEsQaiRSaTCFEQmTciBy+UKUGKCj2IUqERqdTirg88O8vhKSn25yOkVqp1xzVaHW6vX6g2Go3GaJJGLCVQpdVJoUu1wMt3A0HgSFQGBw+EIRAAKgtvtQ6AxmGxEJw4Dx+Gy4hDUukYXCEatkajFGdDlzsVSGjIYRstrIWm1OmAen0FkyRmMWMTzZjjpTRLykPybkA).

I understand that the first null check does currently nothing considering the narrowing and CFA order.
Is that something that would be able to achieve with https://github.com/microsoft/TypeScript/pull/29317?

Cheers
