### ISSUE TITLE
TypeScript 4.1 Iteration Plan

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#40124]
This document outlines our focused tasks for TypeScript 4.1. Nothing is set in stone, but we will strive to complete them in a reasonable timeframe.

Date           |   Event
---------------|-------------------------
August 20th    | TypeScript 4.0 Release
September 11th | Create 4.1 Beta (4.1.0) Build for Testing
September 15th | **TypeScript 4.1 Beta Release**
October 30th   | Create 4.1 RC (4.1.1) Build for Testing
November 3rd   | **TypeScript 4.1 RC Release**
November 13th  | Create 4.1 Final (4.1.2) Build for Testing
November 17th  | **TypeScript 4.1 Final Release** 🚀

## Language Features

* [Recursive Conditional Types](https://github.com/microsoft/TypeScript/pull/40002)
* Investigate Pedantic Flags
    * [`undefined` in index signatures](https://github.com/microsoft/TypeScript/issues/13778)
    * [`--noImplicitOverride`](https://github.com/microsoft/TypeScript/issues/2000)
* Investigate Preventing [Global Conflicts](https://github.com/microsoft/TypeScript/issues/32273) with Strict Environment Configuration
* [Investigate Key Augmentations in Mapped Types](https://github.com/microsoft/TypeScript/issues/12754)
* [Investigate ESM Interop](https://nodejs.org/api/esm.html#esm_enabling)
* [`export * as default`](https://github.com/microsoft/TypeScript/issues/39769)
* [Investigate WASM imports](https://github.com/microsoft/TypeScript/pull/39784)
* [JSX Factory Updates](https://github.com/microsoft/TypeScript/issues/34547)
* [Investigate `///` Comments](https://github.com/microsoft/TypeScript/pull/39930)

## Editor Productivity

* [New Semantic Highlighting API](https://github.com/microsoft/TypeScript/issues/38435)
* [Enable running TSServer in a worker thread](https://github.com/microsoft/TypeScript/issues/39707)
* [Hierarchal Refactoring Triggers](https://github.com/microsoft/TypeScript/issues/35096)
* [Improve Refactoring Discoverability](https://github.com/microsoft/TypeScript/issues/37895)
* [JS Inference Improvements](https://github.com/microsoft/TypeScript/issues/40025)
* [Investigate Support for `@see` and `@link` Tags](https://github.com/microsoft/TypeScript/issues/35524)
* [ATA Updates](https://github.com/microsoft/TypeScript/issues/40123)

## Performance

* Anticipated bug fixes and [UX improvements](https://github.com/microsoft/TypeScript/issues/39035) for partial semantic mode
* [`tsc` Profiling Output Support](https://github.com/microsoft/TypeScript/pull/40063)
* [Investigate Slowdowns in Popular Libraries](https://github.com/microsoft/TypeScript/issues/34801)

## Infrastructure

* Improve Workflow for External Code Tests
* Breaking Change Detection Scripts

**Comment by Kingwl** [comment]
BTW: 
`undefined in index signatures` `--noImplicitOverride` referenced same issue.

**Comment by DanielRosenwasser** [comment]
Fixed, thanks!

**Comment by ifiokjr** [comment]
I want to give a huge shout out to the TypeScript team. You've just released an amazing 4.0.2 and you're already getting us excited for the next thing around the corner. As a burgeoning open-source developer it's inspiring, and you deserve all the success and praise.

I'm most excited about the potential introductions of `///` comments  and the `override` keyword.

**Comment by Kingwl** [comment]
@ifiokjr 
Hey. How about get a preview and perhaps sends some feedback for the override? 

You can see It here: https://github.com/microsoft/TypeScript/pull/39669#issuecomment-676526308

**Comment by Xample** [comment]
Hi, another missing feature I have been awaiting for a long time is the [typed errors](https://github.com/microsoft/TypeScript/issues/13219).

As I [wrote in a comment](https://github.com/microsoft/TypeScript/issues/13219#issuecomment-652873103) 

> This is the only feature I envy the java language

The issue is still labeled "Awaiting More Feedback", in my opinion there is not need to reinvent the wheel, if we can get some interest from the TS team I would with pleasure clarify possible use case scenario.

**Comment by ghiscoding** [comment]
Can someone add the Iteration link to the [Roadmap](https://github.com/Microsoft/TypeScript/wiki/Roadmap)? 
That would avoid me couple clicks each time I want to check the plan 😉  

Thank You.... TypeScript is getting more awesome every iteration 😃

**Comment by DanielRosenwasser** [comment]
@ghiscoding done!

**Comment by dbartholomae** [comment]
Would love to see some progress on nominal types (#202) for 4.1. I'm happy to help, but unsure how to do this. I posted some more details in #202 to keep this thread clean.

**Comment by DanielRosenwasser** [comment]
@typescript-bot create release-4.1

**Comment by DanielRosenwasser** [comment]
@typescript-bot sync release-4.1

**Comment by weswigham** [comment]
@typescript-bot sync release-4.1

**Comment by weswigham** [comment]
@typescript-bot sync release-4.1

**Comment by DanielRosenwasser** [comment]
@typescript-bot sync release-4.1

**Comment by xiaoxiangmoe** [comment]
When will TypeScript 4.1 Beta Release ?

**Comment by Bessonov** [comment]
@xiaoxiangmoe you can use nightly or in meanwhile:

> 4.1.0-beta 13 hours ago

See Versions from https://www.npmjs.com/package/typescript to get more information about builds.

**Comment by Skillz4Killz** [comment]
@DanielRosenwasser Hello 👋 sorry to bother you but I was hoping to request that future blog posts for this release the wording on the `--noUncheckedIndexedAccess` could be redone.

https://devblogs.microsoft.com/typescript/announcing-typescript-4-1-beta/#no-unchecked-indexed-access

- Using Pedantic in the blogpost goes against the discussions we've already had about not using pedantic.
![image](https://user-images.githubusercontent.com/23035000/94369436-ac05ab80-00b7-11eb-9ae5-ebb3c366f7e4.png)
 
![image](https://user-images.githubusercontent.com/23035000/94369110-d8202d00-00b5-11eb-9422-492414eea6e5.png)

There have been entire issues on this repo dedicated to picking a name that did not imply pedantic. Having this in the blogpost after all this is not really nice.

- The explanation of this property does not really do it justice in my opinion. 
Every other feature on the changelog "Use this immediately, will help fix stuff! It's amazing"
Index: "This causes too much noise and doesnt really fix much" 

For example, the post mentions nothing of how impactful this change is to array destructuring. Numerous issues have been created on this repo for this problem such as #38287 #40749 #36635 #37045 which shows that this is quite a useful change to many TS users.

The major downsides that have been seen for those that have tested this is only in older legacy code where people use for loops. A lot of more recent code will not be using for loops like this except when every millisecond of performance matters and so therefore the biggest issue of this config isn't even that big an issue for majority of relevant code.

The post mentions nothing of how this option has been shown already to be improving performance and preventing runtime bugs which cause hours of debugging because the typings will not show any errors so you are forced to go line by line to figure out some bug in production. IMO the blog post should be encouraging the use of this option not discouraging it such as mentioning that the slightly extra noise created by this option is WELL worth the benefits gained from it.

**Comment by DanielRosenwasser** [comment]
I'll reconsider how it's phrased in the 4.1 RC/Final blog posts - you might be right that the tone deserves more optimism. But I'll reiterate that the feature is currently (***currently***) not one that the core team can definitely recommend that **everyone** uses. While we're open to changing our minds about this, and while the feature might improve in functionality over time, we're being intentionally being cautious in our tone to set expectations.

**Comment by DanielRosenwasser** [comment]
@typescript-bot bump release-4.1

**Comment by DanielRosenwasser** [comment]
@typescript-bot sync release-4.1

**Comment by tchetwin** [comment]
I think I'm running into [this issue](https://github.com/microsoft/TypeScript/issues/41359), in our case it began with 4.1.0-dev.20201029 (my comment [here](https://github.com/microsoft/TypeScript/issues/41359#issuecomment-721383363)).

Prior to that all of our code was building ok with 4.1.0-beta.

**Comment by DanielRosenwasser** [comment]
You'll have to be more specific - that is just an automated test run.

**Comment by tchetwin** [comment]
I linked to my comment on that Issue which has playground links with a specific before and after example that fails in 4.1.0-dev.20201029 and succeeds in 4.1.0-dev.20201028.

**Comment by ExE-Boss** [comment]
[The **Breaking Changes** section](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1-beta/#breaking-changes) should probably include <https://github.com/microsoft/TypeScript/pull/38967>.

**Comment by Skillz4Killz** [comment]
Sad to see the wording on the post has not changed 😞

**Comment by ExE-Boss** [comment]
@Skillz4Killz
The last paragraph has been changed from:
> This flag can be handy for catching out-of-bounds errors, but might be noisy for a lot of code, so it is not automatically enabled by the `--strict` flag.

to:
> This flag can be handy for catching out-of-bounds errors, but it might be noisy for a lot of code, so it is not automatically enabled by the `--strict` flag; <ins>however, if this feature is interesting to you, you should feel free to try it and determine whether it makes sense for your team’s codebase!</ins>

**Comment by Skillz4Killz** [comment]
@ExE-Boss  That changes nothing of the tone and understanding of this property. 
![image](https://user-images.githubusercontent.com/23035000/98363494-0f5ef380-1ffd-11eb-8a24-0a5498e6d5eb.png)

**Comment by mprobst** [comment]
To add some data to this conversation, we tried 4.1 and `--noUncheckedIndexedAccess` on a substantial sized code base. We found that it broke [~15% of "targets"](https://github.com/microsoft/TypeScript/issues/41369#issuecomment-724791244), where a target has the granularity of typically a single or few UI component(s). These targets broke individually, i.e. 15% of targets had a compilation error in themselves, not just in some of their dependencies.

Our takeaway is that this flag might be interesting, but currently the signal/noise ratio (i.e. the number of genuine issues caught as opposed to false positives) does not warrant the effort it'd take to roll this out, nor the ongoing effort for programmers to handle this error.

**Comment by Skillz4Killz** [comment]
@mprobst That is some amazing info! 

Out of curiosity how much more info can you extrapolate from your use. For example, if I took a large-sized code base in non-strict TS and enabled the "strict" flag a lot of % of targets would break as well. That should not discourage users from being encouraged to be more type-safe? Breaking older code without this flag is expected, the main concern IMO is how many are actually false positives?

What was the signal/noise ratio? How was this calculated and determined whether each one is a signal or a noise?

**Comment by mprobst** [comment]
@Skillz4Killz I manually sampled some of the results. Among 10 randomly chosen targets, I found 10 false positives, i.e. the code was either obviously correct (e.g. access within for loop, guarded by length check, generally reasonable array operations, etc) or it was covered by a test and working as expected (such as getting element #3 on a page that in practice is guaranteed to have 3 elements on it). I'm sure there are positive positives, they might just be very hard to find amongst the large number of false positives.

The code repository this runs on is google3, see [here for some more background on the size and scale](https://cacm.acm.org/magazines/2016/7/204032-why-google-stores-billions-of-lines-of-code-in-a-single-repository/fulltext). Meaning we have a very large sample of code, and most of it is well tested and running in production (i.e. works in practice). The number of occurrences is difficult to compare with other checks given the prevalence of array indexing in code in general, but 15% of targets broken is at least two orders of magnitude more frequent than I'd expect for a high precision check.

**Comment by RyanCavanaugh** [comment]
@Skillz4Killz A couple points on this

First is that we want to manage expectations appropriately. For `noUncheckedIndexedAccess`, there are a lot of cases ("standard" C-style `for` loops, accesses explicitly guarded by `.length` checks, accesses immediately following a `push`, etc) that simply don't work as ergonomically as the rest of TypeScript. For codebases that are willing to write code in a way that doesn't encounter those limitations, this is obviously fine, but lots of existing code out there is filled with patterns for in-bounds access that TS will not recognize.

Second, your own willingness to do the work to turn this on in your codebase is admirable! The general upgrade philosophy of TypeScript, though, is that medium-to-large efforts like that should not be part of the "normal" upgrade process. This informs how we choose our default options and how we roll out new behaviors that might conflict with that philosophy.

We are not *discouraging* anyone from turning this on, we're just being honest about the limitations we think most people are likely to encounter. I would hope people would find that attitude laudable. The fact that we added the feature at all is a testament to the value we see in it!

**Comment by RyanCavanaugh** [comment]
@mprobst that's some great context. I'm currently sweating bullets on the `Promise` change (0.290%) being too disruptive 😅

**Comment by mprobst** [comment]
@RyanCavanaugh the Promise change is not so bad actually, we can fix that with automated machinery by inserting appropriate `as any` casts. The scary ones are the changes that cannot be automated. Also, it might help that this is the 25th Google-wide TS language upgrade we're doing (we skipped one minor version once, but otherwise have been tracking TS since 1.4).

**Comment by Skillz4Killz** [comment]
Very interesting points. I didn't think there would be that many false positives. Hmmm, that makes me think you guys are correct on the wording to set expectations. I will continue trying to advocate enabling this in my work but i 100% can understand now why it's worded as is now.

**Comment by DanielRosenwasser** [comment]
Thanks for understanding!

**Comment by DanielRosenwasser** [comment]
@typescript-bot bump release-4.1

**Comment by DanielRosenwasser** [comment]
Hey all, we're going to retarget to Thursday (11/19) just to ensure that everything is working as optimally as possible and documented.

**Comment by DanielRosenwasser** [comment]
@typescript-bot bump release-4.1

**Comment by DanielRosenwasser** [comment]
@typescript-bot bump release-4.0

**Comment by DanielRosenwasser** [comment]
🤦‍♂️

@typescript-bot bump release-4.1

**Comment by DanielRosenwasser** [comment]
@typescript-bot bump release-4.1
