### ISSUE TITLE
Angular CLI (8 & 9) generated app re-compiles when opening a different file in VS Code

### ISSUE THREAD

**Issue by vitale232** [microsoft/TypeScript#41483]
- VSCode Version: 1.50.0-insider (user setup)
- OS Version: Windows 10 Enterprise v1909 OS build 1836.1016

### Steps to Reproduce:

1. Create a new Angular 9 application using the Angular CLI. Follow the brief [Lazy Loading tutorial](https://angular.io/guide/lazy-loading-ngmodules#step-by-step) to generate an application with multiple "Feature Modules" that will be chunked.
2. Change the currently viewed file in VS code. The application recompiles without any changes to the source, and without any "save" operations in the project directory.

### Does this issue occur when all extensions are disabled?: Yes/No
When using the flag as instructed in this issues template (`code-insiders --disable-extensions`), no, the issue cannot be replicated. However, there are no third party extensions installed, and the issue exists without the --disable-extensions flag.

### More Info
Here is a gif with a basic Angular 9 application that shows the issue:

![recompile-no-extensions](https://user-images.githubusercontent.com/8504254/93511643-1fa5fc80-f8f1-11ea-841d-3c4188d0915f.gif)

This can be a major nuisance on a real application, as the recompile time is much slower and any data you input while testing is obviously lost. This issue has been reported in this repo previously, but the issues I was able to uncover were closed due to lack of replication or lack of response. Some other issues/StackOverflow posts state that system backups can present this issue. I've confirmed with my IT Department that my project is located in a directory that is _excluded_ from their automated backups.

In the small repro here, I must admit that I can only replicate this intermittently. The reason I chose the Lazy Loading example is the issue seems to be worse when switching between files in different feature modules in our actual apps, and I could not replicate it with the default `hello-angular` app.

This issue has been driving my teammates to use Web Storm, as it can really block a developer's productivity.

**Comment by mjbvz** [comment]
@sheetalkamat Have you seen any other reports of windows defender or some other security feature triggering recompiles?

**Comment by jgbpercy** [comment]
I don't have much to add, but I just want to say that I've also seen this issue regularly, also on Windows 10 with settings managed by IT dept.

**Comment by alan-agius4** [comment]
Hi all, from the Angular CLI side we did see this in the past and it always seemed to be related to software which caused file events to fire incorrectly.

A recompilation happens when a file change event is fired for a file which is a dependency of the current compilation. I also don't think that is cause by TypeScript, as seeing the above GIF it seems to also happen when you open an HTML file.

My 2 cents on this is:
- This issue is also reproducible by opening the file using nodepad.
- The live-protection is causing these events to be fired.

It would also be interesting to see if this issue effects only Webpack file watcher. Does the recompilation occur when using `npx tsc --watch -p tsconfig.app.json` instead of `ng serve`? **NB:** be sure to open a TypeScript file which is part of the compilation, example `main.ts`.

**Comment by captainkout** [comment]
I have confirmed that the project does NOT reload when files are opened in Notepad or WebStorm, project only reloads in VSCode as far as I can tell.

**Comment by captainkout** [comment]
I also verified that reload is NOT occuring when using  `npx tsc --watch -p tsconfig.app.json` and opening any files in the project, including main.ts.

**Comment by alan-agius4** [comment]
> I have confirmed that the project does NOT reload when files are opened in Notepad or WebStorm, project only reloads in VSCode as far as I can tell.
> 
> I verified that the 'watch' is still active by adding empty lines to a file in notepad and saving.

Interesting.

**Comment by alan-agius4** [comment]
> In VSCode, I also verified that reload is NOT occurring when using `npx tsc --watch -p tsconfig.app.json` and opening any files in the project, including main.ts.

By reload, I am assuming you meant recompilation.

**Comment by alan-agius4** [comment]
@captainkout, can you also try to update to the latest version of Angular CLI, maybe it was an upstream issues which was solved in the meantime.

You can update using:
```
ng update @angular/cli @angular/core
```

Unfortunately I am unable to replicate using the above steps and reproduction, although I must point out that I am not using Windows.

**Comment by vitale232** [comment]
Thanks for chiming in, everyone.

I'll dust off my old laptop and try to boot it into Windows this weekend. Perhaps I'll be able to replicate it there. FWIW, I've never seen this on Ubuntu.. only Windows.

**Comment by vitale232** [comment]
I was NOT able to reproduce this issue on a different Windows machine. I think it's a slightly different version of windows (home vs enterprise), but I'm far from a Windows expert. However, the machine did appear to have the "live virus scanning" enabled. So, it would seem there is something with our corporate laptops' configurations that is leading to this issue.

@alan-agius4 or anyone else - Is there a way to surface debug logs from WebPack (and whatever other tooling is involved with the file system events)?

**Comment by jgbpercy** [comment]
Hmm, so this is anecdotal, but I personally haven't seen this issue in the last few days... Maybe since I updated to 1.51 of VS Code, but that's a guess honestly. I'm pretty certain nothing Angular related was changed/updated on my setup, but obviously it could have been a Windows update or something else OS related.

Are people still seeing this on latest VS Code?

**Comment by vitale232** [comment]
@jgbpercy  That's fascinating... Count your blessings!

While using the company laptop, I'm still seeing this issue in our ng-10 projects with this version info:

```
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by vitale232** [comment]
We upgraded to Angular 11 last week, and I've been opting in to [Hot Module Replacement](https://webpack.js.org/guides/hot-module-replacement/). The issue that initiated this ticket is still present (the server makes updates when nothing has changed except the actively viewed file in VSCode), but it's heavily mitigated by HMR. Now when the app starts to recompile, instead of a full page reload, webpack "replaces" the module with the unchanged module and the page seems to be mostly unaffected. There may be a small hiccup in serving static assets while the server makes the non-existent changes.

I _do_ think there is a real issue here, but unfortunately, I don't feel like I'm in a position to present a fully replicable example. The only machine I can replicate this issue on is my company laptop with a looked down Windows Enterprise OS.

I guess I'll close this for now. Thanks for the great software!

**Comment by vitale232** [comment]
In case anyone finds this via search, the issue is still persisting for me on my windows box. BUT... I just set up WSL2, and problem solved!

For those willing and able, Windows Subsystem for Linux 2 will make `ng serve` stable again.

**Comment by sskasim** [comment]
I have a similar setup as @vitale232 on my company laptop and I have been facing this issue too since several months until today.

**Comment by TobiasBreuer** [comment]
Having the same issue here, also with all extensions disabled, ng is still recompiling over and over again when I switch to another file.
What I realized on my side, is that it seems to be related to git.

When I disable git from the preferences:
![image](https://user-images.githubusercontent.com/17617068/116676150-eb2a1100-a9a6-11eb-9a5c-7b025b6d7e28.png)
I can open, close or switch files without any undesired re-compilation happening (all other extensions are still enabled (e.g. Prettier, Angular-Language-Service etc.pp))

However, as soon as I re-enable git usage in VS-Code, the problem re-occurs and ng will start to re-compile again when switching files.

Don't know if it is related to the git version - I have the impression that it got worse since some weeks.
I'm currently using git-for-windows v2.30.0: 

```
Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.30.0.windows.1 from C:\Program Files\Git\cmd\git.exe
```

In the output of git in VS Code, the following is listed (I've shortened the paths manually) just before the re-compilation happens:

```
> git log --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z -n21 -- ...\server-worker\models\index.ts
> git show --textconv :Frontend/src/app/modules/server-worker/models/index.ts
> git ls-files --stage -- ...\server-worker\models\index.ts
> git cat-file -s 2a42bbdec8a86466a629fafdf9df0dc9136c0b9d
```

even-though these are all just reading operations, maybe this triggers any live-anti-virus or whatever in the OS to react?

**Comment by TobiasBreuer** [comment]
Just updated git-for-windows to latest version:
```
Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.31.1.windows.1 from C:\Program Files\Git\cmd\git.exe
```
Issue is still the same - for me, this means I'll disable git usage in VS-Code meanwhile and handle git either on cmder or in Visual Studio (which I use in parallel anyway for the WebAPI projects)...

**Comment by OhadC** [comment]
For anyone who is still having this issue, the fix for me was adding `--poll 2000` (2000 is the debounce ms to recompile) to your `ng serve` command.
so `ng serve` will be `ng serve --poll 2000`
Explanation: By default when no poll interval is set, Webpack will use native file system change detection. This change allows for setting the poll interval which will turn on polling.
