### ISSUE TITLE
tsconfig breaks TSC in VS 2015

### ISSUE THREAD

**Issue by glatzert** [Microsoft/TypeScript#4161]
Placing a tsconfig.json file inside of an ASP.NET vNext Project (beta6) will break tsc.
It will not produce any output.or overwrite files or whatever else.
Removing the tsconfig.json fixes the automatic compilation.

**Comment by mhegazy** [comment]
@paulvanbrenk can you take a look/provide a workaround here?

**Comment by paulvanbrenk** [comment]
only the following setup is supported at this time
````
/projectroot
    /wwwroot
    /scripts
        - tsconfig.json
        - ts files
````

For compile on save to work you need to enable Compile on save for files that are not part of a project, in tools/options/text editor/typescript/project

hope this helps

**Comment by mhegazy** [comment]
also to note, this is something we are still working on. TypeScript 1.5 release went out before ASP.Net release, so there are some missing support that we need to update in the next release.  sorry for the hassle.

**Comment by glatzert** [comment]
Well okay - the currently supported setup works - but orignially we wanted to go by one file per Module, which is not accomplishable without multiple tsconfig files, but with a buildstep - so we will use that as a Workaround.
Thanks

**Comment by paulvanbrenk** [comment]
Can you describe how you would like to setup your project to do 'one file per module', so we can take that into account when we improve the tsconfig experience in the near future.

**Comment by glatzert** [comment]
Well we'd like to use something like this:
```
 /projectroot
    /scripts
        /module1
            - sourceFile1.ts
            - sourceFile2.ts
            - sourceFile3.ts
            - tsconfig.json
        /module2
            - sourceFile4.ts
            - sourceFile5.ts
            - tsconfig.json
        /module3
            - sourceFile6.ts
            - sourceFile7.ts
            - tsconfig.json
```

Which should be build into this:
```
 /projectroot
    /wwwroot/js
        -Module1.js/map.js/min.js
        -Module2.js/map.js/min.js
        -Module3.js/map.js/min.js
```
Currently we can only make one js file per ts file or one js file with all the code. (The latter  `out: "../wwwroot/js/Output.js"´ seems not to work either.)

**Comment by paulvanbrenk** [comment]
@glatzert  thanks, this is good feedback. You should be able to enable this scenario right now using a grunt task, however I don't think there is any good information available right now (I couldn't find any just now). I'll try to add some information to the [ASP.NET + TypeScript wiki](https://github.com/microsoft/TypeScript/wiki/Using-TypeScript-With-ASP.NET-5) this week.

**Comment by ISkomorokh** [comment]
I'm trying to write simple spa using VS 2015 RTM, ASP.NET 5, TypeScript and Aurelia. I have tried the setup that was proposed here earlier, but didn't succeed.
```pre
/projectroot
    /wwwroot
    /scripts
        - tsconfig.json
        - ts files
```
I had to follow [these](http://www.marwijnchristiaans.com/?p=6) instructions to make everything work well. Hope I won't need to copy `*.d.ts` into `script\typings` folder in the nearest future.

Thanks

**Comment by swilson128** [comment]
Hi guys,

I'm building a standalone TypeScript app with a similar folder structure and output to glatzert above.  We need to build several .ts files in a folder to one combined .js file.  Is there any update on when this tsconfig issue will be resolved?  I see it was marked initially for 1.6 but is now pushed to 1.6.2, will it be released with 1.6.2?

Thanks,
Stephen

**Comment by paulvanbrenk** [comment]
It will work in 1.6 with the `tsconfig.json` file in the scripts folder, using this issue to track putting the `tsconfig.json` file in any directory.

**Comment by aaron-bond** [comment]
@paulvanbrenk so we will eventually be able to do the following?
```
/Common.Classes
   - tsconfig.json {out: "../Outputs/Common.Classes.js"}
   - Class1.ts
   - Class2.ts

/Common.Plugins
   - tsconfig.json {out: "../Outputs/Common.Plugins.js"}
   - Class3.ts
   - Class4.ts

/Outputs
   - Common.Classes.js
   - Common.Plugins.js
```

**Comment by paulvanbrenk** [comment]
@aaron-bond yes that's the goal

**Comment by aaron-bond** [comment]
@paulvanbrenk that's great news for us. We're planning a project for some time in the future. Is there a time frame on the outFile property being available?

**Comment by paulvanbrenk** [comment]
@aaron-bond the `outFile` property is in TS 1.6 Beta, it replaces `out`; the support for the multiple `tsconfig` files in a single Visual Studio project should be in the next release of TS for VS, but there are some open questions on how to handle ordering of compilations and how to show errors in VS.

**Comment by paulvanbrenk** [comment]
Closing this thread as the original issue with the tsconfig.json file in the root of the project is fixed in the final release of 1.6.

The support for multiple tsconfig.json files is tracked in issue #4714

**Comment by deni35** [comment]
**mhegazy**, how does TypeScript depend on Asp.Net? Because TS is front-end and Asp.net is back-end. I thought TypeScript is using only Node.js.

If tsconfig.json support is done, update this https://github.com/microsoft/TypeScript/wiki/Using-TypeScript-With-ASP.NET-5

I don't understand can I use tsconfig in HTML With TypeScript project type?
Is this issue specific to Asp.net project type or and for HTML with TypeScript?

**Comment by mhegazy** [comment]
> how does TypeScript depend on Asp.Net? Because TS is front-end and Asp.net is back-end. I thought TypeScript is using only Node.js

TypeScript VS plugin does not depend on niether ASP.net nor nodejs.

> I don't understand can I use tsconfig in HTML With TypeScript project type?

yes you can with TS 1.8/VS2015 update 2. Just add a tsconfig.json file to your project and it should just work.

> Is this issue specific to Asp.net project type or and for HTML with TypeScript?

nope. works in all project kinds.

> If tsconfig.json support is done, update this https://github.com/microsoft/TypeScript/wiki/Using-TypeScript-With-ASP.NET-5

looged issue https://github.com/Microsoft/TypeScript/issues/8402 to update the docs. for now here is a better tutorial for ASP.Net and TS: https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/quick-start/asp-net-core.md

**Comment by deni35** [comment]
> TypeScript 1.5 release went out before ASP.Net release, so there are some missing support that we need to update in the next release.
What did you mean then?

> TypeScript VS plugin does not depend on niether ASP.net nor nodejs.
TypeScript Compiler is running via node.js? So, it indirectly depend on node.js )

>  Just add a tsconfig.json file to your project and it should just work.
Ok. But I still don't understand how does msbuild and tsconfig cooperate.
If I set the same property in both files, what will be property applied? You shoud provide article about it.

**Comment by novakf** [comment]
I have found another workaround for this. If I have tsconfig.json file in project and I set Build Action to None for each and every file in the project the conflict disappears and tsconfig is used instead. Build actions such as Build/Clean seems to be working fine.

**Comment by novakf** [comment]
I am sorry, its bit more complicated, but I still have similar workaround.

a) set all .ts files build action to None
b) create a vsfix.ts file, keep it empty and keep Build Action on TypeScriptCompile
c) create post-build task: tsc -p "$(ProjectDir)tsconfig.json"

In this case build/clean including tslint and build error reporting works well
