### ISSUE TITLE
The inferred type of "X" cannot be named without a reference to "Y". This is likely not portable. A type annotation is necessary.

### ISSUE THREAD

**Issue by mistic** [microsoft/TypeScript#42873]
# Bug Report

### 🔎 Search Terms

inferred type cannot be named, symlink node_modules

### 🕗 Version & Regression Information

I'm verifying the problem on the `typescript@4.1.3`. I've not tried older versions but at least is also reproducible on the `@next` version as of today.

It is probably a regression or a corner case related with other issues opened and already closed like:

- https://github.com/microsoft/TypeScript/issues/30858
- https://github.com/microsoft/TypeScript/issues/28689
- https://github.com/microsoft/TypeScript/issues/2338
- https://github.com/microsoft/TypeScript/issues/29221

### ⏯ Playground Link

[Link for a repo where the problem is being reproduced](https://github.com/mistic/reproduce-typescript-problem-when-symlinking-node_modules)

> NOTE: Just clone the repo and run `yarn tsc`

### 💻 Code

All the relevant code can be found at https://github.com/mistic/reproduce-typescript-problem-when-symlinking-node_modules

It is just reproducing a similar setup that I had on other project that was generating the problem:

- node_modules are a symlink to another location that is not a direct parent of the symlinked node_modules
- we are using types in the compilation from a library where those types are just exported from other one, like for example `withRouter` within `react-router-dom` that is just a plain export from the same type on `react-router`.

### 🙁 Actual behavior

I got the following error:

```
error TS2742: The inferred type of 'Nav' cannot be named without a reference to '../../deps/node_modules/@types/react-router'. This is likely not portable. A type annotation is necessary.

8 export const Nav = withRouter(({ history }: NavProps) => {
               ~~~


Found 1 error.
```
### 🙂 Expected behavior

I was expecting no error at all and that the typescript compiler was just able to find all the respective modules. I've tried everything that I thought was related like enabled the `preserveSymlinks`. The only thing that stops the error is importing the `withRouter` type directly from `react-router` and not from `react-router-dom` but that doesn't make very sense because I actually want to use the `react-router-dom` on a couple of places.

\cc @weswigham @sheetalkamat @andrewbranch because I saw you previously worked to try to solve similar issues.

**Comment by weswigham** [comment]
Hm, it's a bit awkward in your case, since we _technically_ never directly discover that `react-router` is directly visible from your project folder (our symlink discovery is a bit heuristic based, so we only find them in paths we had to resolve a symlink across to access). If you had a `react-router` import somewhere in the file already, we'd know we have a lookup available... Hm. @RyanCavanaugh today we don't use a `package.json` for anything within a TS project, however with the recent changes to node resolution, we really should start considering it (so we can resolve package self names and `"imports"` maps) - as part of that, we could maybe consider using the `dependencies` manifest as a list of safe-to-access modules, like how we already use it for autoimports in the language server.

**Comment by mistic** [comment]
@weswigham Thanks for looking into the issue. What you wrote makes sense in my head as an explanation about why it is this bug happening. Let me know if I can be useful in any other way to move forward with this one as I really hope we can fix it!

**Comment by paynecodes** [comment]
I've got a repro which may help with the fix available here: [paynecodes/ts-repro-type-annotation-require-symlinks](https://github.com/paynecodes/ts-repro-type-annotation-require-symlinks). I don't want to hijack this issue if it's the wrong place, so let me know if a new issue is desirable. 

The Readme lists [references to similar issues](https://github.com/paynecodes/ts-repro-type-annotation-require-symlinks#references) I was able to dig up.

**Comment by btakita** [comment]
I have a set of npm packages where "types" points to a *.ts (not a *.d.ts) file. Reason being I can directly jump to the implementation with the IDE. The issue I'm running into is the following:

An npm package `B` that depends on another npm package `A`. A factory function `fn_` that returns a custom type is defined in pkg `A`. pkg `B` has `export const obj = obj_()`. Typescript compilation is successful. When another package `C` imports the `obj` from pkg `B`, `The inferred type of "obj" cannot be named without a reference to "path/to/pkg/A". This is likely not portable. A type annotation is necessary.`

This cannot happen. There needs to be a setting in `tsconfig.json` for the TS compiler to make pkg `B` fail compilation unless `const obj = obj_()` has a type annotation.

**Comment by weswigham** [comment]
>  At the very least, it would be useful to have a setting in tsconfig.json for the TS compiler to make pkg B fail compilation unless const obj = obj_() has a type annotation. 

There is one. `declaration: true`.

**Comment by btakita** [comment]
Other than not being able to jump to the Typescript source, the other issue with *.d.ts is when there are compile targets not supported by Typescript. Here is why:

To support both *.ts & *.d.ts files, the "out" "" `dist` directory 

For example a *.svelte component.

**Comment by btakita** [comment]
My understanding of `declaration: true` is that a `*.d.ts` file is created. It would be great to navigate directly to the `*.ts` source.

To support both *.ts & *.d.ts files in an npm package, something like `"declarationDir": "dist"` is necessary, otherwise, `*.ts*` files will be imported due to import precedence.

Another minor issue that I have to account for is with single file components which are compiled separate from Typescript. For example a svelte or vue component. These components will need to be copied over to the `dist` directory during `npm run build`, since npm does not support links within packages.

These are both minor but annoying issues.

**Comment by weswigham** [comment]
> My understanding of declaration: true is that a *.d.ts file is created. It would be great to navigate directly to the *.ts source.

Also set `declarationMap: true`.

**Comment by nwaughachukwuma** [comment]
Check if this works for you: https://github.com/microsoft/TypeScript/issues/29808#issuecomment-540292885

**Comment by mistic** [comment]
@weswigham @btakita not related with that initial issue but with your last discussion: `declarationMap` has also a buggy behaviour when used along sourceRoot (which is vital in some cases) https://github.com/microsoft/TypeScript/issues/31873 we are still waiting for a solution on that other issue.

**Comment by riordanpawley** [comment]
> Check if this works for you: [#29808 (comment)](https://github.com/microsoft/TypeScript/issues/29808#issuecomment-540292885)

doesn't help in my case. yarn workspaces monorepo setup with 
monorepo/pkg1 depending on monorepo/pkg2 & node_modules/pkg1
monorepo/pkg2 depending on node_modules/pkg1
Using same version of external/pkg1

**Comment by dustinlacewell** [comment]
I get this issue in a Rush monorepo where a project depends on `cmd-ts`.

**Comment by paynecodes** [comment]
I get this issue throughout many scenarios when using a Rush monorepo. Rush, by default, uses pnpm (pnpm workspaces is recommended). I haven't been able to track down the root cause, but I have scoured this issue tracker and subscribed to many topics hoping someone squashes this.

**Comment by 3cL1p5e7** [comment]
In my case:
When I use `declaration: true` and `yarn` as package manager -> got same error `cannot be named without a reference to 'styled-components/node_modules/@types/react`
After researching I found mismatch versions of `@types/react` for my repo and dependency `styled-components/node_modules/@types/react`

If run `yarn install --flat`, manually fill subpackage resolutions and run `yarn build` - problem is disappear

@InsOpDe `pnpm` also installs flat dependencies for monorepo with resolutions and you avoided my problem :)

**Comment by LiChangyi** [comment]
我已经收到了你的邮件。                                              ---------李昌义

**Comment by imcuttle** [comment]
In my case, add `preserveSymlinks` for resolve it
```json
{
  "compilerOptions": {
    "preserveSymlinks": true
  }
}
```

**Comment by LiChangyi** [comment]
我已经收到了你的邮件。                                              ---------李昌义

**Comment by zhyd1997** [comment]
@mistic 
try this:
add below code into this file: https://github.com/mistic/reproduce-typescript-problem-when-symlinking-node_modules/blob/main/project/tsconfig.json
```json
{
 "paths": {
   "@types/react-router": ["../../deps/node_modules"]
 },
}
```
it works!

**Comment by OoDeLally** [comment]
> In my case, add `preserveSymlinks` for resolve it
> 
> ```json
> {
>   "compilerOptions": {
>     "preserveSymlinks": true
>   }
> }
> ```

This solved it for me too, but why ? :thinking:

**Comment by andre-byrne** [comment]
Is there any way to designate parts of your code where this error is ignored? I'm getting this error, but in a part of my code that will never be exported for an end user (in private code, I mean).

**Comment by tstordyallison** [comment]
FWIW, I'm getting this when compiling https://github.com/facebook/flipper on Windows, where I have my code on drive ("I:") that is actually just symlinked (or whatever that is on Windows) to a directory on the "C:" drive. 

Running the compile from the actual "C:" location makes this error go away. Strange.

Using ``preserveSymlinks`` didn't make any difference for me.

**Comment by nemosmithasf** [comment]
For my case, I've found the following:

It only occurs when `"declaration": true` (no idea why however)

You can work around it by either:
1. Using `paths:{}` in `compilerOptions`
2. Deleting the problematic package from the `node_modules` folder of the symlink'd location
3. Publishing and install via NPM

**Comment by zkindest** [comment]
I removed `"declaration": true` , `"preserveSymlinks": true" `  and restart ts server

**Comment by vjpr** [comment]
I'm using pnpm and I made sure that I only had one version of `react-query` (in my case) across the entire codebase and it started working.

**Comment by wmzy** [comment]
I use [pnpm.overrides](https://pnpm.io/zh/package_json#pnpmoverrides) remove the duplicate dependencies and resolved this problem.

**Comment by vtereshyn** [comment]
"preserveSymlinks": true doesn't resolve all errors that I have. I also use `pnpm` and `typescript` together. Previously I used yarn and typescript and everything was fine.

Now, I have The inferred type of 'someVar' cannot be named without a reference to `'@pnpm-test/core-config/node_modules/yup/lib/string'.` This is likely not portable. A type annotation is necessary. and have no idea how to resolve that.

This appears if I set
```
"baseUrl": "./",
"paths": {
            "*": [
                "node_modules/*/"
            ]
        }
```

If I remove that, I also have the same issue but in other places.

The way to fix this exact problem described above was setting path to exact module (`yup` in my case), but then I still get other similar errors. That's super frustrating. 

I also set `declaration: false` for testing purposes but had no luck having it working.

**Comment by jsheely** [comment]
I was able to setup my repository so that it works with PNPM and NPM for installation in a monorepo workspace. I've found that this bug happens with PNPM but goes away with NPM

root
- packages
- apps


Appears to be a bug in dependency resolution. Appears to be related to how PNPM does symbolic folder links. This specifically happens when I expose a type from a child dependency. 

As long as all the types in the sub module are internal to that module it works fine. But if I reference a type from a sub/sub module and then build it will fail

For science I've also tried `pnpm i --shamefully-hoist` and it fails the same. 

None of the band aides mentioned above have seemed to resolve it for me using PNPM. 

- I've tried setting the  `preserveSymlinks` to true or false as others have suggested.
- My configuration already has `baseUrl: "."`
- Setting paths in `tsconfig.json`

Obviously disable `declaration` resolves the build. But the whole point is to create the `index.d.ts` declaration file that is blowing up

It fails consistently in all forms:
- VS Code Intellisense 
- `tsc index.ts --declaration --emitDeclarationOnly --allowSyntheticDefaultImports --outfile dist/index.d.ts`
- And using [Rollup](https://rollupjs.org/guide/en/#quick-start) bundler with the [rollup-plugin-dts](https://github.com/Swatinem/rollup-plugin-dts)

**Comment by tbergquist-godaddy** [comment]
I managed to get this working. The steps would be to install all troublesome node_modules in the root package.json, then add this (in my case) to tsconfig.json at the root 

```js
"paths": {
      "react": ["node_modules/@types/react"], // fair I am using this
      "react-query": ["node_modules/react-query"], // fair I am using this
      "csstype": ["node_modules/csstype"] // this is causing issues from within react using CSSProperties
    }
```

And this makes sense due to the nature of pnpm, it installs the actual files into `node_modules/.pnpm/<package>@<version>/node_modules`, then symlinks this into each workspace. You cannot guess this path, hence installing the packages into the root package.json will have them symlinked into the node_modules at the root, and you can reference them through `paths`.

I am not sure if this is a `typescript` issue or a `pnpm` issue, but I do think having to go through those steps is sub-optimal 😞

**Comment by jsheely** [comment]
@tbergquist-godaddy Not sure I understand. In my setup I'm referencing a package (A) within my mono repo into another package (B) in the same folder. 

(A) References a third party dependency that is the one being referenced as an error in (B) when I import A and use it

In my case PNPM installs a symbolic link of (A) into (B) node_modules. (A) then contains a node_modules symbol link to the third party package

But as far as TSC should be concerned this is standard dependency hierarchy and it should be able to find all the typings.

**Comment by tbergquist-godaddy** [comment]
Well, from the error I get `The inferred type of 'useSaveLanguage' cannot be named without a reference to 'packages/whitelabel/node_modules/react-query/types`. And this error is coming from `packages/language/...`.  which gets its types from `packages/language/node_modules/react-query/types`. 

Both of these might be symlinked to the same type, but I take it that tsc doesn't follow symlinks and see the paths as different path and then types.

**Comment by jsheely** [comment]
@tbergquist-godaddy Oh that's interesting that yours references the folder path fully. Mine references the module name then path

`The inferred type of 'Ethereum' cannot be named without a reference to '@decentology/hyperverse-evm/node_modules/@rainbow-me/rainbowkit'. This is likely not portable. A type annotation is necessary.`

It's frustrating that this problem goes away when I use `npm install` beause while I don't get this error I have other issues that require that I use PNPM. So it leads me to believe that it's just a setting away in PNPM to resolve the error

**Comment by jsheely** [comment]
Upon further trial and error. I can confirm that setting the path in `tsconfig.json` does in fact work

However I'm not sure I understand why

Here is how I fixed it:

I created a `.npmrc` in the package (B) that was having the problem and set. Which is nice because I can localize what needs hoisted per package
```
public-hoist-pattern[]=*@rainbow-me*
public-hoist-pattern[]=*@ethersproject*
```
Which were the two projects that had errors with the **The inteferred type....**

I then ran `pnpm i` to install the modules. This lifted thw two packages into the root mono repo node_modules folder

I then went back to package (B) and configured the `tsconfig.json` as others have suggested to point to that path
```
public-hoist-pattern[]=*@rainbow-me*
public-hoist-pattern[]=*@ethersproject*
```

No more error. Yay!

So it's wroth noting that the symbolic link path originally would have been nested like 
```
node_modules/@decentology/hyperverse-evm/node_modules/@rainbow-me/rainbowkit
```

But when setting that nested path in my trial and error in the tsconfig.compilerOptions.path it fails to resolve the typings. But hosting it to the top resolves the problem. I assume the nested path would be the default path it would be using :shrug:

**Comment by tbergquist-godaddy** [comment]
Yeah, using `public-hoist-pattern` will also work, since it essentially does the same as adding it to your package.json folder, it will symlink it to the root `node_modules` of your workspace. 

It might be the preferred approach since you don't have to stick dependencies you are not directly depending on in your package.json file.

**Comment by jgoux** [comment]
I have this error with `@trpc/server` in a monorepo, using `yarn@3.2.1`.

I tried all the solutions in this issue and none worked. 😭 

I've made an issue on `trpc` repo with a repro : https://github.com/trpc/trpc/issues/1945

**Comment by DrJume** [comment]
In a Vue 3 app I commented out `"composite": true` under `compilerOptions`, because it sets `declaration: true`

**Comment by DrJume** [comment]
> > In a Vue 3 app I commented out `"composite": true` under `compilerOptions`, because it sets `declaration: true`
> 
> this will break your composite build.

Thank you for the notice. But what exactly is a composite build?

**Comment by vtereshyn** [comment]
> > > In a Vue 3 app I commented out `"composite": true` under `compilerOptions`, because it sets `declaration: true`
> > 
> > 
> > this will break your composite build.
> 
> Thank you for the notice. But what exactly is a composite build?


It allows you to skip the build process if your project has been already built.

```
The composite option enforces certain constraints which make it possible for build tools (including TypeScript itself, under --build mode) to quickly determine if a project has been built yet.
```

**Comment by DrJume** [comment]
> > > > In a Vue 3 app I commented out `"composite": true` under `compilerOptions`, because it sets `declaration: true`
> > > 
> > > 
> > > this will break your composite build.
> > 
> > 
> > Thank you for the notice. But what exactly is a composite build?
> 
> It allows you to skip the build process if your project has been already built.
> 
> ```
> The composite option enforces certain constraints which make it possible for build tools (including TypeScript itself, under --build mode) to quickly determine if a project has been built yet.
> ```
> 
> https://www.typescriptlang.org/tsconfig#composite

Thank you. It seems the option `"composite": true` is only present in the generated Vue 3 app boilerplate if `vitest` is used. 

See: https://github.com/vuejs/create-vue-templates

It isn't included in the `tsconfig.json` in a regular typescript setup. I don't think it will cause problems as it seems to be only recommended with vitest.

**Comment by dexy58** [comment]
`The inferred type of 'authSlice' cannot be named without a reference to '.pnpm/immer@9.0.14/node_modules/immer/dist/internal'. This is likely not portable. A type annotation is necessary.`

This is what I get. I'm using pnpm, t ypescript and monorepo. To be precise, I'm using this:
https://github.com/NiGhTTraX/ts-monorepo

`authSlice` is actually `createSlice`, and `createSlice` is imported from `@reduxjs/toolkit`. I have read the entire thread and setting the `rootUrl = "."` didnt work.

**Comment by atsikov** [comment]
I made another small repo, based on rush and pnpm. It consists of two packages, and declarations are generated for both with `rush build:dts`, similar to what I have in a bigger project.

https://github.com/atsikov/ts-not-portable-error

Running the command throws an error for the second package
```
src/index.ts(3,14): error TS2742: The inferred type of 'useRunMutation' cannot be named without a reference to '../../common/node_modules/react-query/types'. This is likely not portable. A type annotation is necessary.
```

Both packages use `react-query` as a dependency, however for the `common` it is a peer (added to dev as well), as this package is not supposed to be used on its own. Generated declarations for `common` contain `import('react-query').{SomeType}` and it is the reason for "cannot be named" error.
I would expect TS to try to resolve `react-query` relatively to both definitions package (where the dependency is not installed because of being a peer) and to the hosting package (where the dependency exists). It looks like TS only tries to perform a former resolution and fails to do so.

This was probably already mentioned somewhere, but I didn't find a clear explanation. It is some design limitation, or was it done on purpose, or just something that was not considered?

**Comment by joeljeske** [comment]
This related issue #37960 proposes a new option in tsconfig to bypass this compile time check. This new options would be  useful for incremental builds, where the declaration files are not shipped as artifacts (e.g. monorepo, workspaces, etc...). 

That issue includes [a patch](https://github.com/microsoft/TypeScript/files/4476155/typescript%2B3.7.3.patch.txt) that could be applied to "typescript". I'd be interested if it fixes the issues described here.

**Comment by atablash** [comment]
> That issue includes [a patch](https://github.com/microsoft/TypeScript/files/4476155/typescript%2B3.7.3.patch.txt) that could be applied to "typescript". I'd be interested if it fixes the issues described here.

Didn't work for me 😭

**Comment by matthewlilley** [comment]
Are you able to provide some kind of update regarding this issue? 

This issue is encouraging bad behaviors. I'm seeing library maintainers exporting internals just to deal with this, and projects being forced to ignore typescript errors globally. This isn't good at all...

**Comment by chandrumani** [comment]
In `tsconfig.json` i removed `"experimentalDecorators": true,` and i don't this build error anymore

**Comment by jonlu** [comment]
Since this has to do with hoisting, switching the function declarations from `const` to `function` resolved this for me. I encountered this when exporting the configurations for my redux store


**Before:** 
> The inferred type of 'setupStore' cannot be named without a reference to 'XXX'. This is likely not portable. A type annotation is necessary.
```
export const setupStore = (preloadedState?: PreloadedState<RootState>) => {
  return configureStore({...});
}
```

**After:** 
(no errors)
```
export function setupStore (preloadedState?: PreloadedState<RootState>) {
  return configureStore({...});
}
```

**Comment by suleyman-tekin** [comment]
I managed to fix this by adding `"declaration": false` to `compilerOptions` in `tsconfig.json` for my package, adding it here in case it helps someone else.

**Comment by ekkolon** [comment]
There is a related issue (#29808) as implicitly pointed out by @nwaughachukwuma in [his comment](https://github.com/microsoft/TypeScript/issues/42873#issuecomment-884850842).
I solved it after following [@akash-rajput\'s](https://github.com/microsoft/TypeScript/issues/29808#issuecomment-557498277) answer within the same thread.

_To quote_: 
> Happens when we have conflicting versions of a package installed. A temporary solution would be to remove the package mentioned from peer dependencies of the plugin giving the error.
> 
> Or install the exact version of common dependency

In my case, I had linked a local NPM package with peer dependency \@nestjs/common\@^9.0.7 to a monorepo that had \@nestjs/common\@^8.0.0 installed.

I'm using `typescript@4.7.2`.

**Comment by PabloRosales** [comment]
> In my case, add `preserveSymlinks` for resolve it
> 
> ```json
> {
>   "compilerOptions": {
>     "preserveSymlinks": true
>   }
> }
> ```

This worked for me.

**Note**: *I had to restart my TypeScript Server for this to have an effect*

**Comment by GiancarlosIO** [comment]
thanks @PabloRosales, that worked for me 😄 
Just one question, do you know what side effects we can have in the typecheck if we enable that? 🤔 It's safe?

**Comment by PabloRosales** [comment]
@GiancarlosIO I had this problem when using `pnpm`, switching to `npm` actually solved it for me without needing to use this anymore. The option looks safe if you need it: [docs](https://www.typescriptlang.org/tsconfig#preserveSymlinks) didn't experience any issue on my side.

**Comment by dsngo** [comment]
@Nikola-Milovic my solution is disable the composite in tsconfig.json
```json
{
  "compilerOptions": {
   // ...
    "composite": false,
  }
}
```

**Comment by shellscape** [comment]
This is driving me absolutely bonkers in a pnpm monorepo.

**Comment by rubnogueira** [comment]
> This is driving me absolutely bonkers in a pnpm monorepo. Seems similar to #47663

@shellscape Did you find any solution for this?

**Comment by kicks321** [comment]
In two cases within my monorepo, I was using pnpm.  This was not symlinking the libraries I needed properly.

I had to manually install the inferred packages separately to handle this that we're throwing the type errors.

**Comment by skycrazyk** [comment]
I managed to fix this by removing "node_modules" from "exclude" in tsconfig.json

**Comment by spamshaker** [comment]
same problem here
| pkg manager | tsconfig.json <br/> `declaration` flag  | does it work? | 
| :-| :-: | :- |
| pnpm 7 | true | NO |
| pnpm 7 | false | YES |
| pnpm 8 | false | YES |
| pnpm 8 | true | YES |

**Comment by matthewjh** [comment]
Using `"preserveSymlinks": true` with pnpm is generally not safe, because then tsc will treat different symlinks to the same module as different modules altogether.

**Comment by bryantobing12** [comment]
what should we do then @matthewjh  ?

**Comment by Dealerpriest** [comment]
I have the same issue using pnpm. Any ideas of a "correct" way to address the error if preserveSymlinks is off the table?

**Comment by igortas** [comment]
I've faced today this error in `nx monorepo` with `pnpm`, while playing and experimenting setting `vite-node-plugin` as node server, and started overuse different compiler options in the root `tsconfig.base.json` file. I've realized that setting "composite" key to true, started gives me that error.

**Comment by Lionad-Morotar** [comment]
Im using pnpm and had a similiar problem too and I resolve this by setting "shamefully-hoist=true" in ".npmrc"

**Comment by matthew-dean** [comment]
For me, the main problem is I cannot ignore this problem with `@ts-ignore`. Why??

**Comment by electrovir** [comment]
I don't see it posted in here yet so this is what solved it for me: https://github.com/microsoft/TypeScript/issues/47663#issuecomment-1270716220

Add `import type {} from "Y";` where `Y` is the package that TS is saying you need a reference to.

**Comment by Gorthog** [comment]
I had the same problem while using pnpm. The error occurred due pnpm installing multiple copies of the same npm package. Here is what worked for me:
1. Remove the offending npm package from each `package` and moving it into dependencyPeer list.
2. Add the package only for the `app`

Then pnpm did not install multiple versions of the same npm package and that finally fixed this annoying typescript error

**Comment by marcelorl** [comment]
My case was:

Been working with pnpm workspace.  My structure:

package.json
packages
 - users
  - package.json
 - wallet
  - package.json

The 3 package.json have the same package installed with a different version. Uninstalled the package from the parent package.json the problem was gone.

**Comment by backendsuraj** [comment]
In case you're using `pnpm` as package manager in a `monorepo` you can get this error because of the default behavior of `pnpm` to symlink the dependancies when we do `pnpm install`.

Simple fix is to tell `pnpm` to create flat `node_modules` without symlinks.

Create a `.npmrc` file in the root folder of your project & add the following.
```
auto-install-peers = true
node-linker = hoisted
```
Run `pnpm install`

Read more about [node-linker](https://pnpm.io/npmrc#node-linker)

**I'm was using `turborepo` with `pnpm` as the package manager.

**Comment by orenmizr** [comment]
the hoisting solution - doesn't it effect the advantages of pnpm ? isn't there another way to work with symlinks ?

**Comment by InsaneNaman** [comment]
> In case you're using `pnpm` as package manager in a `monorepo` you can get this error because of the default behavior of `pnpm` to symlink the dependancies when we do `pnpm install`. TypeScript act weird when symlinks are used in `node_modules` for some reason.
> 
> Simple fix is to tell `pnpm` to create flat `node_modules` without symlinks.
> 
> Create a `.npmrc` file in the root folder of your project & add the following.
> 
> ```
> auto-install-peers = true
> node-linker = hoisted
> ```
> 
> Run `pnpm install`
> 
> Read more about [node-linker](https://pnpm.io/npmrc#node-linker)
> 
> **I was using `turborepo` with `pnpm` as the package manager.

Facing this same issue while using Mantine with turborepo.

**Comment by orenmizr** [comment]
**pnpm** + **turbo** + **typescript** -> trying to avoid hoisting.
typescript errors out with tsup in the bundling phase.

❌ workaround -  import type {} from 'Y'  
❌ workaround -  declaration option in tsconfig'  
❌ workaround - baseUrl and linking to packages

i have a massive project with crazy amount of packages... it is very hard for me to manually work around this issue. 

_if anyone got more workarounds, i'd be happy to test them out._ i am the last attempt before hoisting everything and waiting for an official fix.

**Comment by CdTgr** [comment]
Not sure if this could be helpful, but I had a similar case when using mongoose where one of my services had an `update` function that was returning the result from `mongoose.updateOne`. But changing it to `mongoose.findByIdAndUpdate` fixed the issue.
So the cause of the error in my case was the incompatible function signature vs the returned value ( the mongoose update ).

### Example
Initial function:
```
async update(x: string, y: Y) => await mongoose.myModel.updateOne({ _id: x }, { y })
```
Updated to:
```
async update(x: string, y: Y) => await mongoose.myModel.findByIdAndUpdate(x, { y }, { new: true })
```

### What changed?

The first one had a return type of `UpdateResult`. where the second one has a `Document` as the return type.
As per the definition, the update ( deprecated in the newer version ) function of mongoose was having a return type `UpdateResult`, but the parameters are not like what I had in my function.

So as per the types, they were not matched.

**Comment by dmaklygin** [comment]
For me, the `"preserveSymlinks": true` in tsconfig.json helped.

**Comment by orenmizr** [comment]
i have already hoisted.  :/ but perhaps this plugin can help - https://github.com/zheeeng/vite-plugin-shared-modules

**Comment by AndreaPontrandolfo** [comment]
Also facing this issue in a pnpm + turborepo + typescript project.
The fun fact is, if i manually give it the type it works.
What i mean is:

```typescript
import { myObj } from 'package'

const newObj = myObj     // ---> error
```

```typescript
import { myObj } from 'package'

const newObj: typeof myObj = myObj   // ---> everything works
```

This is definitely a bug as this cannot possibly be an expected behaviour.

**Comment by atellmer** [comment]
I also faced this problem. I think the point is that the typescript, due to a bug, cannot correctly resolve complex types or types scattered over many directories. To get rid of the error, you need to manually infer the type of the problematic element through the `as` keyword.
Like this:

```tsx
const AbsoluteLayout = forwardRef<AbsoluteLayoutProps, AbsoluteLayoutRef>(
  createComponent((props, ref) => absoluteLayout({ ref, ...props })),
) as Component<AbsoluteLayoutProps, AbsoluteLayoutRef>; //<---- Manual output type
```

**Comment by nouman2075** [comment]
> I've faced today this error in `nx monorepo` with `pnpm`, while playing and experimenting setting `vite-plugin-node` as node server, and started overuse different compiler options in the root `tsconfig.base.json` file. I've realized that setting `composite` key to `true`, started giving me that error, or in my case more specific:
> 
> `The inferred type of 'apiGateway' cannot be named without a reference to '.pnpm/@types+express-serve-static-core@4.17.31/node_modules/@types/express-serve-static-core'. This is likely not portable. A type annotation is necessary.`
> 
> @Dealerpriest not sure if u already tried the `composite` key set to `false` or removing it.

Removing `composite` key or value to `false` works for me

**Comment by ricardosc12** [comment]
I faced this problem using _turborepo_ + _typescript_ + _stitches_

Error:

```
web:build: ../library/ui/src/theme/stitches.config.tsx:3:16
web:build: Type error: The inferred type of 'styled' cannot be named without a reference to '../../../../web/node_modules/@types/react'. This is likely not portable. A type annotation is necessary.
web:build:
web:build:   1 | import { createStitches } from '@stitches/react';
web:build:   2 |
web:build: > 3 | export const { styled, getCssText } = createStitches({
web:build:     |                ^
web:build:   4 |   theme: {
web:build:   5 |     fonts: {
web:build:   6 |       system: 'system-ui',
```

Solution:

```
import { createStitches } from '@stitches/react';

export const { styled, getCssText } = createStitches({
     ...
}) as any;  <-- here - Type any
```

**Comment by justinfagnani** [comment]
I hit this error tryout out npm 9.4's new `install-strategy=linked` in a monorepo using npm workspaces.

One interesting thing about this is that importing from a monorepo module that re-exports causes the error:

```ts
import {BaseComponent, html} from 'my-base-component';

export class MyElement extends BaseComponent {
  render() { return html`...`; }
  // ^ error on the return type of render()
}
```

but importing from the original library fixes the error:
```ts
import {BaseComponent} from 'my-base-component';
import {html} from 'lit';

export class MyElement extends BaseComponent {
  render() { return html`...`; }
  // ^ no error
}
```

**Comment by vladfaust** [comment]
I got the problem of inferring type of `t` in 

```ts
const t = initTRPC.context<Context>().create();
```

Setting `"moduleResolution"` to `"node"` instead of `"node16"` in `tsconfig.json` worked for me.

**Comment by ivancuric** [comment]
Same issue here. What's interesting is that VScode's higlighting and `tsc`'s output don't necessarily match. And removing `node_modules` and reinstalling can break it even if it gets fixed at one point.

**Comment by kiastorm** [comment]
I'm getting this when re-exporting a dependency in a UI library used by two other consumers

```
example
├── app-1
├── app-2
└── ui-library
```

`ui-library` has `ui-library/utils/some-util.ts`

```
// ui-library/utils/some-util.ts
export * from ''@some-node-module;
```


Then the apps get this error when importing from `ui-library/utils/some-util.ts`

```
// app-1/some-file.ts
import { someFunction } from "ui-library/utils/some-util"

someFunction(); // Error
```

None of the workarounds or suggestions have worked as of yet 😢

**Comment by enyelsequeira** [comment]
> the hoisting solution - doesn't it effect the advantages of pnpm ? isn't there another way to work with symlinks ?

this did the trick for me, but I am also wondering are there any drawbacks?

**Comment by belgattitude** [comment]
@enyelsequeira 

If you're on `pnpm >= 7.29.0 || 8.0.0-alpha` you might try with the following settings in your `.npmrc`. Pnpm is currently improving issues with duplicates (deps, dev-deps, peer-deps).

```
## PNPM related ###############
## https://pnpm.io/next/npmrc #
###############################

# Not always possible to be strict, but if it works for you, keep it to true.
# https://pnpm.io/next/npmrc#strict-peer-dependencies
strict-peer-dependencies=false

# Auto install peers should be false to avoid downloading 
# extraneous deps. If the install fails, try first to explicitly add
# the missing deps in your package. Set it to true at last resort 
# (when the problem comes from upstream dependencies). The best is false. 
# https://pnpm.io/npmrc#auto-install-peers
auto-install-peers=false

# Helps locating duplicates, default in v8
# https://pnpm.io/next/npmrc#use-lockfile-v6
use-lockfile-v6=true

# Will fix duplicates due to peer-dependencies (>=7.29.0), default in v8
# https://github.com/pnpm/pnpm/releases/tag/v7.29.0
dedupe-peer-dependents=true

# Helps with peer-deps (>=7.23.0), default in v8
# https://pnpm.io/npmrc#resolve-peers-from-workspace-root
resolve-peers-from-workspace-root=true

```

Then run

```bash
pnpm install && pnpm dedupe
```

Theoretically it should work.

>  I am also wondering are there any drawbacks

By using `node-linker = hoisted`, pnpm will store your deps +/- like npm does (more compatible). Thus loosing some pnpm features.

**Comment by sugarp** [comment]
As a workaround you can enforce the module path by aliasing in `tsconfig.json`. 

From the example `../../deps/node_modules/@types/react-router`

```
{
  "extends": "*",
  "compilerOptions": {
    ...
    "outDir": "./dist",
    "baseUrl": "./",
    "paths": {
        "~/*": ["src/*"],
        "@types/react-router": ["node_modules/@types/react-router"],
     },
  },
  "exclude": ["node_modules", "dist"],
  "include": ["src", "test"]
}
```

**Comment by tjx666** [comment]
![image](https://user-images.githubusercontent.com/41773861/225528898-1b46a914-9da1-42ce-8916-a4aa28d2d351.png)

**Comment by electrovir** [comment]
I posted a solution earlier, but I run into this error somewhere around every month and I need a different solution every time. This time my solution was to explicitly define my function's return type, rather than forcing TypeScript to infer it.

from

```typescript
export function doThing() {
    const stuff = doSomething();
    return {
        stuff,
    };
}
```

to

```typescript
import {ExplicitlyImportedType} from 'whatever'

export function doThing(): {stuff: ExplicitlyImportedType} {
    const stuff = doSomething();
    return {
        stuff,
    };
}
```

**Comment by gajus** [comment]
```
node-linker=hoisted
```

is the only thing that fixed in pnpm.

I tried v8 as well, but no luck.

Something to note:

I had to do:

```bash
find . -name 'node_modules' -type d -prune -print -exec rm -rf '{}' \;
pnpm i
```

to make it work.

Simply doing `pnpm i && pnpm dedupe` was still throwing an error.

**Comment by Himself65** [comment]
in my case, I believe it will throw error when `tsconfig.node.json` and `tsconfig.json` include the same file

**Comment by kiastorm** [comment]
I was getting this error in a pnpm monorepo. I fixed it switching `paths` in my `tsconfig.json` to point to my package in `node_modules`, rather than relative to the monorepo directory structure.

**Before (bad)**
```
"paths": {
  "@org/my-package": "../my-package/src"
}
```

**After (good)**
```
"paths": {
  "@org/my-package": "./node_modules/@org/my-package/src"
}
```

**Comment by ozzyfromspace** [comment]
Just wanted to add to the set of possible solutions: this error can occur when working in a monorepo. Essentially, what happens is that you can two packages, A and B. B consumes components from A. If you use some types in A that also exist in B, you need to be sure that the versions of such types are consistent with each other. If not, the compiler in the consuming package will alert you to a type it doesn't have access to.

As a concrete example:

If you have a monorepo with a UI package written with react, your types may include @types/react ^18.0.0 . If the consuming package is using @types/react <18, the types may not agree, causing the issue at build time. In nextJS particularly, dev works just fine because the compiler doesn't do strict linting as you work. However, at build time, it will throw the error.

You can fix this by doing two things:

1) ensure that the consuming package using the minimum supported types, preferably within the same major version (to prevent breaking changes, presuming a semver-compliant package)
2) rather than marking types that will exist in the consuming package as dev dependencies, mark them as peer dependencies inside your package json. This should tell your consuming compiler that it's not actually supposed to use the dependencies that were specified in the first package, but rather use that as a guide to ensure that it has the minimum supported types

I got the type annotation error that makes up the subject of this thread because my consuming package was using v17 types (@types/node, @types/react/react, @types/react-node). Just going into my package.json, setting them to the latest major version, and running `pnpm update` fixed my problem. Granted, it took me 3 days to even understand what I was doing wrong lol.

Hope this helps someone.

**Comment by pkerschbaum** [comment]
FYI I added [a comment in TypeScript#47663](https://github.com/microsoft/TypeScript/issues/47663#issuecomment-1519138189) which has workarounds for this issue when using pnpm monorepos.

**Comment by ozzyfromspace** [comment]
@pkerschbaum thanks for the very descriptive comment, can't wait to read it!

**Comment by nixjs** [comment]
In monorepo, set all `typescript` to the same version:
```json
"typescript": ">=4.6.3",
```
Then create `npmrc` and put some information:
```strict-peer-dependencies=false
legacy-peer-deps=true
auto-install-peers=true
node-linker=hoisted
```
Everything will run smoothly.

**Comment by belgattitude** [comment]
Would be nice to know which pnpm version you use ?  V8 is bring new lights, I'm wondering if it does help avoiding the hoisted config. Thx

**Comment by pkerschbaum** [comment]
@nixjs I think your proposed solution is workaround #5 of [my comment in #47663](https://github.com/microsoft/TypeScript/issues/47663#issuecomment-1519138189), and that workaround has a drawback - see the explanation there.

**Comment by bartektelec** [comment]
For me it was the pnpm monorepo like mentioned before, using Express I would get the same error. What did the trick is to hoist the package, in project root I made a .npmrc file and added a 
```yaml
public-hoist-pattern[]=*express*
```

**Comment by Maxim-Mazurok** [comment]
I'm getting this error when declaring handlers array for MSW, having `"moduleResolution": "bundler"` in tsconfig. Using `"moduleResolution": "Node"` makes the error go away.

**Comment by gustawdaniel** [comment]
I had the same error with Prisma. Wrong code

```
import { PrismaClient } from '@sportsbase-libs/database-mapping-next';
import { databaseUrl } from './databaseUrl';

export const mapping = new PrismaClient({
  datasources: {
    db: {
      url: databaseUrl('mapping'),
    },
  },
  log: process.env.DEBUG ? ['query', 'info', 'warn', 'error'] : [],
});
```

Fixed code

```
import { PrismaClient } from '@sportsbase-libs/database-mapping-next';
import { databaseUrl } from './databaseUrl';

export const mapping: PrismaClient = new PrismaClient({
  datasources: {
    db: {
      url: databaseUrl('mapping'),
    },
  },
  log: process.env.DEBUG ? ['query', 'info', 'warn', 'error'] : [],
});
```

**Comment by sergiocarneiro** [comment]
**TLDR;** I had a **version mismatch** of a dependency. All related packages in the monorepo needed to have the same version installed.

**Comment by Eliav2** [comment]
most of you (including me🫠) doesn't read the error message. ` A type annotation is necessary`:
explicit type annotation solves the problem.

so
```ts
export const useMongoRealtimeProvider=() => {
...
}
```
becomes
```ts
export const useMongoRealtimeProvider: () => Socket = () => {
...
}
```

**Comment by divmgl** [comment]
This is unreal. Also using a `pnpm` monorepo and this comment was the only solution: https://github.com/microsoft/TypeScript/issues/42873#issuecomment-1497551116

It's unbelievable just how fickle all of this configuration is to get these packages to work together.

**Comment by kiastorm** [comment]
> This is unreal. Also using a `pnpm` monorepo and this comment was the only solution: https://github.com/microsoft/TypeScript/issues/42873#issuecomment-1497551116. The dependency in question was `ioredis` and both versions in `package.json` was pinned to the same version, so there was no reason for a mismatch.
> 
> 
> 
> It's unbelievable just how fickle all of this configuration is to get these packages to work together.

In the end I had to abandon this solution because it messed up auto-import in VS Code.

We now use [pnpm patch](https://pnpm.io/cli/patch) to patch the dependency causing problems and eliminate the error

**Comment by cumt-robin** [comment]
It's annoying...

**Comment by divmgl** [comment]
This is driving me nuts.
<img width="245" alt="Screenshot 2023-09-17 at 11 12 14 PM" src="https://github.com/microsoft/TypeScript/assets/5452298/884045a6-558a-491f-a74c-be1f082d385b">

<img width="228" alt="Screenshot 2023-09-17 at 11 12 27 PM" src="https://github.com/microsoft/TypeScript/assets/5452298/35be8c46-7205-4e6c-859b-d6676689e1cf">

Also confirmed that the BullMQ version we're using is using that same version of `ioredis`. Unfortunately:

```
src/router.ts:35:14 - error TS2742: The inferred type of 'appRouter' cannot be named without a reference to '@/core/node_modules/ioredis/built/Redis'. This is likely not portable. A type annotation is necessary.

35 export const appRouter = mergeRouters(
```
This call is super distant, it's like a second-level import. Bafflingly weird problem as I can't even figure out where the mismatch is.

**Comment by AndrewAriza** [comment]
This error is because `declaration: true` in `tsconfig.json` and declaration is true when `composite: true`. 🚀

**Comment by cumt-robin** [comment]
Maybe you can try like this, post written in Chinese, I don't guarantee it can solve your problem.
https://juejin.cn/post/7282606413842415675

**Comment by miccoh1994** [comment]
I have found running clearing node_modules with `find . -name 'node_modules' -type d -prune -exec rm -rf '{}' +\n\n` and then reinstalling works for PNPM.

**Comment by yashsway** [comment]
I have a [pnpm](https://pnpm.io/) monorepo with a package and an app _using_ that package:

```
pnpm-monorepo
  apps
    react-frontend (uses "backend-adapters". has a dependency on the "msw" package)
  packages
    backend-adapters (has a dependency on the "msw" package)
      adapters
      schemas
      mocks
```

The type error that prevents building looks like this in the **backend-adapters** package:
```
The inferred type of setupRestAPIWorker cannot be named without a reference to ../../node_modules/msw/lib/glossary-de6278a9 . This is likely not portable. A type annotation is necessary.
```

where `setupRestAPIWorker` is just:
```ts
import { restHandlers } from "../mocks/handlers";
import { setupWorker } from "msw";

/**
 * Mock Service worker for all REST API adapters in the domain package
 * @returns a MSW instance
 */
const setupRestAPIWorker = () =>
  setupWorker(...Object.values(restHandlers).flat()); // red squiggly line in VSCode shows up in the const here thanks to Typescript

export { setupRestAPIWorker };
```

The Typescript configuration for this package comes from the root of the monorepo. There is a  `tsconfig.base.json` in the root of the monorepo that is shared by all the apps and packages:
```json
{
  "compilerOptions": {
    "moduleResolution": "node16",
    "target": "ES2022",
    "module": "ES2022",
    "lib": ["ES2022", "DOM", "DOM.Iterable"],
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "noImplicitReturns": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  }
}
```

There's also a `tsconfig.lib.json` in the root of the monorepo intended for use by packages specifically:
```json
{
  "extends": "./tsconfig.base.json",
  "compilerOptions": {
    "composite": true,
    "declaration": true,
    "declarationMap": true,
    "noEmitOnError": true,
    "emitDeclarationOnly": true
  }
}
```

So our package **backend-adapters** uses the lib config above like so:
```json
{
  "extends": "../../tsconfig.lib.json",
  "compilerOptions": {
    "strict": true,
    "sourceMap": true,
    "declarationDir": "lib/types",
    "resolveJsonModule": true,
    "noEmitOnError": false,
    "outDir": "lib",
    "isolatedModules": true,
    "useDefineForClassFields": true
  },
  "include": ["src/**/*", "package.json"]
}
```

Based on how config inheritance works, this means that `moduleResolution` for this package is set to `Node16`.

So at this point, I've tried all the solutions presented in @pkerschbaum 's [comment way above](https://github.com/microsoft/TypeScript/issues/47663#issuecomment-1519138189) and I found that none of them worked. What actually worked was changing the `moduleResolution` in the package `tsconfig.json` back to `Node`. This option is clearly deprecated so this doesn't feel ideal. 😢 

Tooling versions:
- Typescript `4.9.5`
- MSW `1.2.3`
- Node `18.15.0`

**Comment by jamespjarvis** [comment]
Disabling declaration and declaration map in the tsconfig for the application importing the package in my pnpm monrepo worked for me.

**Comment by adicco** [comment]
> I'm getting this error when declaring handlers array for MSW, having `"moduleResolution": "bundler"` in tsconfig. Using `"moduleResolution": "Node"` makes the error go away.

Same thing here, using `znv`'s `parseEnv` with zod types. I get the warning only when my tsconfig has `bundler` for `moduleResolution` (as per [Bun's suggested compilerOptions](https://bun.sh/docs/typescript))

**Comment by Nikola-Milovic** [comment]
Same issue here

```
import { create } from "zustand";
import { devtools } from "zustand/middleware";
import { immer } from "zustand/middleware/immer";

...
export const useAppStore = create<AppState & AppActions>()(
	immer(
		devtools((set) => ({
			user: null,
			setUser: (user) => set({ user }),
		})),
	),
);
```

` The inferred type of 'useAppStore' cannot be named without a reference to '.pnpm/immer@9.0.6/node_modules/immer/dist/internal'. This is likely not portable. A type annotation is necessary.`

`"typescript": "5.1.6"`

The tsconfig

```json
/dashboard ➜ tsc --showConfig
{
    "compilerOptions": {
        "composite": false,
        "declaration": true,
        "declarationMap": true,
        "esModuleInterop": true,
        "forceConsistentCasingInFileNames": true,
        "inlineSources": false,
        "isolatedModules": true,
        "preserveWatchOutput": true,
        "strictNullChecks": true,
        "skipLibCheck": true,
        "strict": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "noFallthroughCasesInSwitch": true,
        "target": "es2020",
        "useDefineForClassFields": true,
        "lib": [
            "es2020",
            "dom",
            "dom.iterable"
        ],
        "module": "esnext",
        "moduleResolution": "bundler",
        "allowImportingTsExtensions": true,
        "noEmit": true,
        "jsx": "react-jsx",
        "baseUrl": "./",
        "paths": {
            "@dashboard/*": [
                "./src/*"
            ]
        }
    },
    "references": [
        {
            "path": "./tsconfig.node.json"
        }
    ],...
}

{
  "compilerOptions": {
    "composite": true,
    "skipLibCheck": true,
    "module": "ESNext",
    "moduleResolution": "bundler",
    "allowSyntheticDefaultImports": true
  },
  "include": ["vite.config.ts"]
}
```

This is the default vite tsconfig generated (with minor tweaks)

**Comment by mklueh** [comment]
Suddenly had this problem with Nuxt 3.8.0 in the nuxt.config.ts. 

Not sure why, because I haven't changed the tsconfig.base.json.

However, setting `"declaration": false` worked for me

**Comment by gajus** [comment]
Related problem https://stackoverflow.com/questions/43900035/ts4023-exported-variable-x-has-or-is-using-name-y-from-external-module-but/77390832#77390832

**Comment by Uregek** [comment]
Has anyone found any other solutions? I use Turborepo with pnpm, there are two identical Nestjs apps works on different ports, but only one causes an error: 
`src/app.controller.ts:18:2 - error TS2742: The inferred type of 'getHelluo' cannot be named without a reference to '.pnpm/rxjs@7.8.1/node_modules/rxjs'. This is likely not portable. A type annotation is necessary.`

**Comment by mklueh** [comment]
> Suddenly had this problem with Nuxt 3.8.0 in the nuxt.config.ts.
> 
> Not sure why, because I haven't changed the tsconfig.base.json.
> 
> However, setting `"declaration": false` worked for me

I had a broken reference to the root tsconfig which caused this issue in the first place. It was caused by moving the project one hierarchy level up in the monorepo

**Comment by transitive-bullshit** [comment]
Setting `"declaration": false` and `"declarationMap": false,` in my `tsconfig.json` solved this for me, though this is an odd fix.

**Comment by pkerschbaum** [comment]
Because it is hidden in the >100 comments, I want to surface my workarounds list again https://github.com/microsoft/TypeScript/issues/47663#issuecomment-1519138189.
@transitive-bullshit this should also explain to you why setting these two options to `false` helped in your case.

**Comment by J4v4Scr1pt** [comment]
Is there no good solution on this issue?! I have been pulling my hair with this for days.
No solution works for me.

```
stories/components/Button/Button.tsx(55,7): error TS2742: The inferred type of 'MyButton' cannot be named without a reference to '../../../node_modules/.pnpm/registry.npmjs.org+@nextui-org+system-rsc@2.0.7_@nextui-org+theme@2.1.10_react@18.2.0_tailwind-variants@0.1.18/node_modules/@nextui-org/system-rsc/dist/types'. This is likely not portable. A type annotation is necessary.      
stories/components/Button/Button.tsx(55,7): error TS2742: The inferred type of 'MyButton' cannot be named without a reference to '../../../node_modules/.pnpm/registry.npmjs.org+@nextui-org+react-utils@2.0.10_react@18.2.0/node_modules/@nextui-org/react-utils/dist/refs'. This is likely not portable. A type annotation is necessary.
stories/components/Button/Button.tsx(55,7): error TS2742: The inferred type of 'MyButton' cannot be named without a reference to '.pnpm/registry.npmjs.org+@react-types+shared@3.21.0_react@18.2.0/node_modules/@react-types/shared'. This is likely not portable. A type annotation is necessary.
stories/components/Button/Button.tsx(55,7): error TS2742: The inferred type of 'MyButton' cannot be named without a reference to '.pnpm/registry.npmjs.org+@react-types+shared@3.21.0_react@18.2.0/node_modules/@react-types/shared'. This is likely not portable. A type annotation is necessary.
stories/components/Button/Button.tsx(55,7): error TS2742: The inferred type of 'MyButton' cannot be named without a reference to '.pnpm/registry.npmjs.org+@react-types+shared@3.21.0_react@18.2.0/node_modules/@react-types/shared'. This is likely not portable. A type annotation is necessary.
stories/components/Button/Button.tsx(55,7): error TS2742: The inferred type of 'MyButton' cannot be named without a reference to '.pnpm/registry.npmjs.org+@react-types+shared@3.21.0_react@18.2.0/node_modules/@react-types/shared'. This is likely not portable. A type annotation is necessary.
stories/components/Button/Button.tsx(55,7): error TS2742: The inferred type of 'MyButton' cannot be named without a reference to '.pnpm/registry.npmjs.org+@react-types+shared@3.21.0_react@18.2.0/node_modules/@react-types/shared'. This is likely not portable. A type annotation is necessary.
stories/components/Button/Button.tsx(55,7): error TS2742: The inferred type of 'MyButton' cannot be named without a reference to '.pnpm/registry.npmjs.org+@react-types+shared@3.21.0_react@18.2.0/node_modules/@react-types/shared'. This is likely not portable. A type annotation is necessary.
```

I have created a [sandbox ](https://codesandbox.io/p/sandbox/condescending-wozniak-38f9d7?file=%2Fvite.config.ts%3A13%2C11)to show the issue.
Run `pnpm build-sb` to create the component lib and get the error. And `pnpm sb` just to start it, which work.

**Comment by AHMET-EMREBAS** [comment]
Import the packages in your library/app entry point file.

**Comment by rehdie** [comment]
My problem was a stupid Windows-Problem:  the error occurred in a jenkins build and the root-cause of the error was a too long path. 

In our case we have an Angular module built with the maven frontend-plugin. The path, where the build was executed, was 

C:\Jenkins\workspace\vgwort\JERRY\Release Management\Release eines Moduls\target\checkout\hf.webclient

and the error was 
```
18:07:13  [INFO] [INFO] projects/jerry/hf-init/src/lib/hf.menu.ts:20:14 - error TS2742: The inferred type of 'HF_MENU' cannot be named without a reference to '.pnpm/@angular+core@15.2.1_rxjs@7.8.0_zone.js@0.11.4/node_modules/@angular/core'. This is likely not portable. A type annotation is necessary.
```

Executing the build in 

C:\Jenkins\workspace\vgwort\JERRY\Release Management\Release eines Moduls\hf.webclient

works fine. Maybe this helps....

**Comment by matthieusieben** [comment]
Consider the following file structure:

```
/monorepo
  /.pnpm
    /kysely@0.22.0/node_modules/kysely
  /packages
    /foo
      /src
        /index.ts
      /node_modules
        /kysely -> ../../.pnpm/kysely@0.22.0/node_modules/kysely 
```

When using `import k from "kysely"` in `index.ts`, the resolved path (when hovering `"kysely"` in vscode) shows the absolute path on disk (`/monorepo/.pnpm/kysely@0.22.0/node_modules/kysely/...`)

Since Typescript sees that the dependence outside `foo`, it display the error.

However, since the full path to the imported files was resolved by following a symlink which **does** reside inside `foo`, Typescript should not consider that this package is "not portable".

**Comment by dgknca** [comment]
> Disabling declaration and declaration map in the tsconfig for the application importing the package in my pnpm monrepo worked for me.

A reminder for myself: this is the solution!

**Comment by matthieusieben** [comment]
Disabling emit of declaration files is only a solution if you don't need them.

**Comment by babakfp** [comment]
When is this going to get fixed? Why should anyone disable the `declaration` option when it's needed? Can Microsoft stop f***ing around and keep working on projects it has started?

**Comment by divmgl** [comment]
While I don't agree with the wording here https://github.com/microsoft/TypeScript/issues/42873#issuecomment-1998466411 I do agree with the sentiment. It'd be nice if a majority of these "quirks" were ironed out.

**Comment by babakfp** [comment]
@typescript-bot @RyanCavanaugh @jakebailey

Can you get this fixed, please?

**Comment by Threebow** [comment]
I spent five hours chasing a bug because I had to type an exported field as `any` to make TypeScript compile, instead of using the correct module type, due to this inferred type error ([further context in my comment on a related issue](https://github.com/microsoft/TypeScript/issues/47663#issuecomment-1915783443)).

While I do recognize that TypeScript is free and open-source software, and as such isn't actually guaranteed to be maintained in the slightest, I don't believe it's unreasonable to expect a more prompt response to such recurring bugs, especially considering 1) Microsoft's backing and the resources they have at hand; and 2) the current position of TypeScript being unescapable within the JS ecosystem nowadays.

I feel that addressing these bugs could only enhance TypeScript. Conversely, neglecting these issues risks eroding trust in TypeScript's development. While I do understand that it is unrealistic to expect an immediate resolution for every issue, it remains concerning to myself (and others I am sure) that many such bugs have remained unresolved for years.

Just my 2c.

**Comment by rhuanbarreto** [comment]
For the ones joining the issue recently:

The root cause for this issue is described by this comment: https://github.com/microsoft/TypeScript/issues/42873#issuecomment-1941449175

Main issue is due to people using PnPM or Bun, which are installing packages as symlinks instead of copying files. Then Typescript follows the symlink and finds out the referenced file is out of the project root, which triggers the error.

Not sure on how to fix this. But the most important is to know the root cause.

**Comment by babakfp** [comment]
Honestly, I'm not switching to NPM. A trash tool forces you to switch to another trash tool, lol. I don't have free 300mb for every goddamn project to install the same package over and over again!

That sounds like it may not be hard to fix after all! Can't the TypeScript team ask for help by sending a message on social media platforms? This will help find someone to fix this issue. If they can't even do this, it's better if they archive the project and let it die. This way other projects will fill the gap, hopefully! They can even try to financially support other open-source projects because clearly, they can't maintain their projects.

**Comment by babakfp** [comment]
I switched to NPM and the issue still exists!!! (same with PNPM and Bun). I'm using Windows 11.
The people that were saying this only happens when using PNPM and Bun, this they test it? Am I doing something wrong?
About symlinks, I don't understand what they achieve here, no matter which package manager I use, the size of node_modules is (almost) the same!!!

**Comment by theoephraim** [comment]
I think I have a relatively painless solution which may work for some...

So in a case where we have a setup like
- A is the original library with the unresolvable type
- B is a helper library which wraps and exposes functionality in a library A
- C is the end user code, which uses library B instead of interacting with A directly (and I'd like to not even declare the dependency on A)

It seems I'm able to fix the issue by re-exporting the missing type from A in B, even though C will still not import it or use it directly.

so my library in B will include something like 
```
export type { MissingType } from 'A'
```
and C can continue to interact with B as it was before...

Would be great if this is fixed but this will certainly work for now

**Comment by pkerschbaum** [comment]
> I think I have a relatively painless solution which may work for some...
> 
> So in a case where we have a setup like
> 
> * A is the original library with the unresolvable type
> * B is a helper library which wraps and exposes functionality in a library A
> * C is the end user code, which uses library B instead of interacting with A directly (and I'd like to not even declare the dependency on A)
> 
> It seems I'm able to fix the issue by re-exporting the missing type from A in B, even though C will still not import it or use it directly.
> 
> so my library in B will include something like
> 
> ```
> export type { MissingType } from 'A'
> ```
> 
> and C can continue to interact with B as it was before...
> 
> Would be great if this is fixed but this will certainly work for now

This is workaround 3.1 of my "workarounds comment" buried deep in this discussion: <https://github.com/microsoft/TypeScript/issues/47663#issuecomment-1519138189>

@mistic may I ask you to update the issue to include a link to these workarounds? The many upvotes indicate it is/was helpful for many people, and I would like to stop commenting here spamming all issue subscribers just to "resurface" the workarounds :)

**Comment by MarvinXu** [comment]
I'm using prisma. Importing type from prisma client seem to fix this error(Even though I'm not using this type)
```ts
import { Product } from '@prisma/client';

@Injectable()
export class ProductsService {
  findAll() {
    return this.prisma.product.findMany();
  }
}
```

**Comment by JoaoMosmann** [comment]
> I'm using prisma. Importing type from prisma client seem to fix this error(Even though I'm not using this type)
> 
> ```ts
> import { Product } from '@prisma/client';
> 
> @Injectable()
> export class ProductsService {
>   findAll() {
>     return this.prisma.product.findMany();
>   }
> }
> ```

This indeed works.
For more complex cases where there are loads of types required in different levels, I've added a 
```ts
import type * as PackageTypes from "package"
```

**Comment by babakfp** [comment]
TypeScript 💪, LOL

```ts
import * as _1 from "../../../node_modules/.pnpm/yaml@2.4.1/node_modules/yaml/dist/index.js"
import * as _2 from "../../../node_modules/remark-gfm/lib/index.js"
import * as _3 from "../../../node_modules/.pnpm/mdast-util-toc@7.0.0/node_modules/mdast-util-toc/lib/index.js"
import * as _4 from "../../../node_modules/rehype-slug/lib/index.js"
import * as _5 from "../../../node_modules/rehype-autolink-headings/lib/index.js"
import * as _6 from "../../../node_modules/rehype-external-links/lib/index.js"
```

When is the TypeScript team going to fix this 4-year-old issue?! @weswigham

**Comment by weswigham** [comment]
With #58176 merged, all of the instances of this issue that are actually us not looking up a dependency you actually have available (because of symlinks preventing us from realizing some path equivalences) should be fixed in the next release, barring any funky unforeseen bugs (which, if you think you can demonstrate, please open a new issue for us to consider). Which is what the OP's issue was long, long ago. Other people in this thread... much less so.

That means that so long as you actually have the dependencies your declaration file needs as direct dependencies (in your `package.json`), we'll be able to autogenerate appropriate dependency names, and no longer emit this error. If you *still* see this error in TS 5.5 and beyond and come to this thread - I'm sorry, SEO has led you astray. This github issue having floated to the top, above even stackoverflow, for that error message is somewhat unfortunate, but not really in our control.

For the benefit of those searchers, our FAQ will likely be updated to have a detailed explanation for this error by the time you find this, but in short: You really do just need to do what the error says, and _write an explicit type annotation on the node the error is marked on_. You have an implicit, direct, type-level dependency on an _indirect_ dependency's types, and we can't resolve that issue for you - it's up to you how you want to reach in and get at the innards of your dependencies. Maybe you add whatever the type is coming from as a direct dependency, maybe you write your own equivalent type, maybe there's a winding road through aliases and reexports and conditional `infer`s to get at the type that we can't automatically discern, but you can write as the annotation - whatever works for you.

**Comment by RyanCavanaugh** [comment]
I'm going to lock this since top-SEO issues do get a lot of drive-by comments that will ultimately hide the helpful above comment. See also (this comment)[https://github.com/microsoft/TypeScript/pull/58176#issuecomment-2052698294] for a bit of a longer restatement of this.

If, after trying 5.5 beta (or today's nightly or later) you're still seeing this error in a situation where it seems illegitimate, please log a new issue with a link to a simplified repo that we can use to investigate and we'll take a look.
