### ISSUE TITLE
Recursive types error: Type instantiation is excessively deep

### ISSUE THREAD

**Issue by vlazh** [microsoft/TypeScript#45672]
# Bug Report

I had got error `Type instantiation is excessively deep and possibly infinite.` in my JSON types - value to JSON transformation.
It's some new limitation introduced from v4.3.2?
Works fine with v4.2.4.

### 🕗 Version & Regression Information

- This changed between versions 4.2.4 and 4.3.2

### ⏯ Playground Link

I couldn't get to make a short and simple example because when I removing any recursive type reference then error will disappeared.

[Playground link with relevant code](https://www.typescriptlang.org/play?jsx=0&ts=4.4.2#code/PQKgBApgzgNglgOwC4FoAmcoEMBGMJgjACwAUGaGAKpJwxSEnmlICeADgQIIKsDyOAFYQAxkjABeMACVRAewBOaADxQkCxAHMANGCy8AfAG4yZNpzA9WAMQCuCMXDkJJYABQA6L1gWaoALj1eAEpJAyDWE2ZzAgBJADMAUQAPJAgENChlABVdbI4IPIALdNdcsET6AikECAA3CAVwqRT1LDEcvILwiFT0zLBahoUyMDAAfgqq0bBA1oV2pE6wfM4evoyGVYgZyeyShBm5qqizArAAaQhWKD547eUuSA2BqwFhMV0AIV0AZXU4GJnmlNmAcHI5Ph9K51LYIM0wAA5ZyI2wwGC4fDKGYAbxmYwA2gAFMCIMAAa2ucnilgAuoF-hogb0QQNYTtSGMuRMwAlWv0svNFo9ibTvgZvroiboho0DPiuYEuKLgQKwF8FWNJkTNbNBvVGlExgBfAmU1jUulkYymFjnFIiGC2NAQK43O4PJ4stVvISiJCSsCMwHib2g8GQiDQqTxLBVBFEwHk7GcyzaGYOp0u5Tmy1cXRu273AqPQPBsQGeWkG3Re2pBZiQsektel4MX0fAPqv4A5ltsEQqEuGNxqDw1yJkTJmb5mZN4ucUvdoO9pBVmtnCx8di0Zw5BE4sCaCBIQJuUIScLZMDG06kSiydgKOSMW0xCrJR3OiB2By7hBZK2rLtrw7z+gimbfvOnq6FYv6OM4G52hYABqcZwGgRLPuwgGqqCHb+rofAALZwEghZ4QMuY0vorAQZ+WY-vYCEASmYwkWRS4ceR1wMAAPhSVI0gAUr8fCIr8jRwOhABemIQMotG6LRlbWne76ieJXAKAs-DxGxaYzLEUCyFgaDODArCUQwEZDumqbcRRYYDEKja8Y866uMZpnmQglnWWA7I8j5FmsNpunKMJUDOHA8SsFxpE8TclZ6uFWDxVFMVxQlZGFpW6nnNu-5xo8AUEZ8YCObxAWuUlgEpVIeKpsSpIuJB2bUR+bRue6C4KfmlU7k4CCKYYEqVYleW0uMgSZQgsXxcqRJihNuW8TWt5vucyIIEVw0lUBPqgX6FVVTcNX1oshYeQeMwtWSnVofAmHYYKDFQbxzaLgNe17ip41nVABj0mAc0LSKy1EZN61RJttYWJpiJgWIdylc5IH8CdXaAxd3V1TdriPehL1yDhBmzg50M3NaAWyiMqaTDixpHINxUwDldXhAAZEizi-QgB1Q2tyUFRYtXXVwCKHaC-PKIg8SNCsVZal1Db49kyupQFiOSRosnyXLCAKwoKzKYYuyq1d7kayz0sDCFflhTp6WG8bSsW+L1ua0qZXHZ2FudVwLN03evTsIo4gadF83ZT9VMMOjls9fVrh01LAWy-Lis2wzoPR+D5S1cogO6J7Nz7ilAn2C68SIBAaC29rYkSVJ+t4ApWcm+UKkW2D2WF5dHQl0n6uVt7lgBQ7llpfFnfu7niMz6j5R2+2zvxSpPKxlUersqXg9LMPZdZBrqmpj7idUIgSAABwz2AAlX8gACMABs9+P9fADMABMH+8sgO+68H4AKQG-f+sRkC-xnhbGeygEC2GIjgOUjdE7lSQL3ZuyMkCozjsLIGLM1AaAQJoUOyRw4KHENfRosYRAEB1q3eAcl25o37OgoWdVcZqwlgiNOYAmpjAUFGXy-kAD6Y49ZMPkrNZuutpJSJYXgzmRpApyERueWa+dY4cLyrDMgQA)

**Comment by andrewbranch** [comment]
Re-opened from #44281, possibly related: #45632, #45576

**Comment by weswigham** [comment]
We did definitely add rules for relating conditional type constraints around then, I think.

**Comment by andrewbranch** [comment]
https://github.com/microsoft/TypeScript/pull/37208?

**Comment by andrewbranch** [comment]
Indeed, reverting that “fixes” this issue.

**Comment by jakearchibald** [comment]
I think this issue is impacting a couple of my libraries, as the `IDBValidKey` now references itself.

[Here's the pattern that's causing a problem](https://www.typescriptlang.org/play?ts=4.4.2#code/JYWwDg9gTgLgBAbzgQwM6oKaxauMCeYGAguljADRwCSqAogB7IDG8AvnAGZQQhwDkzCADsAJsBjARyADYBaAkTnMAFhmYBrVPwDcAKD1DhqeFAyoArjJgAuGgBEAQgDVZwUQGkM+ANoBdOABeOB9+TggIfj99PUUSMlgAHlpGFhhEuIhOODNLaypqJ1cZdy9fPwA+CoAKGCgLDABKHSA).

**Comment by vlazh** [comment]
It looks like the issue was fixed by the version 4.6.2. Isn't it?

**Comment by jakearchibald** [comment]
[This example](https://www.typescriptlang.org/play?ts=4.6.2#code/JYWwDg9gTgLgBAbzgQwM6oKaxauMCeYGAguljADRwCSqAogB7IDG8AvnAGZQQhwDkzCADsAJsBjARyADYBaAkTnMAFhmYBrVPwDcAKD1DhqeFAyoArjJgAuGgBEAQgDVZwUQGkM+ANoBdOABeOB9+TggIfj99PUUSMlgAHlpGFhhEuIhOODNLaypqJ1cZdy9fPwA+CoAKGCgLDABKHSA) still fails in 4.6.2. Not sure if that's intended.

**Comment by vlazh** [comment]
> [This example](https://www.typescriptlang.org/play?ts=4.6.2#code/JYWwDg9gTgLgBAbzgQwM6oKaxauMCeYGAguljADRwCSqAogB7IDG8AvnAGZQQhwDkzCADsAJsBjARyADYBaAkTnMAFhmYBrVPwDcAKD1DhqeFAyoArjJgAuGgBEAQgDVZwUQGkM+ANoBdOABeOB9+TggIfj99PUUSMlgAHlpGFhhEuIhOODNLaypqJ1cZdy9fPwA+CoAKGCgLDABKHSA) still fails in 4.6.2. Not sure if that's intended.

I found two deep recursions: `IDBValidKey` and `IsExact` -> `DeepMakeRequiredForIsExact`.
If splits `IDBValidKey` into two types the error goes away. [Example](https://www.typescriptlang.org/play?ts=4.6.2&ssl=5&ssc=6&pln=5&pc=17#code/JYWwDg9gTgLgBAbzgQwM6oKaxauMCeYGAguljADRwCSqAogB7IDG8AvnAGZQQhwDkzCADsAJsBjARyADYBaAkTnMAFhmYBrVPwDcAKD0B6Q3kIYaAEQBCANVnBRAaQz44AXjioYUYMIDmcAA+cMIAriAARlhBcBbIMObBVqGcnFgAyhChUMyJlrb2Ti4A2gC6OnBwxnAA8j5+vrJwohicvhJSwnqK5tTWdjIO6aBgMhjOrh5ePv4xYZHRwXEJMcmpGVk5GPo9+QMOE+57hcPgY4fBfQWDoqej4yXlBkLCXnBQGKihMjAAXMc3CZlI7FficCAQfhPbpmUiYWAAHlojBYMARPQgnHen2+lABB0eAD5CQAKbyhDAASh0QA).

**Comment by hasgar-aot** [comment]
any fix? it's kind of annoying 
v4.0.3 
fails in 4.3.5 too.
