### ISSUE TITLE
Support different moveToNewFile file name conventions

### ISSUE THREAD

**Issue by bobbyg603** [microsoft/TypeScript#46514]
# Suggestion

Support additional file naming conventions when refactoring.

## 🔍 Search Terms

moveToNewFile move to file "move to a new file"

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Specify project file naming conventions in tsconfig.json and use the rule [here](https://github.com/microsoft/TypeScript/blob/main/src/services/refactors/moveToNewFile.ts).

## 📃 Motivating Example

Angular projects use the file name convention some-example.component.ts. The refactor action "Move to a new file" uses the convention SomeNewFile.ts. Ideally, there would be a way to specify the naming convention of the new file. In this case, some-new-file.ts would be the desirable outcome.

## 💻 Use Cases

1. Create a TS interface in the same file where it's being used called SomeExampleInterface
2. Extract the interface using "Move to a new file" in VS Code
3. Notice the created file is SomeExampleInterface.ts, which needs to be renamed to some-example-interface.ts to follow project naming conventions

**Comment by rtablada** [comment]
This would be great if it could be supported!

**Comment by ImLunaHey** [comment]
To save others time trying to find this issue.

Related: https://github.com/microsoft/vscode/issues/81835

**Comment by bobbyg603** [comment]
This issue has been resolved. You can choose an arbitrary file name via "Move to File" then "Enter a new file path".

https://github.com/microsoft/TypeScript/assets/2646053/1fc1f5a0-b48d-4825-ae3f-e7da0fddb5cc

**Comment by BartaG512** [comment]
> This issue has been resolved. You can choose an arbitrary file name via "Move to File" then "Enter a new file path".
> 
>  move-to-file.mov

I would not say it is completed. You need to type in the file name, but the original request was about adding file name conventions, so you can do refactor faster.

**Comment by bobbyg603** [comment]
@BartaG512 Allowing the user to specify a file name seems like an elegant and satisfactory way to solve the problem I originally reported. Please feel free to open a new issue if the solution isn't satisfactory for your use case.

**Comment by ImLunaHey** [comment]
This should be reopened as this does not fix the issue stated in the OP.

**Comment by chad-schwab** [comment]
I always want my filename to be the kebab case version of my function name. The solution as stated is hardly different than Move to new file -> rename. In fact, with autocomplete it's worse, as it's easy to accidentally move to an existing file with a similar name.

**Comment by ImLunaHey** [comment]
That's exactly what I'm after @chad-schwab. Since I work a lot with react and want my components to be capitalised in code but kebab case in the file name.

**Comment by bobbyg603** [comment]
Re-opened, this is no longer an issue for me, but it seems it's still an issue for others. I'll let the company with more resources and time figure out what to do about this 😮‍💨
