### ISSUE TITLE
Callback return type in javascript code is not checked properly under unpredictable circumstances

### ISSUE THREAD

**Issue by gerukin** [microsoft/TypeScript#49062]
# Bug Report

### 🔎 Search Terms

`is:issue is:open callback no check`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (up to `4.6.3`), and I reviewed the FAQ for entries about callbacks

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?target=7&ts=4.6.2&filetype=js#code/PQKhCgAIUgBBjAhgG2QI0fA1pAwi9TLKGWAB0QCdEBbSAbwHs0ArAU3gBcBfSMtygGdGAOxJxKbTgFdKIwQ0GdKASxEBzbiWDhwoCNDicAnvwAmbAGaQAosjY02IzrlGWV68eUqN+lE4rKapqQANoitGwAul5kPn4B9PioGNi8ofBoMdA6emBGpmwW1vR2Dk4ubh6hUbxljs6uIu7qCiC5+nAU1HSl9g2VzR6CvGz9FU0tbTrwokqQZowAyjKW1gC8kGPljVWtkOsAfJAA5IxYJ7qLK9JrABShUJDP9E-P75ARjgBcpwCCJwANG8PpBMr87gBKA7HE5A97AYCQTgACxUClmlEkXGQxkgghRjAA7goRIwtljGJRIGpkSi2JAAJIAERsIO4wI+r1B7y+bF+JwAQkCQR9wZAoTDIJYUIIGYi6eiwVTsZxcfjCSTIIgRBSfNTaaiGSy2R8tFFIVdlqtLA8QdyeZ9IgKAZzHeK-MJdUc+AIvQA6PmO4MK1FKzGq9UE4kKHV6qk03VGpmsmnWAAGZMZNDIyBU8BUnD+ImM6ZpCiciDQ9jMgO1IjMyqxHDVeOjWrJ8YNSfpKZsacgmcY2dz+cLxdL5YW6KrNfZbpeot5ztOwoXoPFkp9MuQcrrwYPPNDaIUjIAchGW1HNaTyQJ9Ym6cbU3cifSjdShyO8wWiyWy0qlbVkUkAJmSnCWma4AWroCqFgsjBsIIIgnJwkA0IgnCcAIkBvvmKJdsqjgKO4QhoYavZUNQxjgNcNp2lyS7PHyLoisGm7QtuspsPuh58ZAx5Kuel44m2N6fHelLdk+fYSm+Uj0p+WY5j+47-lOQE1qB1LgZB7wcvaTFOj8q5se6aC-J6ohSlZIiBpE-EIkiYYYiqV5iTG9aERRz79ioGbKaOv4TgBFYRMBtb1o2ImthqnmdveCY+bJ-mDoFql-pOSpmDOEXstBlp6EiaDSOR1hEgysw0AMoGlTJ6aZGWRKFgR6a2U1DLqFIMlsAAHvwXAgZIgjSMgnC0daty2o8jHBix-xmTyHFSjue6OXxgm3kSTaRh5Wpxol0nJia86GXNK5CotoIKh6frWT6tn2Y4+UwUV2m4QyqUVURNWMHVyaZpEAG6mwLU4cw7BcBNNz3DN7wOjy80nK6RnLVxu48eth6bRJ20xdenkHVJj7Hayp2zY6CpI2uqMWb6Qj3ccj1ButOP43tsYg8TyUmgOX4qWOmWhVs4U1nWOrRW5olxR2kkPjzqapfzQVqVlCg5YIs5FC9hU47K5JElSWAKHcgOOMLnbIKIXXUlVAwgX9aEleRChqAAbigKhmJadFTQx8NGUjKPsXTW7HKtmNYyGzknrjO3uTLnPeT2vnkwH50mQAnLxUeOWzUuxe2SeHSTvYnSHll3d6TNV09DKszH4YFwT+1c-LKcpQFw4C8F6mAaLRTiw28fS0XEnJzJvNK+lgshVOGta2YOuwUi+u4UbCjNaikAsNI8wNWgZaHQozu4S1juDo1fBUJE2FCND9Fw4uGf8gt65iqHnHh9xOe505ipbRHoXcSRN26TzJmadcCNQTUyuh-CEX9ICZz-htRurlmyjxAW3JKHdy76QKivSAp94KW2tjhQ2lBjYDm+pIGgjA3YMjQIwbeZs2BljiL4QQD8-ZPwYLTBBK0f4oOumg7U6hEC0mEs3Dm48S4K1NPpKB-D6ZehsrXFmedRHs0Tl5ORuDFZd2-LPPuYVF5D0lhg4B8U5Y4PAX5QxPdVbCwXnlKCMEgA)

### 💻 Code

```javascript
/**
 * @callback Callback
 * @param {object} person
 * @returns {string}
 */

/**
 * @typedef ElementConfig
 * @property {string} [name]
 * @property {Callback} [cb]
 */

/** @typedef {ElementConfig[]} ElementConfigs */

/** @param {ElementConfigs} elementConfigs */
const doStuff = elementConfigs => 'ok'

doStuff([
    {
        name: 'A',
        cb: () => '',   // this correctly shows no error in the IDE
    },
    {
        name: 'B',
        cb: () => false // this correctly shows an error in the IDE
    }
])

doStuff([
    {
        name: 'A',
        cb: person => person.name               // this correctly shows an error in the IDE if `noImplicitAny` is enabled, and correctly shows no error in the IDE if `noImplicitAny` is disabled
    },
    {
        name: 'B',
        cb: () => false,                        // this INcorrectly shows no error in the IDE (whether `noImplicitAny` is enabled or not)
    }
])

// it doesn't matter which error comes first in the array
doStuff([
    {
        name: 'A',
        cb: () => false,                        // this INcorrectly shows no error in the IDE (whether `noImplicitAny` is enabled or not)
    },
    {
        name: 'B',
        cb: person => person.name               // this correctly shows an error in the IDE if `noImplicitAny` is enabled, and correctly shows no error in the IDE if `noImplicitAny` is disabled
    }
])

// but if we comment out the `cb` with `person` we get the expected result
doStuff([
    {
        name: 'A',
        cb: () => false,                        // this now correctly shows an error in the IDE
    },
    {
        name: 'B',
        // cb: person => person.name
    }
])

// or we if we comment out the `name` in either object
doStuff([
    {
        name: 'A',
        cb: () => false,                        // this now correctly shows an error in the IDE
    },
    {
        // name: 'B',
        cb: person => person.name               // this correctly shows an error in the IDE if `noImplicitAny` is enabled, and correctly shows no error in the IDE if `noImplicitAny` is disabled
    }
])

// this also works (`name` is no longer commented out but is invalid)
doStuff([
    {
        name: 'A',
        cb: () => false,                        // this now correctly shows an error in the IDE
    },
    {
        name: 9,                                // this correctly shows an error in the IDE
        cb: person => person.name               // this correctly shows an error in the IDE if `noImplicitAny` is enabled, and correctly shows no error in the IDE if `noImplicitAny` is disabled
    }
])

// also works with just `cb` errors but without `cb` parameters
doStuff([
    {
        name: 'A',
        cb: () => false,                        // this now correctly shows an error in the IDE
    },
    {
        name: 'B',
        cb: () => 9                             // this correctly shows an error in the IDE
    }
])

// but it no longer works if we remove both `name` props
doStuff([
    {
        cb: () => false,                        // this again INcorrectly shows no error in the IDE
    },
    {
        cb: person => person.name               // this correctly shows an error in the IDE if `noImplicitAny` is enabled, and correctly shows no error in the IDE if `noImplicitAny` is disabled
    }
])
```

### 🙁 Actual behavior

Typescript, when checking javascript code, seems to allow callbacks with obviously incorrect return values under some circumstances which are difficult to guess.

### 🙂 Expected behavior

`cb: () => false` in the example should always return an error, no matter what other properties exist or not, and whether they could be validated.

**Comment by RyanCavanaugh** [comment]
Once a program contains an error, further checking of that program is suspect. In this case, once there's an access of the nonpresent  `name` property, the containing array can (sometimes) be reduced to ` { cb: () => any* }` where `any*` is the special error type which generally behaves as `any`.

Basically, to put it another way, we can only guarantee to issue 0 or not-0 errors; whether you get 1 or 2 or 3 or 4 errors is implementation-defined and isn't a reliable signal. An analogy would be that if you put `(3 / 0) + (4 / 0)` into a symbolic math evaluator, whether you get 1 divide-by-zero error or 2 is going to depend on how exactly that evaluator works.

**Comment by gerukin** [comment]
Thank you @RyanCavanaugh for the explanation but perhaps I am still missing something. The behavior still seems a bit opaque and unintuitive to me. 😇

[Playground Link](https://www.typescriptlang.org/play?target=7&ts=4.6.2&filetype=js#code/PQKhCgAIUgBBjAhgG2QI0fA1pAwi9TLKGWAB0QCdEBbSAbwHs0ArAU3gBcBfSMtygGdGAOxJxKbTgFdKIwQ0GdKASxEBzbiWDhwoCNDicAnvwAmbAGaQAosjY02IzrlGWV68eUqN+lE4rKapqQANoitGwAul5kPn4B9PioGNi8ofBoMdA6emBGpmwW1vR2Dk4ubh6hUbxljs6uIu7qCiC5+nAU1HSl9g2VzR6CvGz9FU0tbTrwokqQZowAyjKW1gC8kGPljVWtkOsAfJAA5IxYJ7rAwJAqnAuMbIIiJ-c0iJycApAA7gAWKngfy2lB8lEgs0cCncQnuakgnD+bEgVGoxnAixW0jWAApQlBIIT6ATCaTIBFHAAuU4AQROABoSWSIWhqTiAJQHY6WFCCNj05mCoWC64IgEKACSADlZqCOJxkMZIII-owfgoRIwQWDbiIxciJQARGyQHH-KRI8EAA01EpoZGQgLuNJExittwUTkQaHsZkgjHBms47KZ3EZZOJwopbGpJwAQgymWTMtS-MI9Uc+AJ0wA6aPCoWixEqBSyyRcRXK1XqlF6gQ6+GIg3G27WG2MO0Op2cF1uj1bCI+ooCxAiP1l+WVlVqjVa+sB3X6yBGk0qNu2+2O+DO13uksLEve32h8BRENAA):
```javascript
// it doesn't matter which error comes first in the array
doStuff([
    {
        name: 'A',
        cb: () => false,                        // this INcorrectly shows no error in the IDE (whether `noImplicitAny` is enabled or not)
    },
    {
        name: 'B',
        cb: person => person.name               // this correctly shows an error in the IDE if `noImplicitAny` is enabled, and correctly shows no error in the IDE if `noImplicitAny` is disabled
    }
])
```

> Once a program contains an error, further checking of that program is suspect

Here the first error isn't the `cb` on the second object in the array. It's rather unclear to me why the _first_ error is simply ignored.

You will note that I have many other examples above, all of them behaving rather unintuitively to me (even after your explanation).

[Playground Link](https://www.typescriptlang.org/play?target=7&ts=4.6.2&filetype=js#code/PQKhCgAIUgBBjAhgG2QI0fA1pAwi9TLKGWAB0QCdEBbSAbwHs0ArAU3gBcBfSMtygGdGAOxJxKbTgFdKIwQ0GdKASxEBzbiWDhwoCNDicAnvwAmbAGaQAosjY02IzrlGWV68eUqN+lE4rKapqQANoitGwAul5kPn4B9PioGNi8ofBoMdA6emBGpmwW1vR2Dk4ubh6hUbxljs6uIu7qCiC5+nAU1HSl9g2VzR6CvGz9FU0tbTrwokqQZowAyjKW1gC8kGPljVWtkOsAfJAA5IxYJ7rAwJCcABYqCijCkADujJRYCgAUAAYRjl+kEekBEjEgyFE6gEkFmNAGRUgjGknEgaBRwIUagAbigVGYAJTgRYraRrb6hKCQan0KnU+mgyIALlOAEETgAaOkM2FoFnfAkHY6WZ5sDk8iWSiXXW4PBRg16wj6SLjIYyQQR3RivJ4iLaUHyUYF6+5sSAASQAIjZudwuQzaVKAWwWQBOcVSz1ehky+4g2YGjicNUarU6yCIPUCQ3G2Vmq02qWZFl+YR6o58ARpgB0zu9PpufoUAZVwfVmu1uv1MbUcYt1uB1n+jHNNDIyBU8BUnFZImMQJBTkQaHsZnFkbMSsDqvLYfl4OjH1jpvrNkbkGbrfbne7vf7mIWj2Ho9t4CiRKAA):
```javascript
// this also works (the second `name` is now invalid)
doStuff([
    {
        name: 'A',
        cb: () => false,                        // this now correctly shows an error in the IDE
    },
    {
        name: 9,                                // this correctly shows an error in the IDE
        cb: person => person.name               // this correctly shows an error in the IDE if `noImplicitAny` is enabled, and correctly shows no error in the IDE if `noImplicitAny` is disabled
    }
])
```

Here **ALL 3** across both objects (entire array) show errors properly. Which I guess I would not expect based on:
> Once a program contains an error, further checking of that program is suspect

`name: 9` is incorrect, and somehow adding this error in the second object of the array allows the `cb` error (which was previously ignored) on the first object to be picked up as expected.

In this example, if you comment out the second `name` the error on the first `cb` [no longer shows](https://www.typescriptlang.org/play?target=7&ts=4.6.2&filetype=js#code/PQKhCgAIUgBBjAhgG2QI0fA1pAwi9TLKGWAB0QCdEBbSAbwHs0ArAU3gBcBfSMtygGdGAOxJxKbTgFdKIwQ0GdKASxEBzbiWDhwoCNDicAnvwAmbAGaQAosjY02IzrlGWV68eUqN+lE4rKapqQANoitGwAul5kPn4B9PioGNi8ofBoMdA6emBGpmwW1vR2Dk4ubh6hUbxljs6uIu7qCiC5+nAU1HSl9g2VzR6CvGz9FU0tbTrwokqQZowAyjKW1gC8kGPljVWtkOsAfJAA5IxYJ7rAwJCcABYqCijCkADujJRYCgAUghyiZkgAAMIo4gZBZjQBkVIIxpJwAJTgRYraRrb6hKCQbH0LHY-GQUFsABcpwAgicADR4gkQtCk74Ig7HSzPNiU2mcrmc663B4KJQqVAQj6SLjIYyQQR3RivJ4iLaUHyUSBqPlsSAASQAIjYadxqQTcdzeUTSQBODnc602yC8+6PEVKjicCVSmVyyCIBUCZWqhX3DU6vXczKkvzCBVHPgCSMAOiJtoJ9v5TrFrsl0tl8sVfrVga1utV1hBjE1NDIyBU8BUnDJImM4MdTkQaHsZg53sBs2d4szHoUIkYuY+-vVhZsxeBQ-LlertfrjdVCjMj1b7f14CiSKAA). If you instead make the second name correct (set it to a valid `string`) the error on the first `cb` no longer shows (first example in this post).

I understand this has something to do with the array but the array itself never shows any errors (nor do any of the objects within the array). The errors are shown on the properties of the objects, so you would assume that correct operation would pick up errors on all properties of all objects in the array individually.

[Playground Link](https://www.typescriptlang.org/play?target=7&ts=4.6.2&filetype=js#code/PQKhCgAIUgBBjAhgG2QI0fA1pAwi9TLKGWAB0QCdEBbSAbwHs0ArAU3gBcBfSMtygGdGAOxJxKbTgFdKIwQ0GdKASxEBzbiWDhwoCNDicAnvwAmbAGaQAosjY02IzrlGWV68eUqN+lE4rKapqQANoitGwAul5kPn4B9PioGNi8ofBoMdA6emBGpmwMdg5OLm4evCA68KJKkMwsAIKQALwMUJBdEY4AXJAA5E0DADSdXZn9fsIibQB8fAIzAHQ9RV0bkMDAkIAy5P2AvBuAsjvgWnmkJvzF9o7OriLuIdXgtfKcDawAQm0dm2v9A0+o3GkEmkAAFABKeaQSwoQTrTZI5HbPaHE5nfQFK70Eq3coPDyhKJVGp1d5USgtdqhEH0EF-SIAoFjZETND9KEwuHIBFslE7QCg5IdAHI7IO4rI29P5-0Gw0lyLB01EMOVIlWkQ2qP2kGO4vAMXO2KKuJuZXuj2JpJe5MglO+NLpDI2sqGwP5SqWKtaCzVGscWp2Or1mwlTplTMGLOd7M50J9sPhiP5XVRwt1YtDBvAQA)
```javascript
/**
 * @callback Callback
 * @param {object} person
 * @returns {string}
 */

/**
 * @typedef ElementConfig
 * @property {string} [name]
 * @property {Callback} [cb]
 */

/** @type {ElementConfig} */
const objA = {
    name: 'A',
    cb: person => person.name       // ❌: 👍
}

/** @type {ElementConfig} */
const objB = {
    name: 'B',
    cb: () => false                 // ❌: 👍
}

/** @type {ElementConfig[]} */
const arrA = [
    {
        name: 'B',
        cb: () => false             // ✅: 👎
    },
    {
        name: 'A',
        cb: person => person.name   // ❌: 👍
    }
]

/** @type {ElementConfig[]} */
const arrB = [
    {
        name: 'A',
        cb: person => person.name   // ❌: 👍
    },
    {
        name: 'B',
        cb: () => false             // ✅: 👎
    }
]
```

**Comment by somebody1234** [comment]
note re: functions... type type is inferred as:
```ts
const arr: {
    name: string;
    cb: (person: any) => any;
}[]
```
(see `const arr` in the [Playground](https://www.typescriptlang.org/play?noImplicitAny=false&ssl=28&ssc=12&pln=28&pc=1&filetype=js#code/PQKhFgCgAIWgBAxgQwDaoEbMQa2gYTU2xylgQAdkAnZAW2gG8B7DAKwFNEAXAX2godqAZ2YA7MnHjUO3AK7UxwpsO7UAlmIDmvScChRQEGFO4BPQQBMOAM2gBRVBzocx3fOJvqtkytWaC1OYqapo60ADaYvQcALq+8BT+gcGMhOhYuPwRiBjxJvqQhmAI5la2TI7Oru6e3hGx-FUubh5iXlrKIIXFUlS0DIzNNW0dwvwcTi217d5dhYjiqtCWzADK8jZ2ALzQk9WtdZ3Q2wB80ADkzDgXBpCrG3JbABQRZNAfjO8fP9DRLgAuS4AQQuABpvr9oLkgc8AJQnc42NDCDhgqEYzEY4DAaDcAAW6mUAEkAHKLagyHioMzQYT45gAd2UYmYe0pzGo0E0ePxHGgxIAIvZoM9GXyCUJoAADVnEugUVDqRDqbjAsRmaXc5SuZAYJyWaCcv7MbhwyG8CEwH5fa0Y-4cIEXABC4MhvxhAiEojEiK9InEADoHVjMTjeUToZyqdwaXSGczoMhfUJ-FyeZKBcLuXZZcx5Yrlar1ZrtXtovqOJZ0cnDRSY3H6UyWWzU8aM3ysyL1Lm5QqlSq1RqtZHLES9QaLVBYubIIslNwk5STpFIbasQ6naCrVjPfC-cjUKj0aHT79wwTI2T61xY7Sm4nWey09zfZmhSKxRK+Vy8wWB8Ww5lrqlaGsarJmhaO42u6PybpcrrQRinqBD6fqoUGIZnj8F6EsoN7UveCbKMmz7tm+nYfjmMp9oWg4liOOoVgaNZiHW0a3o2xEmmR6YUfyVE9jR+b9kWQ6lqO46gVOkCxEAA)).
and because of `any`, it suppresses the error for `() => false`. because the return type is `any`, any return type is acceptable. because `() => false` takes no args, it can handle a `person: object`... by ignoring it

**Comment by gerukin** [comment]
Thanks @somebody1234 but I think the original example is not the same as what you added to your playground. I think everything behaves normally (as you describe) in your `arr`. But it doesn't in my `doStuff([...])` example.

If you go back to your [playground](https://www.typescriptlang.org/play?noImplicitAny=false&ssl=28&ssc=12&pln=28&pc=1&filetype=js#code/PQKhFgCgAIWgBAxgQwDaoEbMQa2gYTU2xylgQAdkAnZAW2gG8B7DAKwFNEAXAX2godqAZ2YA7MnHjUO3AK7UxwpsO7UAlmIDmvScChRQEGFO4BPQQBMOAM2gBRVBzocx3fOJvqtkytWaC1OYqapo60ADaYvQcALq+8BT+gcGMhOhYuPwRiBjxJvqQhmAI5la2TI7Oru6e3hGx-FUubh5iXlrKIIXFUlS0DIzNNW0dwvwcTi217d5dhYjiqtCWzADK8jZ2ALzQk9WtdZ3Q2wB80ADkzDgXBpCrG3JbABQRZNAfjO8fP9DRLgAuS4AQQuABpvr9oLkgc8AJQnc42NDCDhgqEYzEY4DAaDcAAW6mUAEkAHKLagyHioMzQYT45gAd2UYmYe0pzGo0E0ePxHGgxIAIvZoM9GXyCUJoAADVnEugUVDqRDqbjAsRmaXc5SuZAYJyWaCcv7MbhwyG8CEwH5fa0Y-4cIEXABC4MhvxhAiEojEiK9InEADoHVjMTjeUToZyqdwaXSGczoMhfUJ-FyeZKBcLuXZZcx5Yrlar1ZrtXtovqOJZ0cnDRSY3H6UyWWzU8aM3ysyL1Lm5QqlSq1RqtZHLES9QaLVBYubIIslNwk5STpFIbasQ6naCrVjPfC-cjUKj0aHT79wwTI2T61xY7Sm4nWey09zfZmhSKxRK+Vy8wWB8Ww5lrqlaGsarJmhaO42u6PybpcrrQRinqBD6fqoUGIZnj8F6EsoN7UveCbKMmz7tm+nYfjmMp9oWg4liOOoVgaNZiHW0a3o2xEmmR6YUfyVE9jR+b9kWQ6lqO46gVOkCxEAA), you'll see that hovering over....
* `cb` line 31 gives you: `(property) cb: () => boolean`
* `cb` line gives you: `(property) cb: (person: any) => any`

Both are fine and indeed there can be no error with those inferred types.

However contrast it with my example (in the same Playground):
* `cb` line 21: `(property) cb?: Callback` which as per the `Callback` def cannot return a `boolean`
* `cd` line 25: `(property) cb?: Callback` which as per the `Callback` def cannot return `any`

What you've done by adding your separate `arr` example is remove the `Callback` association. Your array is not declared as an array of `ElementConfig`, so there is some inferring here (entirely independently of the array where I have the problem I am attempting to describe in this issue)... whereas the array in `doStuff` is declared as an array of `ElementConfig`, which in turn mandates that `cb` properties must conform to the `Callback` signature, and return only a `string` and never `any` or `boolean` (indeed as callbacks they do not need to specify an argument, but they still must return a `string`).

Not sure if I'm missing the point somehow, but this is how I understand your example.

**Comment by somebody1234** [comment]
it's the same issue. the problem is that the inferred type of `arr` is the type that's being passed to `doStuff`. returning (and accepting) an `any` explicitly passes *any* sort of type compatibility checks. in other words, every type is compatible with `any`

**Comment by gerukin** [comment]
I would assume that using an inferred type from your example:
```javascript
const arr: {
    name: string;
    cb: (person: any) => any;
}[]
```
...in a variable specifically typed as `ElementConfig[]`, or inlining it in a function requiring an array specifically typed as `ElementConfig[]`, would fail.

In fact it does (examples from the [playground above](https://www.typescriptlang.org/play?target=7&filetype=js#code/PQKhCgAIUgBBjAhgG2QI0fA1pAwi9TLKGWAB0QCdEBbSAbwHs0ArAU3gBcBfSMtygGdGAOxJxKbTgFdKIwQ0GdKASxEBzbiWDhwoCNDicAnvwAmbAGaQAosjY02IzrlGWV68eUqN+lE4rKapqQANoitGwAul5kPn4B9PioGNi8ofBoMdA6emBGpmwMdg5OLm4evCA68KJKkMwsAEKQALwMUJBdEY4AXJAA5ACCAwA0nV2Z-QAUAJRtAHyQliiCRV0bm1tdwMCQgDLk-YC8G4CyO+BaeaQm-MX2js6uIu4h1eC18pwNrENtHZs9bH6AyaYwmkCmfAEwhEi0hQlEADoAdtILsDsczhd9AUbvQSvdyk8PKEolUanVPlRKD92qEwfQwf9IkCRuMUeC0DN5q0litkGt2Vs0YBQcmOgDkdsHcNkbBnsgFAkHS7YQvzQ2GqxHInZ7Q6QU6S8AxS44op4u5lR7PElkt4UyBUlq0+mMjbywYjF2TTmQOawvkCwUbNG606QQB8G4B2XcAsASAITJAPB-kqVfxRboAnKNA4HgxjPRz+hqYTy4dCkZEgzqc5stEbsbBrqb8RaKuprTlbR97ZRKLhfnTNrKU8z3QNcxDfUX-etM9m9Sdw9H44nney0Wmk5sVVDROqtyJS45y+jZwaYkA)):
```javascript
/** @type {ElementConfig[]} */
const arrB = [
    {
        name: 'A'
        cb: () => false             // ❌: 👍 🤷‍♂️
    },
    {
        name: 9,                    // ❌: 👍
        cb: person => person.name   // ❌: 👍
    }
]
```

FYI: this is the type reported by intellisense for `arrB` in this case: `const arrB: ElementConfig[]`. It behaves the same when passed to the function directly. What matters here is what the array is typed as (`ElementConfig[]`), not what it would be inferred to be had there be no typing definitions at all.

[Playground Link](https://www.typescriptlang.org/play?target=7&filetype=js#code/PQKhCgAIUgBBjAhgG2QI0fA1pAwi9TLKGWAB0QCdEBbSAbwHs0ArAU3gBcBfSMtygGdGAOxJxKbTgFdKIwQ0GdKASxEBzbiWDhwoCNDicAnvwAmbAGaQAosjY02IzrlGWV68eUqN+lE4rKapqQANoitGwAul5kPn4B9PioGNi8ofBoMdA6emBGpmwMdg5OLm4eoVG8IDrwokqQVJQAQpAAvGFQkD303T0DkBGOAFyQAOQAguP9g5CZYwAUAJQdAHyQliiCRXN7kMDAkIAy5GOAvBuAsjuQgHwbgOy7gLAEgEJkgPB-s9wANLN9+0ORYwCc7x+wIGhxO5wus0GCz4AmEInWsKEogAdMNdgcjqdIJc3uAYnlSBRqHR6CVHM5XCJ3Ooqrw2PYKeVqR4FLVwPV5JxIGZGABlGSWaydBmlSkVdQKdobcaMLAzQkFfjFRllKk0uk5cC8gXSIWLUJfKEDdFjKYzH4wlaIrbIHYg0FYiE3B4vN6fQbffamyCAh3AsHY3GWtBjPzwxHh1Hox3gnGQwZaKLLcBAA):
```javascript
/**
 * @callback Callback
 * @param {object} person
 * @returns {string}
 */

/**
 * @typedef ElementConfig
 * @property {string} [name]
 * @property {Callback} [cb]
 */

/** @type {ElementConfig[]} */
const arrB = [
    {
        name: 'A'
        cb: () => false             // ❌: 👍 🤷‍♂️
    },
    {
        name: 9,                    // ❌: 👍
        cb: person => person.name   // ❌: 👍
    }
]

/** @param {ElementConfig[]} elementConfigs */
const doStuff = elementConfigs => 'ok'

/** @type {ElementConfig[]} */
doStuff([
    {
        name: 'A'
        cb: () => false             // ❌: 👍 🤷‍♂️
    },
    {
        name: 9,                    // ❌: 👍
        cb: person => person.name   // ❌: 👍
    }
])
```

`ElementConfig` doesn't accept `any` in the `cb` callback. It just doesn't, so `any` doesn't pass. In fact, it fails reliably as far as I can tell. 🎉 This is not the issue.

The problem is that in some narrow cases the `cb` property can return a `boolean` and not fail... and it's not obvious to me why. See my examples above for when that happens (for seemingly unrelated reasons). Ex to make the first `cb: () => false` pass validation, you can make the second `name` correct (`string`). But removing the second `name` altogether has the first `boolean` `cb` properly fail again. 🤷‍♂️

**Comment by somebody1234** [comment]
your playground errors because the comma after `'A'` is missing...

**Comment by somebody1234** [comment]
remove the type annotation from `arrB` - the type is now:
```ts
const arrB: ({
    name: string;
    cb: () => boolean;
} | {
    name: number;
    cb: (person: any) => any;
})[]
```
which, as you may notice, is completely different from
```ts
const arr: {
    name: string;
    cb: (person: any) => any;
}[]
```

**Comment by gerukin** [comment]
Sure, but I still fail to see the relevance. All the `cb` here in both cases fail the type definition.

Why does the first `cb` pass?
```javascript
/** @type {ElementConfig[]} */
const arrA = [
    {
        name: 'A',
        cb: () => false             // ✅: 👎
    },
    {
        name: 'B',
        cb: person => person.name   // ❌: 👍
    }
]
```
Is it not telling typescript that all elements of the array must be of the type `ElementConfig`, which requires the `cb` callback to return a `string` (and not `any` or `boolean`)?

---

Consider this ([Playground Link](https://www.typescriptlang.org/play?target=7&filetype=js#code/PQKhCgAIUgBBjAhgG2QI0fA1pAwi9TLKGWAB0QCdEBbSAbwHs0ArAU3gBcBfSMtygGdGAOxJxKbTgFdKIwQ0GdKASxEBzbiWDhwoCNDicAnvwAmbAGaQAosjY02IzrlGWV68eUqN+lE4rKapqQANoitGwAul5kPn4B9PioGNi8ofBoMdA6emBGpmwMdg5OLm4eoVG8IDrwokqQVJQAgpAAvGFQkD303T0DkBGOAFyQAOQt4wA0-YOQmWMAFACUHQB8kJYogkXz+5DAwJCAMuRjgLwbgLI7E2iMjPaIIuOQKgoijJxNgoIeEWj2kE4jEBhQmSlUGjm3Fmgz6ByGkTG4wAQjM5oNFnwBMIRBssUJRPCjqcLtdxsx2Fxnq8hh8vj91H8AUCQfwwUENOMoeAYnlSCY2fQSo5nK4RO51FUanUGp9msiOl1YeiBsM2EipjCDpjVnjtshdvD5sTAKDkF0AcjtQrW9FU9NVI1HW+aYvw4vGu0QAOjVA2JZ0gVwmaueZkYbDedLYAA9Xp9CQKiuTWBxOFzBlpefoCoLhWUxRKpTlwPV5HLKJRcIrQnM4Qd7RNNbaFmhlmt2pt9Yajb7jv7A+Nbvc2I9qRG5d9foh-kUWQn2RDPOmnbX9sT6yi0fCXdjCe38TjvZEeySA2Tg5BQ+HaZ9o7HIPHQUnKanuZn8rA50L7CLyuLKtUixLRpmgAESrGsm3XRstxbSBdT3Ts9m7Q5e1JG47geJ4XjHelJ2nQFgTncZwWCK0IKJY510dJttwJXE9w9ERD0cY8+zPSIQzDHDb0aB82SfFM0wGaFyIONdEQmXBN21WDGPdHcmJ9Ho-TQ8Zz0vbiY143EiIpQTX3AIA)):
```javascript
/** @type {ElementConfig[]} */
const arrA = [
    {
        name: 'A',
        cb: () => false             // ❌: 👍 'boolean' is not assignable to type 'string
    },
    {
        name: 'B',
        cb: person => person        // ❌: 👍 'object' is not assignable to type 'string'
    }
]

/** @type {ElementConfig[]} */
const arrB = [
    {
        name: 'A',
        cb: () => false             // ✅: 👎
    },
    {
        name: 'B',
        cb: person => person.name   // ❌: 👍 'name' does not exist on type 'object'
    }
]

/** @type {ElementConfig[]} */
const arrC = [
    {
        name: 'A',
        cb: () => false             // ❌: 👍 'boolean' is not assignable to type 'string
    },
    {
        // name: 'B',
        cb: person => person.name   // ❌: 👍 'name' does not exist on type 'object'
    }
]

/** @type {ElementConfig[]} */
const arrD = [
    {
        name: 'A',
        cb: () => false             // ❌: 👍 'boolean' is not assignable to type 'string
    },
    {
        // name: 'B',
        cb: person => person.name   // ❌: 👍 'name' does not exist on type 'object'
    },
    {
        // name: 'C',
        cb: person => person.name   // ❌: 👍 'name' does not exist on type 'object'
    }
]
```

`arrA` and `arrB` both have the same inferred type:
```javascript
const arrA: {
    name: string;
    cb: (person: any) => any;
}[]
```
Yet they give different errors. This is not the cause, or at least it isn't a sufficient condition.

The reason seems to have something to do with the kind of errors that are encountered in the array objects. The error on `arrB`'s second `cb` is about a seemingly missing property because we are in strict mode. Somehow this stops further/prior errors from being evaluated. Perhaps this is related to what @RyanCavanaugh mentioned in the beginning. Buuuuut, `arrC` does have the same error, yet it doesn't stop further/prior evaluation... just because the `name` property doesn't exist (which indeed means the inferred type of the array would now be a union of 2 kinds of object types but... so what?). Even if not a bug (which I'm not sure it isn't quite yet), this is rather opaque and unintuitive to me.

So this seems to mean that when typescript encounters an error in an array it stops processing errors for elements of the same inferred type. Or something like that. But of course, that's not true, as we saw for `arrA`. So this applies only to some kinds of errors and not others.

So a tentative conclusion would be: typescript doesn't show errors on elements of the same inferred type when it encounters some kinds of errors on one of them. Except that as `arrD` shows, that's not quite true either. Name B and C have the same inferred type, and the same seemingly problematic error, and yet all 3 show. 🤔

**Comment by somebody1234** [comment]
it *is* a bit unfortunate if you want to suppress that one error (for whatever reason) though...
[Playground](https://www.typescriptlang.org/play?target=7&filetype=js#code/PQKhCgAIUgBBjAhgG2QI0fA1pAwi9TLKGWAB0QCdEBbSAbwHs0ArAU3gBcBfSMtygGdGAOxJxKbTgFdKIwQ0GdKASxEBzbiWDhwoCNDicAnvwAmbAGaQAosjY02IzrlGWV68eUqN+lE4rKapqQANoitGwAul5kPn4B9PioGNi8ofBoMdA6emBGpmwMdg5OLm4eoVG8IDrwokqQVJQAQpAAvGFQkD303T0DkBGOAFyQAOQAguMANP2DkJljABQAlB0AfJCWKIJFCweQwMCQgKDkY4C8G4ByO-Pcc4N9h0ORY+Mts-ODx0aCALRsAA9+Fx-pQfJRPgMlnwBMIRJsYUJRAA6Yb7I4nQAy5JdALI7EzR40gZkYbAUIkYnEggJUjVEkBM-AmzHYXHGt3AUSAA)
```ts
const arrB = [
    {
        name: 'A',
        cb: () => false
    },
    {
        name: 'B',
        // @ts-expect-error
        cb: person => person.name
    }
]
```
but to be fair this is most definitely not a place you'd want to use (just) `@ts-expect-error`... maybe something like [this](https://www.typescriptlang.org/play?target=7&filetype=js#code/PQKhCgAIUgBBjAhgG2QI0fA1pAwi9TLKGWAB0QCdEBbSAbwHs0ArAU3gBcBfSMtygGdGAOxJxKbTgFdKIwQ0GdKASxEBzbiWDhwoCNDicAnvwAmbAGaQAosjY02IzrlGWV68eUqN+lE4rKapqQANoitGwAul5kPn4B9PioGNi8ofBoMdA6emBGpmwMdg5OLm4eoVG8IDrwokqQVJQAQpAAvGFQkD303T0DkBGOAFyQAOQAguMANP2DkJljABQAlB0AfJCWKIJFCweQwMCQgKDkY4C8G4ByO-Pcc4N9h0ORY+Mts-OD+gX8DMmEaRynwGxyMggAtGwAB78LiQyg+SjAnpLPgCYQiTZooSiAB0w32RxOgBlyS6AWR2JgTxpAzIw2AoRIxOJBoSpGqJICZfuNmOwuONbuAokA) (`@type {Callback}` + `@ts-expect-error`)

of course, in the case you want to fix all errors (as one does when using tsc to check code), whether there's one error or two indeed doesn't matter since (in this case) if you fix that error, the other error will appear

**Comment by RyanCavanaugh** [comment]
It's definitely a thing to be aware of. One of the reasons we were super resistant to adding `ts-expect-error` (and even `ts-ignore`) is exactly because we sometimes improve error reporting by moving/splitting errors for better accuracy. It wouldn't be surprising if we changed OP's behavior at some point in the future.

**Comment by gerukin** [comment]
The problem I see is that the behavior is seemingly inconsistent to the user. Please take a look at my [playground](https://www.typescriptlang.org/play?target=7&filetype=js#code/PQKhCgAIUgBBjAhgG2QI0fA1pAwi9TLKGWAB0QCdEBbSAbwHs0ArAU3gBcBfSMtygGdGAOxJxKbTgFdKIwQ0GdKASxEBzbiWDhwoCNDicAnvwAmbAGaQAosjY02IzrlGWV68eUqN+lE4rKapqQANoitGwAul5kPn4B9PioGNi8ofBoMdA6emBGpmwMdg5OLm4eoVG8IDrwokqQVJQAgpAAvGFQkD303T0DkBGOAFyQAOQt4wA0-YOQmWMAFACUHQB8kJYogkXz+5DAwJCAMuRjgLwbgLI7E2iMjPaIIuOQKgoijJxNgoIeEWj2kE4jEBhQmSlUGjm3Fmgz6ByGkTG4wAQjM5oNFnwBMIRBssUJRPCjqcLtdxsx2Fxnq8hh8vj91H8AUCQfwwUENOMoeAYnlSCY2fQSo5nK4RO51FUanUGp9msiOl1YeiBsM2EipjCDpjVnjtshdvD5sTAKDkF0AcjtQrW9FU9NVI1HW+aYvw4vGu0QAOjVA2JZ0gVwmaueZkYbDedLYAA9Xp9CQKiuTWBxOFzBlpefoCoLhWUxRKpTlwPV5HLKJRcIrQnM4Qd7RNNbaFmhlmt2pt9Yajb7jv7A+Nbvc2I9qRG5d9foh-kUWQn2RDPOmnbX9sT6yi0fCXdjCe38TjvZEeySA2Tg5BQ+HaZ9o7HIPHQUnKanuZn8rA50L7CLyuLKtUixLRpmgAESrGsm3XRstxbSBdT3Ts9m7Q5e1JG47geJ4XjHelJ2nQFgTncZwWCK0IKJY510dJttwJXE9w9ERD0cY8+zPSIQzDHDb0aB82SfFM0wGaFyIONdEQmXBN21WDGPdHcmJ9Ho-TQ8Zz0vbiY143EiIpQTX3AIA) from [this comment](https://github.com/microsoft/TypeScript/issues/49062#issuecomment-1126953228). You can see that `arrA`, `arrB`, `arrC`, and `arrD` all behave differently. The equation example (🙇‍♂️) doesn't explain that as far as I can tell. Can we not use the (different IMO) equation example and use the actual examples?

> and nothing you could derive from first principles to specify the exact number of problems that any given wrong equation has. It's either right or wrong, and the way that the wrongness is described is not necessarily going to match every single person's intuition

Sure, but I think I haven't argued for either 1 error or all error reporting on the same semantic block. Indeed, it's more a matter of convention here 👌. But I am arguing for consistent and easily understandable behavior from the user's point of view. Here, even knowing all the facts, I could not have predicted what errors typescript would surface or suppress, and indeed, the software works 90% of the time showing all errors on all object properties in the array, and 10% of the time it suppresses some types of errors from some object properties in array, but keeps all others. Let us keep in mind that typescript doesn't show any error at the object or array level. It is only at the property level in my example, always. That or it shows no error at all.

> we sometimes improve error reporting by moving/splitting errors for better accuracy

Much appreciated. I would expect this effort to continue and `arrB` to report a separate `cb` violation, just like the other array examples (which would also do away with the `@ts-expect-error` problem shown above). Again, the problem here is the inconsistency and impossibility of predicting (at least not easily so) what typescript may do.

It may seem like a no issue and indeed as @somebody1234 reminds us:
> if you fix that error, the other error will appear

However, if you have two errors of the kind I show here sufficiently spread apart, you might not realize one is suppressing the other and might keep working on a part of the code which will actually have to change. Worse, you might notice the second error on the exact same property and mistakenly conclude you can safely keep adding stuff to the **first** error free object because it shows no error vs the one below you will fix later.

Again, if typescript always behaved consistently and either reported just the **first** error, or a more generic error at the parent block level, then I would adjust my expectations / reflexes. But it mostly behaves much better, pinpointing things smartly at the lowest possible level. In my case it was a bit different, I knew there was supposed to be an error and when I didn't see it, I thought the type definitions were wrong and wasted time trying to understand why I had no error there for something obviously wrong which showed as such for everything else. This did not give me confidence in releasing the code for others to use.

Again, the behavior violates consistency.. it's not just a matter of unmet subjective expectations, or not being able to decide what is wrong specifically in a block (it can, and it isn't ambiguous in the examples I gave you - there is one good answer, which typescript gets 90% of the time).

> It's definitely a thing to be aware of

The issue here is that I'm still not sure what to be aware of. I appreciate the equation example, but I don't think it explains much here unfortunately. Nobody has told me yet what justifies the inconsistency and how to know in advance what will cause typescript to ignore which errors in **my specific examples**. I can't really describe what I should be watching out for, much less build reflexes, because I can't predict when typescript will show or suppress other _somehow related_ errors.

**Comment by RyanCavanaugh** [comment]
Consistency is not a concrete principle to work from, and this issue isn't meaningfully actionable.

Consider these four programs
```ts
const b: string[] = [1, "a", 2];
```

```ts
const a = [1, "a", 2];
const b: string[] = a;
```

```ts
function f() {
  return [1, "a", 2];
}
const b: string[] = f();
```

```ts
function f() {
  return [1, "a", 2];
}
const a: (string | number)[] = f();
const b: string[] = a;
```

It's *very nice* that the first program shows two errors; this was a well-received behavior when we implemented it.

The second program, it's sort of a 🤷‍♂️ as to whether we should or shouldn't drill into the errors on `a`. It'd maybe be nice.

In the third program, it would seem weird to issue distinct errors, but maybe you could with a sufficiently detailed error chain.

In the fourth program, it's probably completely untenable to do anything but issue exactly one error.

But these programs all do the same thing! Consistency demands that they all have same error arity, since they are functionally equivalent. The only solution would be for TypeScript to only ever issue one error: "Program is not right" and terminate, but no one wants that.

**Comment by gerukin** [comment]
I understand some choices need to be made as to whether and how to represent errors. I think the current behaviors you describe in your examples are all fine and examples of **different** conventions in **different** ways of coding the same functional program, but they still do not address what I'm talking about. In fact, the current behavior in all those examples makes the most sense to me, and is consistently predictable.

The examples I gave you are using the same convention being applied unevenly, sometimes mistakenly or at least **unpredictably** [omitting some errors](https://www.typescriptlang.org/play?target=7&filetype=js#code/PQKhCgAIUgBBjAhgG2QI0fA1pAwi9TLKGWAB0QCdEBbSAbwHs0ArAU3gBcBfSMtygGdGAOxJxKbTgFdKIwQ0GdKASxEBzbiWDhwoCNDicAnvwAmbAGaQAosjY02IzrlGWV68eUqN+lE4rKapqQANoitGwAul5kPn4B9PioGNi8ofBoMdA6emBGpmwMdg5OLm4eoVG8IDrwokqQVJQAgpAAvGFQkD303T0DkBGOAFyQAOQt4wA0-YOQmWMAFACUHQB8kJYogkXz+5DAwJCAMuRjgLwbgLI7E2iMjPaIIuOQKgoijJxNgoIeEWj2kE4jEBhQmSlUGjm3Fmgz6ByGkTG4wAQjM5oNFnwBMIRBssUJRPCjqcLtdxsx2Fxnq8hh8vj91H8AUCQfwwUENOMoeAYnlSCY2fQSo5nK4RO51FUanUGp9msiOl1YeiBsM2EipjCDpjVnjtshdvD5sTAKDkF0AcjtQrW9FU9NVI1HW+aYvw4vGu0QAOjVA2JZ0gVwmaueZkYbDedLYAA9Xp9CQKiuTWBxOFzBlpefoCoLhWUxRKpTlwPV5HLKJRcIrQnM4Qd7RNNbaFmhlmt2pt9Yajb7jv7A+Nbvc2I9qRG5d9foh-kUWQn2RDPOmnbX9sT6yi0fCXdjCe38TjvZEeySA2Tg5BQ+HaZ9o7HIPHQUnKanuZn8rA50L7CLyuLKtUixLRpmgAESrGsm3XRstxbSBdT3Ts9m7Q5e1JG47geJ4XjHelJ2nQFgTncZwWCK0IKJY510dJttwJXE9w9ERD0cY8+zPSIQzDHDb0aB82SfFM0wGaFyIONdEQmXBN21WDGPdHcmJ9Ho-TQ8Zz0vbiY143EiIpQTX3AIA):
```javascript
/** @type {ElementConfig[]} */
const arrA = [
    {
        name: 'A',
        cb: () => false             // ❌: 👍 'boolean' is not assignable to type 'string
    },
    {
        name: 'B',
        cb: person => person        // ❌: 👍 'object' is not assignable to type 'string'
    }
]

/** @type {ElementConfig[]} */
const arrB = [
    {
        name: 'A',
        cb: () => false             // ✅: 👎
    },
    {
        name: 'B',
        cb: person => person.name   // ❌: 👍 'name' does not exist on type 'object'
    }
]

/** @type {ElementConfig[]} */
const arrC = [
    {
        name: 'A',
        cb: () => false             // ❌: 👍 'boolean' is not assignable to type 'string
    },
    {
        // name: 'B',
        cb: person => person.name   // ❌: 👍 'name' does not exist on type 'object'
    }
]

/** @type {ElementConfig[]} */
const arrD = [
    {
        name: 'A',
        cb: () => false             // ❌: 👍 'boolean' is not assignable to type 'string
    },
    {
        // name: 'B',
        cb: person => person.name   // ❌: 👍 'name' does not exist on type 'object'
    },
    {
        // name: 'C',
        cb: person => person.name   // ❌: 👍 'name' does not exist on type 'object'
    }
]
```

So far, you've avoided telling me why typescript behaves differently for `arrB` compared to the others. I would understand a low priority on this. But outright closing it does Typescript users a disservice, especially since in the worst case it can lead to **all legitimate issues being mistakenly ignored** (case reported by @somebody1234 [here](https://github.com/microsoft/TypeScript/issues/49062#issuecomment-1132022137)).
