### ISSUE TITLE
Typescript Unable to resolve signature of parameter of decorator in vscode

### ISSUE THREAD

**Issue by luluhoc** [microsoft/TypeScript#52396]
I'm getting the error when I'm decorating the class in nestjs service.
I'm using typescript 4.9.4

The Typescript is compiling without errors, and I'm getting this problem only in VSCode.

```
Unable to resolve signature of parameter decorator when called as an expression.
  Argument of type 'undefined' is not assignable to parameter of type 'string | symbol'.ts(1239)
```

My tsconfig
```
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": false,
    "removeComments": true,
    "strictNullChecks": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "ES2020",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
  }
}

```

My Class
```
export class AuthService {
  private readonly logger = new Logger('AuthService');
  constructor(
    private readonly jwtService: JwtService,
    private readonly prisma: PrismaService,
    private readonly passwordService: PasswordService,
    private readonly configService: ConfigService,
    private readonly twilioService: TwilioService,
    private readonly userService: UsersService,
    @InjectQueue('nest-worker') private nestWorkerQueue: Queue,
    @InjectQueue('mailsend') private mailSend: Queue,
    @Inject(CACHE_MANAGER) protected readonly cacheManager: Cache,
    private readonly mailerService: MailService
  ) {}

```

I tried reinstalling typescript and removing node modules, but the problem persists.

**Comment by luluhoc** [comment]
so the problem is JavaScript and TypeScript Nightly extension in VSCODE, when disabled the problem is gone.

**Comment by luluhoc** [comment]
https://github.com/microsoft/vscode-typescript-next/issues/72

**Comment by wayn3r** [comment]
This happened to me. And as @luluhoc said, it is likely you have enabled the ` JavaScript and TypeScript Nightly` extension in vscode, but I didn't disable it to fix this. Just select the typescript version you're using so vscode know what you're using. In your case is `4.9.4`. 

To make sure you are using `typescript@4.9.4`:

Open a JavaScript or TypeScript file in VS Code.

In the VS Code command palette, run the `TypeScript: Select TypeScript version` command.
Make sure you have Use Workspace version selected.

![image](https://user-images.githubusercontent.com/61094137/214652263-deff47e7-1083-412a-995c-ded716a38cc0.png)

**Comment by magnocarvalho** [comment]
@wayn3r Thanks, run `TypeScript: Select TypeScript version` and it worked for me. ✌️

**Comment by izakharov** [comment]
> This happened to me. And as you said, it is the `JavaScript and TypeScript Nightly` extension in vscode, but I didn't disable it to fix this. Just select the typescript version you're using so vscode know what you're using. In your case is `4.9.4`.
> 
> To make sure you are using `typescript@4.9.4`:
> 
> Open a JavaScript or TypeScript file in VS Code.
> 
> In the VS Code command palette, run the `TypeScript: Select TypeScript version` command. Make sure you have Use Workspace version selected.
> 
> ![image](https://user-images.githubusercontent.com/61094137/214652263-deff47e7-1083-412a-995c-ded716a38cc0.png)

Thanks!! you saved my day 🙌

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.

**Comment by gggaboaniquilador** [comment]
Thanks for the solution bro;)

**Comment by MarleeG** [comment]
Thank you @izakharov !

**Comment by jack-useb** [comment]
> This happened to me. And as you said, it is the `JavaScript and TypeScript Nightly` extension in vscode, but I didn't disable it to fix this. Just select the typescript version you're using so vscode know what you're using. In your case is `4.9.4`.
> 
> To make sure you are using `typescript@4.9.4`:
> 
> Open a JavaScript or TypeScript file in VS Code.
> 
> In the VS Code command palette, run the `TypeScript: Select TypeScript version` command. Make sure you have Use Workspace version selected.
> 
> ![image](https://user-images.githubusercontent.com/61094137/214652263-deff47e7-1083-412a-995c-ded716a38cc0.png)

That definitely saved my day 👍 Thank you! @izakharov

**Comment by parkchoongho** [comment]
> This happened to me. And as you said, it is the `JavaScript and TypeScript Nightly` extension in vscode, but I didn't disable it to fix this. Just select the typescript version you're using so vscode know what you're using. In your case is `4.9.4`.
> 
> To make sure you are using `typescript@4.9.4`:
> 
> Open a JavaScript or TypeScript file in VS Code.
> 
> In the VS Code command palette, run the `TypeScript: Select TypeScript version` command. Make sure you have Use Workspace version selected.
> 
> ![image](https://user-images.githubusercontent.com/61094137/214652263-deff47e7-1083-412a-995c-ded716a38cc0.png)

@wayn3r Thanks!! 👍👍

**Comment by CRISTIAN-MULLER** [comment]
> the issue form was pre-populated with a template and some instructions. We need you to read those instructions _completely_, follow them, and then fill in _all_ the fields in that template.
> 
> We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly

@wayn3r You Rock.

**Comment by std4453** [comment]
The underlying issue is still not fixed though, and it might come as a problem for someone who need to use TypeScript 5.0+. @luluhoc can you open a new issue following the issue template?

**Comment by NabeelTariq44** [comment]
It's showing the same error to me 
TS1239: Unable to resolve signature of parameter decorator when called as an expression.
  Argument of type 'undefined' is not assignable to parameter of type 'string | symbol'.
<img width="192" alt="Capture" src="https://user-images.githubusercontent.com/121153823/230715831-0f83ef70-8ef6-4644-b5a5-91fbf687a065.PNG">

**Comment by sublimator** [comment]
Something to do with the new decorators I suppose.
I am also seeing this issue when trying to upgrade to TS5.  
We are using experimental decorators. 

> Another missing functionality are parameter decorators. These are decorators with which method or constructor parameters can be decorated. This is a feature used by libraries like Angular, Nest.js, or type-graphql. As of shortly before the TypeScript 5 release, there are no separate proposals for this and no implementation in TypeScript. Because of this, Angular will not yet switch to the new decorators, but will continue using the experimental decorators, since the dependency injection feature is built on this pattern.

**Comment by sublimator** [comment]
https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#more-accurate-type-checking-for-parameter-decorators-in-constructors-under-experimentaldecorators

**Comment by josejustino** [comment]
> This happened to me. And as you said, it is the `JavaScript and TypeScript Nightly` extension in vscode, but I didn't disable it to fix this. Just select the typescript version you're using so vscode know what you're using. In your case is `4.9.4`.
> 
> To make sure you are using `typescript@4.9.4`:
> 
> Open a JavaScript or TypeScript file in VS Code.
> 
> In the VS Code command palette, run the `TypeScript: Select TypeScript version` command. Make sure you have Use Workspace version selected.
> 
> ![image](https://user-images.githubusercontent.com/61094137/214652263-deff47e7-1083-412a-995c-ded716a38cc0.png)

It worked for me too. Thanks man!

**Comment by ajubin** [comment]
Hi, thanks for the fix.

One thing I don't understand though is the fact that I already had this line `"typescript.tsdk": node_modules/typescript/lib"` in my project settings but it was not taken into account. 

Isn't it a bug ?

**Comment by linhvuvan** [comment]
It happens to me even though I don't use `JavaScript and TypeScript Nightly` extension. Try do disable all extensions that I have, still does not work.
My ts version is `"typescript": "~4.6.3"`

Code that cause issue
```
@Inject(forwardRef(() => UsersService))
```

**Comment by linhvuvan** [comment]
A coworker of mine fixed it by changing the version of Typescript in vscode.

**Comment by regalstreak** [comment]
I added `"experimentalDecorators": true` to my `compilerOptions` in `tsconfig.json`. Worked with VSCodes typescript version 5.0.4
![image](https://github.com/microsoft/TypeScript/assets/7759208/1c5af63f-6480-4fec-94b0-4cd11772d43c)

**Comment by GareginAv** [comment]
I tried all the options, but it doesn't work

**Comment by henzopolicena** [comment]
@GareginAv, it doesn't work for me too. But I was import the @Query from wrong path.

![image](https://github.com/microsoft/TypeScript/assets/95658345/ecb8dc3e-893d-4544-ba3c-9f94452af227)
Now it is correct and works for me.

![image](https://github.com/microsoft/TypeScript/assets/95658345/e28daca6-fe0d-4e45-8d62-ac4128e20bbb)

**Comment by carlossalasamper** [comment]
I'm experiencing the same issue, it's seems like a bug in decorators from 5.0. I'm having this error specifically with the tsyringe decorators

**Comment by FelipeSinnemann** [comment]
> This happened to me. And as you said, it is the `JavaScript and TypeScript Nightly` extension in vscode, but I didn't disable it to fix this. Just select the typescript version you're using so vscode know what you're using. In your case is `4.9.4`.
> 
> To make sure you are using `typescript@4.9.4`:
> 
> Open a JavaScript or TypeScript file in VS Code.
> 
> In the VS Code command palette, run the `TypeScript: Select TypeScript version` command. Make sure you have Use Workspace version selected.
> 
> ![image](https://user-images.githubusercontent.com/61094137/214652263-deff47e7-1083-412a-995c-ded716a38cc0.png)

I love u bro

**Comment by iamgabrielsoft** [comment]
if the above didn't solve your problem completely then check out this from Stackoverflow, it was really helpful
https://stackoverflow.com/questions/38271273/experimental-decorators-warning-in-typescript-compilation

**Comment by razznblue** [comment]
If you are getting this warning while making a typegoose model, add these three options to your next.config.json.
```json
    "strictPropertyInitialization": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
```

**Comment by amalashenok** [comment]
@wayn3r, `TypeScript: Select TypeScript version` works for me, Thank you Bro!

**Comment by finleywilliamsonV** [comment]
I was still getting the error `Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option in your 'tsconfig' or 'jsconfig' to remove this warning.ts(1219)` for an `@NgModule()` decorator even after `TypeScript: Select TypeScript version` got rid of the initial error.

What finally worked was setting
```
{
   "js/ts.implicitProjectConfig.experimentalDecorators": true
}
```
in VSCode's `settings.json`

**Comment by raoufmadani** [comment]
Although VS Code is a great editor for TypeScript projects, it needs a kick every now and again. Often, without warning, certain files cause it to freak out and complain. Mostly the fix seems to be to save and close all open files, then open tsconfig.json. After that you should be able to re-open the offending file without error. If it doesn't work, lather, rinse, and repeat.

If your tsconfig.json specifies its source files using the files array, IntelliSense will only function correctly if the file in question is referenced such that VS Code can find it by traversing the input file tree.

Edit: The 'reload window' command (added ages ago now) should solve this problem once and for all.

**Comment by Hexacker** [comment]
I have faced the same issue today, the fix was just reloading the Typescript server
`CMD + SHIFT + P` then choose `TypeScript: Restart TS Server`

**Comment by MonikaR23** [comment]
If @wayn3r solution didn't solve your problem, you may want to check your tsconfig.json (which should already have "experimentalDecorators": true) and make sure you have the following:
```
{
  "include": [
    "src/**/*.ts",
  ]
}
```

**Comment by nsk1703** [comment]
Thank you very much!!

**Comment by WendaoLee** [comment]
> I added `"experimentalDecorators": true` to my `compilerOptions` in `tsconfig.json`. Worked with VSCodes typescript version 5.0.4 ![image](https://private-user-images.githubusercontent.com/7759208/237209902-1c5af63f-6480-4fec-94b0-4cd11772d43c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNzg3NDAsIm5iZiI6MTcyMDA3ODQ0MCwicGF0aCI6Ii83NzU5MjA4LzIzNzIwOTkwMi0xYzVhZjYzZi02NDgwLTRmZWMtOTRiMC00Y2QxMTc3MmQ0M2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDRUMDczNDAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzE0ZmE5YjhhZDk3YjhlMTRmMzk0MThiMDhkYWZjOTQzYWUxYzI4MTRmYTA4NmZmZDA5MTFjMmUzNzUzZjVmYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.L0alZrWOMjtE5MLdsXiwQSHumOFGBBsY0eIFP9EG3XM)

yep,this works for me.The document here:[https://www.typescriptlang.org/tsconfig/#experimentalDecorators](https://www.typescriptlang.org/tsconfig/#experimentalDecorators)

**Comment by salqadri** [comment]
> Although VS Code is a great editor for TypeScript projects, it needs a kick every now and again. Often, without warning, certain files cause it to freak out and complain. Mostly the fix seems to be to save and close all open files, then open tsconfig.json. After that you should be able to re-open the offending file without error. If it doesn't work, lather, rinse, and repeat.
> 
> If your tsconfig.json specifies its source files using the files array, IntelliSense will only function correctly if the file in question is referenced such that VS Code can find it by traversing the input file tree.
> 
> Edit: The 'reload window' command (added ages ago now) should solve this problem once and for all.

I tried all the above in vain; this is what finally worked for me. ty.

**Comment by tanishq14developer** [comment]
This save my entire day !!!

**Comment by DEEPAKsingh74** [comment]
Anyone still having the issue here i have resolved it.

In your tsconfig.json file just add these two options inside compilerOptions.
```
{
       compilerOptions: {
           ... other configs ...
           "experimentalDecorators": true,
	  "strictPropertyInitialization": false,  // this will not give you error if you do not initialize the values in your typescript. which is 
                                                                  // required for typeORM
}
}
```

-------------------   OR  ---------------------------
You could manually mark the typeORM properties as not nullable (!)

```
  @Entity('users')
  export class UserEntity {
	@PrimaryGeneratedColumn('uuid')
	id!: string;
```
