### ISSUE TITLE
Some signatures should use union instead of overloads

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#5766]
I think, this code should be correct code by fixes of lib.d.ts or type system.

``` ts
var separator: string|RegExp;
'str'.split(separator); // type error
```
## Manual: Replace to union types

Resolve by type definition.

from:

``` ts
// lib.d.ts
    split(separator: string, limit?: number): string[];
    split(separator: RegExp, limit?: number): string[];
```

to:

``` ts
// lib.d.ts
    split(separator: string|RegExp, limit?: number): string[];
```
## Automatic: Generate union types

Resolve by auto generated merged signature from overloads.

from:

``` ts
// lib.d.ts
    split(separator: string, limit?: number): string[];
    split(separator: RegExp, limit?: number): string[];
```

Generate the merged signature internally, implicitly.

to:

``` ts
// in memory
    split(separator: string, limit?: number): string[];
    split(separator: RegExp, limit?: number): string[];
    split(separator: string|RegExp, limit?: number): string[]; // generated
```

**Comment by ahejlsberg** [comment]
Agreed, we should fix the declaration of `split` to take a union type for the first parameter.

**Comment by falsandtru** [comment]
Thanks! Should I list up all integration targets? Such as String#match/replace/search, and more many types.

**Comment by RyanCavanaugh** [comment]
It's probably worth having a script or something to find these cases.

Unfortunately we can't perform this merging on the type system side because the two forms (two overloads vs one overload with a union) actually have rather different semantics in practice.

**Comment by falsandtru** [comment]
All right, I'll leave it up to you.

**Comment by falsandtru** [comment]
When TypeScript fixes this issue? I want to fix this issue myself partially if TypeScript doesn't fix this issue until next version 1.8.

**Comment by mhegazy** [comment]
@falsandtru feel free to send a PR for the issue.

**Comment by falsandtru** [comment]
@mhegazy thanks, I'll fix it.
