### ISSUE TITLE
Bad error message for assigning empty array to tuple type

### ISSUE THREAD

**Issue by Arnavion** [Microsoft/TypeScript#6524]
Reported in the IRC channel against 1.7.5. Still exists in 1.8.0-dev.20160117

``` typescript
var x: [number] = [];
```

```
foo.ts(1,5): error TS2322: Type 'undefined[]' is not assignable to type '[number]'.
  Property '0' is missing in type 'undefined[]'.
```

I guess `undefined` comes from the fact that the RHS array is empty, so its element type is left uninitialized. Maybe you want to detect that and have a different error message? "An empty array is not assignable to type [number]." or something.

**Comment by RyanCavanaugh** [comment]
@sandersn @DanielRosenwasser would this be fixed by the proposed contextual typing changes?

**Comment by DanielRosenwasser** [comment]
If I understand things correctly, you should get `number[]` with Nathan's changes.

Even if you didn't, I think I've concluded on several occasions with @JsonFreeman and @CyrusNajmabadi that surfacing the `undefined ` type in error messages is not a problem.

**Comment by Arnavion** [comment]
>Even if you didn't, I think I've concluded on several occasions with @JsonFreeman and @CyrusNajmabadi that surfacing the `undefined` type in error messages is not a problem.

You don't think it gives the impression of being a compiler bug?

**Comment by DanielRosenwasser** [comment]
That's what I argued at the time because it totally looks like we screwed up somehow. The fact that we're surfacing the `undefined` type isn't a problem so much as it is that its representation kinda, well, sucks. :smile:

**Comment by sandersn** [comment]
I checked, looks like the error with the change in #6118 is still the same.

**Comment by JsonFreeman** [comment]
Is there such thing as a tuple of length 0? It seems like the error ought to say something like
>type [] is not assignable to type [number]

where `[]` is the tuple of length 0. But I guess a tuple of length 0 is really the same as `undefined[]` anyway, so maybe there is no point in having that concept.

This is *not* to say that the type `undefined` should never be surfaced in an error message. That is a separate discussion. I think the better question is not about `undefined`, but about how to improve error messages about tuple types. I think that while technically, a tuple type acts as an object with numeric properties, perhaps the error should talk about the "size / length" of the tuple. I think that would be more intuitive for users.

**Comment by DanielRosenwasser** [comment]
Is this still a bug given that the `null` and `undefined` types are going to be representable in 2.0?

**Comment by Arnavion** [comment]
foo.ts:

```typescript
var x = [];
```

`tsc -d -t es5 foo.ts`

foo.d.ts:

```typescript
declare var x: any[];
```

---

foo.ts:

```typescript
var x: [number] = [];
```

`tsc -t es5 foo.ts`

```
foo.ts(1,5): error TS2322: Type 'undefined[]' is not assignable to type '[number]'.
  Property '0' is missing in type 'undefined[]'.
```

There's no difference with `--strictNullChecks`

---

So is an empty array `any[]` or `undefined[]` ? Should it be `undefined[]` even if `--strictNullChecks` isn't passed in?

**Comment by JsonFreeman** [comment]
For the tuple case, it doesn't really matter what the element type is. The array literal is required to have an element at index 0 because of the contextual type, but it does not.

For the other case, if the array did not get widened to `any[]`, I don't think you would be able to subsequently add elements to it, which would be very limiting.

Both of these ideas are independent of strict null checking. That said, I still think it would be reasonable to have tuples of length 0, and then the message would talk about the type `[]` as the empty tuple type.

**Comment by DanielRosenwasser** [comment]
We have empty tuples now, and the new message is

```
Property '0' is missing in type '[]' but required in type '[number]'.
```
