### ISSUE TITLE
Can't edit files in Visual Studio after installing 1.8.4 On Update 2 CTP

### ISSUE THREAD

**Issue by OSUblake** [Microsoft/TypeScript#7204]
**TypeScript Version:** 
1.8.4

**Visual Studio Version:** 
Community 2015 CTP 14.0.25008.00

Everything was working fine using TypeScript 1.8.1 beta. After installing 1.8.4 last night, the editor no longer works. Typing does nothing. The onlys keys it responds to are enter, delete, backspace. The three drop-down lists at the top of the editor that let you jump to certain parts of your code are all blank.

I've tried all of the following with no luck. 

- Repair/uninstall Visual Studio and TypeScript
- Disable extensions
- Uninstall ReSharper
- Clear MEF component cache
- Update [devenv.exe.config](https://social.msdn.microsoft.com/Forums/vstudio/en-US/e011bc08-8b1d-4a2a-99d6-a167da922145/visual-studio-2015-update-1-fails-to-update-devenvexeconfig-plus-fix?forum=vssetup)

I also can't seem to stop Visual Studio from updating to the CTP when I reinstall. I started getting a lot of JavaScript language service crashes after installing the CTP. Viewing a compiled TS file would cause JavaScript to stop working.

**Comment by djarekg** [comment]
I have the same problem. My co worker does not and the only major difference is I have the vs2015.2 CTP and he just has vs2015.1 rtm. Hope that helps

**Comment by birick** [comment]
I ran into the same problem as well.  

I was playing using the newly added ability to add comments to the tsconfig.json file.  If I added a comment at the very top of the file, then this behavior occurred after a restart of VS.  

To resolve, remove any comments at the top of the tsconfig.json file (only use inline comments to the json), and then restart VS.  To be safe, you might try removing any comments to the file and restarting VS and see if that fixes it.

**Comment by mhegazy** [comment]
Update 2 CTP does not support TS 1.8.4. We are looking into why the setup did not show the correct blocking message. 
TS has dependency on internal APIs that changed in Update 2, trying to install TS 1.8.4 (targeting Update1) will cause the language service to be broken.
Update 2 CTP has TS 1.8.1-beta in box, the next public release of Update2 should have the TS 1.8.4. sorry for the inconvenience.

**Comment by IanYates** [comment]
@mhegazy - thanks for the update.  Partly our fault for running a CTP :)  The perf improvements have been worth it though.

If you've got some hacky way of rolling back to the 1.8.1-beta that'd be splendid.

**Comment by mhegazy** [comment]
uninstall TS 1.8.4, repair Update 2 entry in Add/Remove programs should do the trick.

**Comment by IanYates** [comment]
Despite having Update 2 CTP installed, my Add/remove programs just shows 
`Microsoft Visual Studio Enterprise 2015 with Update 1`
![capture1](https://cloud.githubusercontent.com/assets/1314477/13279211/c0b0e092-db21-11e5-9e0a-fbb512aa6488.PNG)


But CTP for update 2 was definitely installed and indeed when I run VS 2015 it says it's CTP for update 2
![capture2](https://cloud.githubusercontent.com/assets/1314477/13279226/e32ea528-db21-11e5-8d29-7103ddeb2855.PNG)

I guess the incorrect info being reported in add/remove programs is the reason why installation of TypeScript 1.8.4 wasn't blocked.

So I've uninstalled TS 1.8.4 - it was really quick and repaired the only entry in add/remove programs so I no longer get those crashes in VS pointing me to the activity log but I also get a read-only TypeScript editing experience.

Sorry for so many words - I wanted to be specific and anticipate what you might suggest :)  My other thread has the things I've tried already with regards to uninstall, reinstall, repair, etc.

**Comment by IanYates** [comment]
I went to my layout folder for the update 2 CTP and found the pair of Typescript *.msi files.  They wouldn't install as a newer version of the product was already present.  Removing TypeScript 1.7.x and 1.8.x from add/remove programs still didn't let the *.msi files executes.

So I then fired up Windows Installer Cleanup Utility.  It lists many packages for CTP update 2 - so that's good.  It also still listed the TypeScript packages.  I nuked them and then ran the ones from the update 2 ctp folder.

That got me back to VS 2015 throwing errors directing me to the activity log upon opening a TypeScript file.

I visited add/remove programs and removed TypeScript from there.  Opening VS 2015 got me back to the behaviour described in this thread where I get the read-only TypeScript experience (but no errors raised in the GUI). Strange that even after uninstalling TypeScript I still got syntax highlighting, etc.

I'm now running a full repair from the VS 2015 Update 2 CTP installer.  Fingers crossed.

**Comment by IanYates** [comment]
:no_good: 
Reboot after repair and it's still read-only.  I noticed however that I can cut & paste code to the editor.  Saving doesn't recompile the JS files though.

I'm heading home (GMT + 10 here) and will check this thread again in an hour or two.  I have some work to do tonight so am **very** happy to be a guinea pig for any suggested fixes you may have.

**Comment by OSUblake** [comment]
> uninstall TS 1.8.4, repair Update 2 entry in Add/Remove programs should do the trick.

Unfortunately, this does not resolve the issue. Everything @IanYates has posted is the same for my machine. There is no Update 2 entry in Add/Remove programs, and Visual Studio is still showing 1.8.4 as being installed. 

Testing out all these different repairs takes way too long. At this point, I'm beginning to think that doing a clean install is going to be the easiest fix for me.

**Comment by IanYates** [comment]
I've uninstalled, reinstalled, uninstalled, gone crazy...  :fire: 

I have run uninstallers for VS 2015 Update 1 from add/remove programs and then also ran the installer for Update2 CTP to ask it to remove itself.  Rebooting in between every change.

I tried just VS 2015 update 1, which claims to *mostly* work (some TFS component fails) but then I can't apply the servicing update for update 1 since it says it needs update 1 installed.  TypeScript files open but with no syntax highlighting or any other special behaviour.  Whilst VS doesn't talk about being a CTP in its splash screen it's help->about menu still mentioned CTP 2.

So I figured I might as well try to get on to Update 2 CTP.  It installs without complaint.  Reboot.

But now I'm back to square one - I can't edit any typescript files :(

How can I completely remove TypeScript from my system so that I can perhaps run the 2x TypeScript MSIs that ship with Update 2's CTP?  I assume there are registry keys and folders to remove.  I just don't want to remove too many and break things further.

**Comment by paulvanbrenk** [comment]
Can you delete the component cache [0] and the activity log from your machine... and send me the activityog [1] when it's created again?

[0] `%localappdata%\Microsoft\VisualStudio\14.0\ComponentModelCache`
[1] `%AppData%\Microsoft\VisualStudio\14.0`

**Comment by OSUblake** [comment]
@paulvanbrenk -TypeScript language service version: `14.1840.40222.1`

[ActivityLog.txt](https://github.com/Microsoft/TypeScript/files/145277/ActivityLog.txt)

**Comment by paulvanbrenk** [comment]
Can you nuke this folder `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript\` and re-run the update 2 installer from here `https://www.visualstudio.com/en-us/downloads/update2-prereleases`

**Comment by paulvanbrenk** [comment]
@OSUblake just to make sure, did you open a TypeScript file before grabbing the activitylog? I don't see any errors in there, which is a unexpected.

**Comment by OSUblake** [comment]
I was wondering if that's what you wanted to happen, but I had to manually log that out. 

After doing a repair and clearing the component cache, it stops creating errors when you launch VS, even though it's not working correctly.

**Comment by paulvanbrenk** [comment]
@OSUblake did you try clearing the TypeScript folder and re-running the Update 2 installer.. not repair from 'Programs and Features'... 

I'm setting up a machine to see if I can get it in the same state... but that's taking a little while.

**Comment by OSUblake** [comment]
I'm not near my computer right now, but I'll try again using the steps you provided.

I did try running the installer before, but it would always crash as soon as I pressed install. For some reason using the installer from the Visualstudio.com site would always cause it to crash, but the installer from the Microsoft.com downloads worked.

**Comment by IanYates** [comment]
I've just gone through the nuking of folders and am about to try the typescript installer.

**Comment by IanYates** [comment]
![vs 2015 ctp 2 setup result](https://cloud.githubusercontent.com/assets/1314477/13301011/96262a68-db8e-11e5-9515-69d5bf7eb61a.PNG)
(Note that it says update 1 in the image but I fetched and ran the installer at https://www.visualstudio.com/en-us/downloads/update2-prereleases clicking the web installer link)

Setup log
[dd_vs_enterprise_20160225070059.log.txt](https://github.com/Microsoft/TypeScript/files/145416/dd_vs_enterprise_20160225070059.log.txt)


After launching VS it's still broken I'm afraid.  No user visible errors. I can open a TS file and get syntax highlighting but I can't type.

Unfortunately there's now no activity log file.  Weird.  (I did delete the XSL stylesheet for it by accident - maybe that had an effect). I'll rerun with the -log parameter.

**Comment by IanYates** [comment]
Version of typescript is now `1.8.0`.  VS 2015 version is update 2 CTP `14.0.25008.00`

The folder `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript\` is no longer on my PC so I can't check the language file version in that folder.

BUT, it is in the `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\VWDExpressExtensions\TypeScript` folder now.
Version: `14.1840.40222.1`

Activity log...
[typescriptactivity.txt](https://github.com/Microsoft/TypeScript/files/145429/typescriptactivity.txt)

Screenshot of help->About
![vs and typescript version in help-about](https://cloud.githubusercontent.com/assets/1314477/13301255/cb94f368-db8f-11e5-8c20-e451fa68e373.PNG)

**Comment by IanYates** [comment]
A better activity log.  I realised that I renamed TypeScript folder to _TypeScript and could see in the previous log that VS enumerates all folders for extensions and found the _TypeScript folder.  It's now completely nuked.

So rerunning VS again gives me a TypeScript editor where I can type but 
a) I do get an activitylog.xml file and a message telling me to go look at it
b) Saving the TS file does not recompile the JS file anymore

Activity log attached
[ActivityLog.xml.txt](https://github.com/Microsoft/TypeScript/files/145449/ActivityLog.xml.txt)

**Comment by paulvanbrenk** [comment]
You probably saw this message:

![image](https://cloud.githubusercontent.com/assets/5273975/13303803/32505c9e-db06-11e5-9268-faf60494a39d.png)

Now I see TypeScript files as plain text files.. but no TypeScript features work.

**Comment by IanYates** [comment]
Thanks @paulvanbrenk - I appreciate the help.

**Comment by IanYates** [comment]
Great success!

Someone here suggested to do a system restore - my earliest one available happened to be from 24hrs ago when I installed TypeScript 1.8 :)

After coming back up the copy of Visual Studio was completely hosed :(  Every possible pane was showing an error referring me to the activity log.  Not pretty.

I ran the CTP 2 installer from the web which only took a couple of minutes but VS was still hosed but with fewer modal dialogs about errors.

I then ran the CTP installer from my previously downloaded "/layout" folder and was given a repair option.  That took a while (10-15 minutes?).  Reboot.

Open VS - one error about something inconsequential and I CAN EDIT TS FILES AGAIN!  Saving them makes a JS file too.

Happy! :dancer:

**Comment by MhausT** [comment]
Had the same problem today after installing VS 2015 Update 2 CTP (typescript 1.8.4 was already installed) because my VS 2015 started acting up horribly while writing typescript code. Made a bad thing even worse for me as well, rather than VS 2015 freezing up at nearly every letter, it now simply ignored my input except for selecting/deleting/newlines. Running VS 2015 in safe mode(devenv /SafeMode) with all extensions disabled allowed me to edit *.ts files again, however without any typescript actually going on. 

Found this github-issue, tried uninstalling typescript 1.8.4 and a series of uninstalling/reinstalling/repairing VS2015 Update2, with no success except new warnings and errors along the way. Eventually tried removing all leftover registry entries I could find from typescript 1.8.4 because the typescript installer from Update 2 CTP refused to install claiming 1.8.4 was still installed. Now the installer finally loaded but was immediatly gone just as well, figuring it hadnt worked I uninstalled VS2015 again. That uninstall failed on some visual studio update, so i tried that again but added /uninstall /force to the setup command line. Now, after reinstalling VS2015 and Update2 CTP once more, removing the` C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript\ `folder as mentioned here, and repaired Update 2 CTP ... I can actually edit and compile *.ts again.

The version of my `Microsoft.VisualStudio.LanguageServices.TypeScript.dll` is now `14.1800.40203.2`. However, actually writing any typescript code in my project still behaves as before this Update 2 CTP story began: eating up my memory, frequently freezes for 30-60s periods, 'visual studio is busy notifications' and eventually it crashes. Got an error similar to what @paulvanbrenk posted as well, but it was quickly followed by many more components failing the same way (about 10 of 'em). 

Tried a new project rather than my existing one, and no immediate typescript issues there. So I guess the issues I am currently still stuck with might be project-specfic rather than still relevant to this thread. Anyway, hope it helps,

**Comment by paulvanbrenk** [comment]
Thanks for reporting back all... and we'll definitely make sure this won't happen in the future.

**Comment by mwijnands** [comment]
Maybe a workaround is to uninstall TS 1.8.4 and just install TS 1.8.1-beta again? (As that is what Update 2 CTP uses)

https://www.microsoft.com/en-us/download/details.aspx?id=48593 (click "Details")

**Comment by paulvanbrenk** [comment]
@mwijnands we have bug which won't let you uninstall 1.8.4, if you have 1.7.x installed, which comes with Update 1.

So uninstalling 1.7.x first and then uninstalling 1.8.4 should work.

**Comment by mwijnands** [comment]
I see. And then install TS 1.8.1-beta or repair Update CTP 2 right.

**Comment by paulvanbrenk** [comment]
@mwijnands repair.. the released version of 1.8.1-beta only works on Update 1.

**Comment by mwijnands** [comment]
@paulvanbrenk thanks!

**Comment by PeteCJohnson** [comment]
How can I uninstall Update 2 ctp if it doesn't show in "Add or Remove Programs"?

**Comment by respectfulyellow** [comment]
Having the same problem with 1.8.x without CTP 2.  Just update 1.  Not sure what to try at this point.

**Comment by mhegazy** [comment]
@respectfulyellow what do you see after installing update 2? can you share your install logs (%temp%\dd_TypeScript*)? also can you share your activity log from VS and any error messages you see?

**Comment by oising** [comment]
Does update 2 RC solve this issue?

**Comment by mhegazy** [comment]
Update 2 RC should have the correct version of TS (1.8.24.0). give it a try and let us know if you run into issues.

**Comment by oising** [comment]
@mhegazy Running `tsc -v` from command line gives `1.8.0` -- is this expected?

**Comment by oising** [comment]
Ok, I've restarted my machine and perhaps there were some env var issues, now I'm seeing 1.8.5 from tsc -v  (which is correct I think for VS plugin 1.8.6) -- right?

**Comment by mhegazy** [comment]
1.8.5 is correct.

**Comment by bikerboyroy** [comment]
Same issue here. I downloaded the latest ts.msi  (TypeScript_Dev14Full.exe) ran it, rebooted.
At cmd prompt i typed   tsc -v and it says Version 1.0.3.0 .

What I use to do is: FrontEnd stuff , run via gulp, but edited in Sublime Text 2. The backend WebApi was edited / compiled via  VS2015.
On 6th March 2106 I decided to bring all development under VS2015.
But I've now got these TS editing errors.

I reverting back to Sublime Text 2  / gulp runners for the front end.

This is another pathetic bug by MS, ever wonder why web devs just don't trust you, and never will !!!!

SORT IT OUT !

**Comment by bikerboyroy** [comment]
I noticed I had previous versions on TS for VS2015 installed.
So, via Control panel I uninstalled the older versions and the latest 1.8.6.0.
Rebooted my  I7 16G memory Win10 laptop.
I installed ver 1.8.6.0 again and rebooted.
Opened VS2015 and I CAN edit .ts files and compile etc via my gulp setup.
But when typing code the IDE seems slow to respond in general, I can out type what appears in the code window, I'm not that fast a typer either.

I now have a serious doubt w.r.t. VS2015 for the frontend.
I'm staying with my original development for frontend i.e. Sublime Text 2,, just a nagging doubt that's all.

**Comment by bikerboyroy** [comment]
The problem is back again !
I close VS2015, shut down my laptop.
3 hours later came back, started it up, .ts files will not edit ! Can only backspace.
Good job I'm using Sublime Text as mentioned above

So MS, when's the fix ?

**Comment by paulvanbrenk** [comment]
@bikerboyroy Can you share the activitylog? Do you have Resharper installed?

**Comment by bikerboyroy** [comment]
Yes reshaper is installed and updated

**Comment by paulvanbrenk** [comment]
Can you disable Resharper for TypeScript files, and see if that works better.

**Comment by bikerboyroy** [comment]
I'll try give me a few moments

**Comment by bikerboyroy** [comment]
Hi
Disabled reshaper for ts and js. Still can't edit

**Comment by paulvanbrenk** [comment]
Can you close VS, delete the activitylog [0], restart VS, and share the activity log if it re-opens.

Is this in any TS file, even ones not part of a project?

[0] %AppData%\Microsoft\VisualStudio\14.0\ActivityLog.xml

**Comment by bikerboyroy** [comment]
Hi
I'll do this in the morning, it's 21.17 in uk, I'm done :-) 
Regards 
Roy

**Comment by mhegazy** [comment]
@bikerboyroy do you happen to have a tsconfig.json in your project? does it have excludes anywhere? can you share the project, or a sample that reproduces the issue?

**Comment by bikerboyroy** [comment]
Hi
No I don't use a typescript config file, it's all run via gulp tasks. Can't share project due to legal reasons. What I can do is create a small test solution this morning and see if I get errors. The solution with the problem is using the latest mvc core dnx templates

**Comment by bikerboyroy** [comment]
Thanks to Paul & Mohamed for getting back to me.

Oped the test project this morning and it will still not edit .ts files. I have several small  ts files in the folder structure. I'm not sure if this locking is caused by me running gulp tasks.. anyway....

We've had a Skype meeting this morning to discuss.
What we're doing is keeping the C# WebApi part of the project in VS2013 , not porting to VS2015.
The frontend will still be developed via Sublime Text, we're upgrading to ver 3 of ST.

Thank you for your emails to me, hope you fix the problem

**Comment by mhegazy** [comment]
@bikerboyroy we would appreciate your help diagnosing this issue. We do not have other reports of this issue, so that leads me to believe it is something special about your project. we would be happy to sign any applicable NDAs to get access to your project, or a sample that reproduces the issue. feel free ot email me directly on `mhegazy` at `Microsoft` dot `com`

**Comment by bikerboyroy** [comment]
Hi Thank you but we're having to get on with the job at hand at the moment.Funny thing is: I shut down my laptop a few hours ago, an hour ago started it up and opened the test project in VS2015.It's working .ts files are editing ok. I've done nothing other then shutdown then start the machine again !RegardsRoy

Date: Wed, 9 Mar 2016 08:55:41 -0800

**Comment by mredl** [comment]
same issue here. from one minute to another, i can't edit ts files. only backspace is possible.
in other projects it's currently possible, but i'm afraid that i get the same issue there!

**Comment by bikerboyroy** [comment]
Hi ALL.
It's happened again this morning. Start up etc , can't edit .ts file in my small test project.
I've not got the time to investigate any further.
The main project is staying VS2013 with ST3 for the frontend.
I have a meeting with the client to discuss the project on Monday. The dev team is 4 contractors including myself based around the UK, working remotely, with me as team leader.
We have ported the frontend to React via typescript in VS2013.
At the meeting on Monday I'm recommending a port of the backend C# Web Api to Node/Express rather than port to DNX via VS2015. The WebApi communicates to an external  Java WebService b.t.w

I really can't trust VS2015 for the frontend.
Sorry MS guys, but I can't spare any more time floundering about with VS2015.

**Comment by mrunks** [comment]
My coworker and I are also having this problem. I uninstalled all versions of typescript and reinstalled the latest from the Extensions and Updates inside Visual Studio 2015.  We are still completely unable to type in any .TS files.  This is a serious problem and may be forced to ditch typescript for this project if it cannot be fixed soon.

**Comment by cwojke** [comment]
I had the same problem. Like @mrunks I uninstalled all versions and then installed 1.8.1.0 Beta and it works. I'm not going for 1.8.4 or latest untill this is solved.

**Comment by bikerboyroy** [comment]
Stick with typescript. Use ST3 and build with gulp from command window. Just ditch VS2015 for frontend dev work.

**Comment by mhegazy** [comment]
@mrunks can you provide some details on what version you had, and what you installed after that.

@cwojke any additional information is appreciated.

**Comment by mhegazy** [comment]
> Stick with typescript. Use ST3 and build with gulp from command window. Just ditch VS2015 for frontend dev work.

@bikerboyroy we would appreciate the help solving this issue. we have not had a local reproduction of the issue you described. I would rather we solve the bug, rather than throwing the baby with the water; and for that we would need some more information.

**Comment by mrunks** [comment]
We have visual studio 2015 with update 1.  Previously had 1.6 then installed the latest version from Visual studio Online gallery.  If is done use a config file for Typescript I can type but a project that uses the config file is where the problem seems to reside.

**Comment by mhegazy** [comment]
@mrunks this seems to be different from the OP. do you see this issue with a new project create from template? or just the project you are working on? what version of TS did you install from gallery?

**Comment by cwojke** [comment]
Hi @mhegazy,here are additional information: 

VS 2015 Community Edition with Update1. I have some other extensions installed like Web Essentials, Bundler & Minifier, Web compiler, WebPack task runner. No Resharper.

My solution consist of about 100 C# projects (Orchard CMS), 8 of them have Typescript and I couldn't edit .ts in any of them. In one project there is .tsconfig and some node modules (but not included in project), in other there is nothing but few .ts files.

The problem occured with TS 1.8.4 from downloaded installer. I could not type any characters in files with .ts and .tsx extension. Only wokring keys were Backspace (and maybe Delete, I'm not sure now). 

Like I said before, after reverting back to 1.8.1. Beta I was able to edit these files again.

**Comment by Lanayx** [comment]
I suddenly got the same issue today (ts version 1.8.6). The only thing that helped was to add tsconfig.json to the project. After that I was able to edit ts files again. Maybe this helps someone else.

**Comment by janb87** [comment]
Same issue here. I was able to solve it by removing the comment on top of my tsconfig.json file.

Doesn't work:
```
/** 
 * Comment
 **/
{
    "compilerOptions": {
        "module": "commonjs",
        "noImplicitAny": true,
        "allowUnreachableCode": false,
        "allowUnusedLabels": false,
        "forceConsistentCasingInFileNames": true,
        "noFallthroughCasesInSwitch": true,
        "noImplicitReturns": true,
        "removeComments": false,
        "preserveConstEnums": false,
        "sourceMap": false,
        "noEmitOnError": true,
        "emitBOM": false,
        "suppressImplicitAnyIndexErrors": false,
        "target": "es5",
        "declaration": true,
        "experimentalDecorators": true
    },
    "compileOnSave": false, // Gulp does this for us
    "exclude": [
        "node_modules"
    ]
}
```

Works:
```
{
    "compilerOptions": {
        "module": "commonjs",
        "noImplicitAny": true,
        "allowUnreachableCode": false,
        "allowUnusedLabels": false,
        "forceConsistentCasingInFileNames": true,
        "noFallthroughCasesInSwitch": true,
        "noImplicitReturns": true,
        "removeComments": false,
        "preserveConstEnums": false,
        "sourceMap": false,
        "noEmitOnError": true,
        "emitBOM": false,
        "suppressImplicitAnyIndexErrors": false,
        "target": "es5",
        "declaration": true,
        "experimentalDecorators": true
    },
    "compileOnSave": false, // Gulp does this for us
    "exclude": [
        "node_modules"
    ]
}
```

**Comment by mredl** [comment]
i got it working again by simply making a change in tsconfig.json, pressing save, revert it, save again - now i can edit files again

**Comment by pgorbas** [comment]
"birick:'s  comment's on Feb 23 worked for me.

He said "To resolve, remove any comments at the top of the tsconfig.json file (only use inline comments to the json), and then restart VS. To be safe, you might try removing any comments to the file and restarting VS and see if that fixes it."

I had comments above the open brace of my tsconfig.json file.  I simply moved them down inside the open brace.  Then I right clicked on the project, selected 'Unload Project', let it unload, then right clicked on the project again, (which now is labeled as '(unavailable)', and selected 'Reload Project'.  AFter the project loaded I could now edit the ts files normally.

**Comment by malibuzios** [comment]
I have updated to VS2015 update 2 RTM. My previous plugin version was `1.8.6` but after the update it has been downgraded to `1.8.29`. Is there any risk in trying to install the latest plugin on update 2? or should I wait for a future release?

**Comment by paulvanbrenk** [comment]
@malibuzios VS Update 2 installs a newer version of the plugin (29 > 6). And you will break VS if you manage to install `1.8.6`.

**Comment by malibuzios** [comment]
@paulvanbrenk Thanks for the information, I assumed it was `1.8.2.9` as `.29` seemed like a big jump :).

**Comment by paulvanbrenk** [comment]
We fixed all the cases that we could find where parsing the `tsconfig.file` would break the editing experience and most of those fixes were shipped as part of Update. The remainder will ship in the next release of TypeScript.

**Comment by cboulva** [comment]
Hello,

After installing TypeScript latest Next version (from https://www.microsoft.com/en-us/download/details.aspx?id=48593), I had the same issue (only backspace/delete key are active when editing any .ts file), Installing VS2015 Update 2 did not fix it either. What seems to fix it in my case is to remove the tsconfig.json file from the project (I use a fully independent gulp stack setup to compile my client-side typescript files, anyway). Home this can help someone.

As soon as I reintegrate the tsconfig.json file in the project, it breaks the .ts editor. And likewise, as soon as i remove it from the project, the editor starts working again.

For information: the file content I have is really simple:

{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "sourceMap": true,
    "noResolve": true
  }

**Comment by paulvanbrenk** [comment]
@cboulva that's interesting... there are no comments anywhere in the `tsconfig.json` file?

**Comment by cboulva** [comment]
Hello, no @paulvanbrenk , no comments at all.

**Comment by cwojke** [comment]
@cboulva Missing parenthesis? In case you just din't copy&paste the last line...

**Comment by vikasjain6** [comment]
it's happened, because of tsconfig.json file, actually I was trying to develop an Angular2 application in Visual Studio 2015 Update 2, once I added tsconfig.json file then .ts file get locked.

if I go to project property, say "**one or more tsconfig.json files detected. project properties are disabled**" and .ts file can't edit.

Please try to resolve ASAP
Thanks

**Comment by paulvanbrenk** [comment]
@vikasjain6 Can you share the `tsconfig.json` file you were using.

**Comment by vikasjain6** [comment]
below json setting was using

{
  "compileOnSave": true,
  "compilerOptions": {
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "exclude": [
    "node_modules",
    "typings/main",
    "typings/main.d.ts"
  ]
}

**Comment by Ritzlgrmft** [comment]
I had a similar problem: everything worked fine. But then, during typing in a typescript file, from one second to another, I no longer was able to edit anymore. Repairing Visual Studio took a lot of time, but did't change for the better.

Finally, I added a default tsconfig.json file, and - I was able to edit again. Afterwards I deleted the file again, but I am still able to edit.

Strange...

**Comment by CarlosOnline** [comment]
Had this same problem.  Renamed the tsconfig.json to tsconfig.json.bak.  I could now type again.  I restored the tsconfig.json and it still works.
Crazy bug.

**Comment by maggiepint** [comment]
I'm getting this issue using .tsx files only with the following setup:

![image](https://cloud.githubusercontent.com/assets/6054610/14901808/ecd1485c-0d5c-11e6-86d8-cfcc41b274ad.png)

For what it's worth, I am using MVC6, DNX, webpack and Reactjs.NET.

I have tried uninstalling all instances of typescript and then running a repair of visual studio and reinstalling typescript.

I have also tried removing/re-adding/renaming the tsconfig.json file. This did not help.

Finally, I created a new project using the default ASP.NET 5 MVC template. I added a .jsx file to that, and was also unable to edit.

This whole time, regular typescript (.ts) files are working fine. This is a super simple project based off of a super simple boilerplate at this point, so I'm honestly really at a loss to know what would be causing this issue.

Backspace, enter and delete seem to work, but that's it.

**Comment by mhegazy** [comment]
>  I added a .jsx file to that, and was also unable to edit.

.jsx or .tsx?

**Comment by mhegazy** [comment]
can you share your tsconfig.json

**Comment by maggiepint** [comment]
.tsx - typo there.

```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "jsx": "preserve"
  }
}
```

**Comment by maggiepint** [comment]
There's absolutely nothing proprietary, it's just junk code, so I pushed the whole repo:

https://github.com/maggiepint/ReactTSBehavingWeird

**Comment by CarlosOnline** [comment]
I had to create a batch file to workaround this.

move tsconfig.json tsconfig.json.bak

REM start typing in the visual studio typescript file then un pause the this script to keep gulp happy

pause 

move tsconfig.json.bak tsconfig.json

**Comment by teves-castro** [comment]
@CarlosOnline Can you elaborate on how exactly are you using your solution? 

In my case after I rename the tsconfig file I regain editing ability, but when when the file is renamed back to its original name although I retain editing ability the project system is no longer using the tsconfig file and instead is looking at the project as if no tsconfig is present in the project.

Note: I'm using an ASP.Net 4.6 project not a ASP.Net Core one.

**Comment by CarlosOnline** [comment]
I make sure to restore tsconfig before typescript file is saved, otherwise gulp will fail.

**Comment by segersrobbert** [comment]
After get latest with tfs I cant edit any typescrit files anymore. Turned source control plugin on and off, changed nothing in the tsconfig file, reboot and can still edit .js and .html files but no .ts files. unable to work

**Comment by teves-castro** [comment]
In my case I was able to overcome my problems by removing some content from my tsconfig.json file. More specifically I had a filesGlob element and a files element in my file, which weren't being used, my project builds with gulp and the source files are specified in another form. After removing these elements everything started working normally.
This leads me to believe that this problem might have something to do with some invalid content in tsconfig preventing the language service to operate properly.

**Comment by paulvanbrenk** [comment]
@segersrobbert If you remove the `tsconfig.json` does editing work again... can you share your project?

**Comment by segersrobbert** [comment]
I've upgraded visual studio and all works fine now. I'm sorry to say it's been a real struggle working with visual studio on front-end work besides this edit bug, configuring own compiling of typescript was a real hassle, its slow, it freezes and crashes quite often.

**Comment by mhegazy** [comment]
>  configuring own compiling of typescript was a real hassle, its slow, it freezes and crashes quite often.

@segersrobbert sorry to hear you are running into trouble there. We would love to get these issues fixed. Can you share more information about your set up, how can we reproduces the crashes, and freezes? can you share crash dumps, or at least stacks from relevant error events in your event viewer?

**Comment by segersrobbert** [comment]
Setup: mac(10.11.4) running parallels with windows10, since updated to VS2015 update 2 crashes and freezes are no more. VS is still interfering with typescript compiling and adding its typescript compile tags to `csproj` whenever it feels like.

**Comment by mhegazy** [comment]
> VS is still interfering with typescript compiling and adding its typescript compile tags to csproj whenever it feels like.

adding a new typescript file will always add it as `TypeScriptCompile` item.

**Comment by mhegazy** [comment]
> VS is still interfering with typescript compiling

can you elaborate on this? what is the expectation and what is actually happening?

**Comment by vanister** [comment]
>As soon as I reintegrate the tsconfig.json file in the project, it breaks the .ts editor. And likewise, as soon as i remove it from the project, the editor starts working again.

I ran into a similar issue to @cboulva, except my .ts files would only be editable when I added the tsconfig.json (default one from Add > New Item context menu) file back to my project.

I initially used VS to compile my .ts files, but then switched to using gulp for compiling them.  That's when I deleted the tsconfig.json file, restarted VS the following day, then ran into the non-editable .ts files.  Of course, adding it back made it work.

I also added the `<TypeScriptCompileBlocked>` line to my .csproj file to prevent msbuild from compiling the .ts files in my project.
```
    ....
    <TypeScriptToolsVersion>1.8</TypeScriptToolsVersion>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
</PropertyGroup>
```

**Comment by paulvanbrenk** [comment]
@vanister can you share your project?

**Comment by vanister** [comment]
@paulvanbrenk sure, how do you want me to get it to you?

**Comment by paulvanbrenk** [comment]
@vanister A repo on GitHub is probably easiest. Also, which version of VS and TypeScript are you using ( see Help - About).

**Comment by vanister** [comment]
@paulvanbrenk I'll create a repo for it and send you the details.  I'm using 2015 update 2 with TypeScript 1.8.31.  Whatever was installed the VS update 2 installer.  I am also using gulp-typescript and that typescript version is: 

``
$ node_modules/gulp-typescript/node_modules/typescript/bin/tsc -v
Version 1.8.10
``

![image](https://cloud.githubusercontent.com/assets/7736967/15868257/eadfe5d6-2c9b-11e6-8ddb-00455c2a2dbb.png)

**Comment by vanister** [comment]
@paulvanbrenk sent you and email

**Comment by paulvanbrenk** [comment]
@vanister change the following in your project files:
```xml
-    <TypeScriptTarget>Unknown</TypeScriptTarget>
+    <TypeScriptTarget>ES6</TypeScriptTarget>
```
We don't gracefully deal with this will be fixed in the next release of TypeScript

**Comment by vanister** [comment]
Thanks @paulvanbrenk

**Comment by kabua** [comment]
**I think I found the Issue!**
I just ran across the same problem BUT I think I've tracked down the issue. 

If I have a very simple project; which contains only a single ```ts``` file and a tsconfig.json file then I can edit the ```ts``` file. However, if I include the project's ```node_modules``` folder (which contains Angular2's QuickStart required modules - consists of 5,610 files) then I can't edit the ```ts``` file; well not for a few seconds that is.

On future investigation, I discovered that when I couldn't edit the ```ts``` file, the three drop-down list boxes were empty. But then after several seconds, I noticed that the first drop-down list box would finally show "TypeScript Virtual Projects" at which point, I could edit my ```ts``` file!!

By changing my ```tsconfig.json``` file to exclude the ```node_modules``` folder, I could edit my ```ts``` almost instantaneously.

My test tsconfig.json file:

    {
        "compilerOptions": {
            "target": "es5",
            "module": "system",
            "moduleResolution": "Node",

            "declaration": false,
            "diagnostics": true,
            "removeComments": false,
            "sourceMap": true,
            "listFiles": true
        },

        "exclude": [
            "WebUtilities",
            "node_modules",
            "typings"
        ],

        "compileOnSave": true
    }

Can anyone else verify that this fixed the issue?

**Comment by paulvanbrenk** [comment]
@kabua that sounds very plausible.. I'll update the default `tsconfig.json` file to exclude `node_modules` and `bower`. Are there any other suggestions?

**Comment by natwebb** [comment]
I am running into the same issue, and none of the fixes suggested here seem to be working. My .tsconfig has always excluded node_modules, so I can't add it pursuant to @kabua 's suggestion, so presumably that's not universally the cause of this issue. I tried adding and removing .bak on the .tsconfig and that also has made no difference. I'm compiling .ts into .js using VisualStudio, and not running gulp or any other such tool.

I have a question out on Stack Overflow here: http://stackoverflow.com/questions/37820711/visual-studio-2015-cannot-edit-typescript-files-get-exception-0x80020101 and I'm happy to share any other information that may be useful, though I can't upload the project itself without getting fired. :)

**Comment by paulvanbrenk** [comment]
@natwebb Yeah, this looks like a different issue.. replied on the StackOverflow question.

**Comment by natwebb** [comment]
At the suggestion of @paulvanbrenk I intalled Update 3 RC from here: https://www.visualstudio.com/downloads/visual-studio-prerelease-downloads and while the initial install failed, necessitating a restart and making VS unusable, running a Repair to get VS back up and running included a successful install of Update 3 RC and fixed the bug!

**Comment by ThomasSchoof** [comment]
I started receiving this error after I updated to Update 3 (Final). I made a stackoverflow question about this issue: http://stackoverflow.com/questions/38184024/error-in-visual-studio-2015-update-3-when-opening-solution-typescript

**Comment by IvanMisyats** [comment]
I was able to edit Typescript files again when I installed Update 3 for VS.

**Comment by morsmodr** [comment]
Close VS2015.
In the root of your solution, go to .vs folder > folder named with solution name > v14 folder > delete the hidden vs file
Restart VS2015
Voila it works
