### ISSUE TITLE
Is there a MSBuild parameter that tells VS which `tsconfig.json` to use?

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [microsoft/TypeScript#7903]
I have 2 tsconfig.json files:
- tsconfig.full.json
- tsconfig.quick.json

I want to be able to point the VS2015 to either one of them accorting to the configuration parameters in `*.targets` files. How can I do it?

**Comment by mhegazy** [comment]
There is not. one thing to note, the targets file has some logic to find tsconfig.json files, by providing this that would switch it off.

**Comment by mhegazy** [comment]
@paulvanbrenk can we add a new property for `--project` and use that if it exists.

**Comment by paulvanbrenk** [comment]
@mhegazy what if someone wants to use 2 `tsconfig.json` files for Debug and 2 others for Release. Let's think of a more general solution before we paint ourselves into a corner.

**Comment by mhegazy** [comment]
We can always make it a collection :)

**Comment by hellocontrol-bng** [comment]
This would be great for the Debug/Release scenario, especially when testing out things like es5/es6. At the moment, we are forced to enable settings like that for all build scenarios, which can be pretty risky.

Unless there is another way to do that?

**Comment by paulvanbrenk** [comment]
You can enable this by manually editing the project file, and adding `Configuration=Debug` to the itemgroup you want to include for debug. (Typing from memory, but there's probably a PropertyGroup which works this way in your project.)

**Comment by hellocontrol-bng** [comment]
@paulvanbrenk Just to make sure I am understanding you correctly, do you mean adding an additional `tsconfig.json` file that only is included in the build for that particular configuration?

**Comment by paulvanbrenk** [comment]
something like this:
```xml
<ItemGroup Condition=" '$(Configuration)' == 'Debug' ">
    <Content Include="tsconfig.json" />
</ItemGroup>    
<ItemGroup Condition=" '$(Configuration)' == 'Release' ">
    <Content Include="tsconfig.json" />
</ItemGroup>
````

**Comment by ridhoq** [comment]
Bump, is there still any consideration for a msbuild property for --project?

I'm running into an issue where my msbuild is picking up a tsconfig.json in my node_modules directory. I have a tsconfig.json in the dir above that that tells it to ignore the node_modules dir, but msbuild isn't respecting that.

**Comment by paulvanbrenk** [comment]
@ridhoq which version of TypeScript are you using?

**Comment by ridhoq** [comment]
From my .csproj file: `<TypeScriptToolsVersion>2.1</TypeScriptToolsVersion>`

**Comment by paulvanbrenk** [comment]
That's a pretty old version, I believe we fixed this since then... please try a newer version.

**Comment by ridhoq** [comment]
Sure I can do that - will a newer version correctly load the tsconfig.json file I want?

**Comment by paulvanbrenk** [comment]
It should

**Comment by ridhoq** [comment]
@paulvanbrenk so I updated my msbuild typescript to 2.5.3 and I'm still seeing the same behavior. It's still reading the tsconfig from one of my node_modules even thought I have a tsconfig in a parent directory telling it to exclude the node_modules directory. Any ideas on what to try next?

**Comment by paulvanbrenk** [comment]
@ridhoq  I don't reproduce that... can you create a new issue with a small repro. Thanks!

**Comment by ridhoq** [comment]
@paulvanbrenk I've repro'd the issue here: https://github.com/ridhoq/NodeModulesTSConfigTest. Can you check it out? I suspect it's some silly config issue at this point so thanks for taking the time to look at this!

**Comment by KeithHenry** [comment]
Did anything ever happen with this? It's 4 years later and VS2019 _still_ can't switch tsconfig files for different build scenarios.

**Comment by Bouke** [comment]
@KeithHenry [Other than making `tsconfig.json` the recommended configuration option 11 months ago](https://github.com/microsoft/TypeScript-Website/commit/13d86f55f8899dd3963cea2b3b960e3caa4f3209) it seems nothing has changed.
