### ISSUE TITLE
Since i have updated visual studio 2015 community to update 3 compile on save isn't working.

### ISSUE THREAD

**Issue by dotnet4ever** [Microsoft/TypeScript#9136]
**TypeScript Version:** 

1.7.5 / 1.8.0-beta / nightly (1.9.0-dev.20160217)

**Code**

```ts
// A self-contained demonstration of the problem follows...

```

**Expected behavior:**

**Actual behavior:**

**Comment by mhegazy** [comment]
This is the same issue as https://github.com/Microsoft/TypeScript/issues/8835, it should be fixed in Update 3 RTW. sorry for the inconvenience.

**Comment by dotnet4ever** [comment]
can i know when'll release update 3 rtw ?

**Comment by mhegazy** [comment]
We, the typescript team, do not really have much control over when VS is released.

**Comment by dotnet4ever** [comment]
hi mhegazy
i uninstall vs update 3 but my problem doesn't solve.
when i remove tsconfig from my project, compile on save works correctly but when return back it compile on save doesn't work ! 
do you know what should i do ?

**Comment by mhegazy** [comment]
As noted in https://github.com/Microsoft/TypeScript/issues/8835#issuecomment-224422208, this issue is *not* fixed in Update 3 RC. It should be fixed in the next release of Update 3.
