### ISSUE TITLE
Typescript 2.0 beta VS2015 U3 publish issue.

### ISSUE THREAD

**Issue by lg314** [Microsoft/TypeScript#9730]
**TypeScript Version:**  2.0.0 beta VS2015 U3

**Step**
1. Install Typescript 2.0.0 beta
2. Create blank webapplication project.
3. Add typescript file.
4. Install nuget package Typescript msbuild 2.0.0 beta 
5. Build project successfully with any error.
6. Publish project get error.

Copying file WebApplication20\file1.js to obj\Release\Package\PackageTmp\WebApplication20\file1.js failed. Could not find a part of the path 'WebApplication20\file1.js'.	WebApplication20	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.Web.Publishing.targets	2998	

The file in obj\TypeScriptCompilerOutput.text shows project name has been dupilicated.

**Expected behavior:**
c:\\(solution name)\\(project name)\\file1.js
c:\\(solution name)\\(project name)\\file1.map.js
**Actual behavior:** 
c:\\(solution name)\\(project name)\\(project name)\\file1.js
c:\\(solution name)\\(project name)\\(project name)\\file1.map.js

**Comment by JudahGabriel** [comment]
I'm hitting this also. 
![error](https://cloud.githubusercontent.com/assets/312936/16885413/1952b856-4a94-11e6-8ef8-4515ab3424e9.jpg)

It prevents me from publishing my web app, which is a showstopper.

Anyone know of a workaround? It's looking like I'll need to uninstall TS 2.0 beta for VS 2015.

**Comment by mhegazy** [comment]
@paulvanbrenk can you take a look.

**Comment by paulvanbrenk** [comment]
@JudahGabriel or @lg314 can post a _diagnostic_ build log? Does this only reproduce with the NuGet package? Is this an ASP.NET v4 or v5/Core project?

**Comment by JudahGabriel** [comment]
> Does this only reproduce with the NuGet package?

I didn't use the NuGet package; I just downloaded and installed TS 2.0 beta for VS 2015.

> can post a diagnostic build log? 

Sure. How do I do that? You want the full obj\TypeScriptCompilerOutput.text file?

> Is this an ASP.NET v4 or v5/Core project?

Nope. This is a good old fashioned MVC 5 project. 

Repro steps are super simple, and take about 30 seconds: 

1. [Install the TS 2.0 beta for VS 2015.](http://download.microsoft.com/download/6/D/8/6D8381B0-03C1-4BD2-AE65-30FF0A4C62DA/TS2.0.0-TS-release20-nightly-20160708.1/TypeScript_Dev14Full.exe)

2. In Visual Studio, File-> New MVC project.

3. Build -> Publish. Publish anywhere, including the local file system. Voila, the publish will fail.

**Comment by paulvanbrenk** [comment]
Figured it out... 

As a work around you can add the following to the project file:
`<TypeScriptProjectDir>$(MSBuildProjectDirectory)\</TypeScriptProjectDir>` after the `<TypeScriptToolsVersion>2.0</TypeScriptToolsVersion>` element.

**Comment by JudahGabriel** [comment]
Thanks so much for the workaround, Paul! I'll give it a try.

**Comment by paulvanbrenk** [comment]
Have a fixed in the VS repo, this will be in the next 2.0 release.

**Comment by TheWolfA2** [comment]
@paulvanbrenk 's suggested fix of `<TypeScriptProjectDir>$(MSBuildProjectDirectory)\</TypeScriptProjectDir>` definitely fixed the issue! Any ETA on when this will be released?  I downloaded the TS 2.0 beta and still encountered the issue.

**Comment by mhegazy** [comment]
TS 2.0 RC (2.0.2) has already been released (https://blogs.msdn.microsoft.com/typescript/2016/08/30/announcing-typescript-2-0-rc/).
