### ISSUE TITLE
VisualStudio ignores errors in not opened *.ts files

### ISSUE THREAD

**Issue by qbunia** [Microsoft/TypeScript#9756]
VisualStudio ignores errors in not opened *.ts files.

Configuration:
Microsoft Visual Studio Community 2015 Version 14.0.25422.00 Update 3
Microsoft .NET Framework Version 4.6.01038
Typescript 1.8.35.0

**Actual behavior:** 
Create new Typescript application. Go to project properties set Module system: Amd and check: Combine JavaScript output into file: All.js. 

Create typescript file "bla.ts":
```ts
class Bla
{
}
```

In app.ts add:
```ts
var bla = new Bla();
```

Close app.ts so its not present in tabs. Go to bla.ts, change class name of "Bla" to "Bla2". Save file. Now at the bottom visual studio shows that output generated successfully. If you go to Error list there are no errors. But when you actualy open app.ts then you get the error.

**Expected behavior:**
VisualStudio should compile all ts files and detect any errors in every ts file instead of checking errors only in currently opened file.

**Comment by nippur72** [comment]
I experienced this too but have solved by choosing "compile + intellisense" in the error display (there's a combobox)

**Comment by mhegazy** [comment]
This is caused by a change in the Roslyn configurations. you can re-enable the checking of closed files by checking `Tools` -> `Options` -> `Text Editor` -> `C#` -> `Advanced` -> `Editor Help` then check `Enable full solution analysis`.

**Comment by mhegazy** [comment]
I have logged https://github.com/Microsoft/TypeScript/issues/9780 to track adding a better place to expose the option.

**Comment by qbunia** [comment]
@mhegazy 
I tried checking Enable full solution analysis, but this doesnt solve problem, in error list I still dont see errors.

**Comment by mhegazy** [comment]
@paulvanbrenk can you take a look?

**Comment by paulvanbrenk** [comment]
@qbunia It can take up to a minute to show the errors...

**Comment by paulvanbrenk** [comment]
I don't reproduce this in my current build. Closing this and adding an option as discussed in #9780
