### ISSUE TITLE
problem with @types/angular

### ISSUE THREAD

**Issue by lucamorelli** [Microsoft/TypeScript#9781]
Hi, after I installed ts 2.0 beta, I created an asp.net core application and added angular 1.5 and .d.ts from npm.
If I try to compile I have a few problems with angular-mocks.d.ts.
I see these errors in the  error list

```
Cannot find name 'IServiceProvider'.    ... node_modules\@types\angular\angular-mocks.d.ts  65  
Cannot find name 'IScope'.  ..\node_modules\@types\angular\angular-mocks.d.ts   122 
Build:Module 'angular' has no exported member 'IInjectStatic'.  ...\node_modules\@types\angular\angular-mocks.d.ts  344 

```

If I open angular-mocks.d.ts at the beginning I find this 
![error](https://cloud.githubusercontent.com/assets/127777/16902842/b0c90932-4c6b-11e6-89c7-e20230459e7b.png)

this could explain the errors, but:
1. I don't understand why this error isn't shown in the error list
2. this is my config file

```
{
  "compilerOptions": {
    "module": "system",
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5",
    "inlineSources": true,
    "inlineSourceMap": true,
    "outFile": "js/application.js"
  },
  "exclude": [
    "node_modules",
    "wwwroot",
    "node_modules/@types/angular/angular-mocks.d.ts"
  ]
}

```

same problems in the index.d.ts

// Support AMD require
export = angular;
here I have the same error.

how can I solve this?

**Comment by mhegazy** [comment]
There a few issues with the @angular declarations, should all be fixed in the next few days. here are related issues:

* [Broken @types/angular](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10082)
* [Problems using types installed in node_modules/@types](https://github.com/Microsoft/TypeScript/issues/9725)
* [@types/angular-ui-router "Module 'angular' has no exported member 'ui'"](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10154)

**Comment by mhegazy** [comment]
i pushed a fix for this to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10170, once merged and published to npm I will let you know.

**Comment by lucamorelli** [comment]
thanks

**Comment by lucamorelli** [comment]
I just updated to @types/angular 1.5.8 and now I have no error.
Just another thing: if by mistake I have both

    "sourceMap": true,
and 
    "inlineSources": true,
    "inlineSourceMap": true,

ts compiler fails with this message

Error	MSB6006	"tsc.exe" exited with code 1.	HotelPerformance	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets	223	Build

**Comment by lucamorelli** [comment]
Another thing, I have a similar problem adding the types file for angular-ui-bootstrap and ui-grid.

![error](https://cloud.githubusercontent.com/assets/127777/16956308/313d13e8-4dd8-11e6-8123-4e9b74e7260c.png)

**Comment by lucamorelli** [comment]
opening the **angular** index.d.ts file I still have this error message:

![error](https://cloud.githubusercontent.com/assets/127777/16958036/284a1694-4ddf-11e6-95dc-ca47eb3ce25d.png)

This happens only inside the editor, but there is not a compilation error

**Comment by mhegazy** [comment]
> Just another thing: if by mistake I have both "sourceMap": true, and "inlineSourceMap", ts compiler fails with this message

Can you share the output in the output window?

> opening the angular index.d.ts file I still have this error message:

I have filed https://github.com/Microsoft/TypeScript/issues/9829 to track this

**Comment by lucamorelli** [comment]
![error](https://cloud.githubusercontent.com/assets/127777/16968589/187082b8-4e10-11e6-9105-9df7a698f812.png)

any suggestion for the problem with the angular-ui-bootstrap and ui-grid problem?

**Comment by mhegazy** [comment]
i want the actual error. it should be in your output window after you build. or share the msbuild log using `msbuild /verbosity:detailed`

**Comment by lucamorelli** [comment]
hmmm ... I don't find anything in the output window. How can I add parameters to msbuild in a asp.net core projects? I tried adding it to the Condination Compilation symbols but nothing changed.
FYI, in the error list, if I show **Build+Intellisense** I find

![error](https://cloud.githubusercontent.com/assets/127777/16975154/07702192-4e44-11e6-8f47-ad7620e31f27.png)

**Comment by mhegazy** [comment]
The extra errors should not be there. this is tracked by https://github.com/Microsoft/TypeScript/issues/9662

**Comment by mhegazy** [comment]
To get the build output go to `Tools` -> `Options` -> `Projects and Solutions` -> `Build and Run` and select `MSBuild project build output verbosity` to be `Detailed`

**Comment by lucamorelli** [comment]
this happens when I compile with sourceMap in the ts config but not the .d.ts files give me problems
```
Target "PreComputeCompileTypeScriptWithTSConfig" in file "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets" from project "D:\Sorgenti\HotelPerformance\src\HotelPerformance\HotelPerformance.xproj" (target "CompileTypeScriptWithTSConfig" depends on it):
       Using "VsTsc" task from assembly "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\TypeScript.tasks.dll".
       Task "VsTsc"
         C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.0\tsc.exe --project "D:\Sorgenti\HotelPerformance\src\HotelPerformance\tsconfig.json" --listEmittedFiles
       Done executing task "VsTsc".
Done building target "PreComputeCompileTypeScriptWithTSConfig" in project "HotelPerformance.xproj".
Target "CompileTypeScriptWithTSConfig" in file "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets" from project "D:\Sorgenti\HotelPerformance\src\HotelPerformance\HotelPerformance.xproj" (target "Compile" depends on it):
       Task "VsTsc"
         C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.0\tsc.exe --project "D:\Sorgenti\HotelPerformance\src\HotelPerformance\tsconfig.json" --listEmittedFiles
         D:\Sorgenti\HotelPerformance\src\HotelPerformance\error TS5053:Build:Option 'sourceMap' cannot be specified with option 'inlineSourceMap'.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(223,5): error MSB6006: "tsc.exe" exited with code 1.
       Done executing task "VsTsc" -- FAILED.
Done building target "CompileTypeScriptWithTSConfig" in project "HotelPerformance.xproj" -- FAILED.
```
if I reinstall them and retry this is the result

```
Target "CompileTypeScriptWithTSConfig" in file "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets" from project "D:\Sorgenti\HotelPerformance\src\HotelPerformance\HotelPerformance.xproj" (target "Compile" depends on it):
       Task "VsTsc"
         C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.0\tsc.exe --project "D:\Sorgenti\HotelPerformance\src\HotelPerformance\tsconfig.json" --listEmittedFiles
         D:\Sorgenti\HotelPerformance\src\HotelPerformance\error TS5053:Build:Option 'sourceMap' cannot be specified with option 'inlineSourceMap'.
D:\Sorgenti\HotelPerformance\src\HotelPerformance\node_modules\@types\angular-ui-bootstrap\index.d.ts(8,26): error TS2307: Build:Cannot find module 'angular'.
D:\Sorgenti\HotelPerformance\src\HotelPerformance\node_modules\@types\ui-grid\index.d.ts(20,21): error TS2307: Build:Cannot find module 'angular'.
         The command exited with code 1.
       Done executing task "VsTsc" -- FAILED.
Done building target "CompileTypeScriptWithTSConfig" in project "HotelPerformance.xproj" -- FAILED.
```

Could be possible has problem to parse error rows without filename? honestly this error attached to the ending \ is a bit confusing

**Comment by mhegazy** [comment]
The error message is expected. the problem is the message is not well formatted:

```txt
D:\Sorgenti\HotelPerformance\src\HotelPerformance\error TS5053:Build:Option 'sourceMap' cannot be specified with option 'inlineSourceMap'.
```

so VS can not parse it and put it in the error list, so you get the cryptic `"tsc.exe" exited with code 1` message instead.

**Comment by lucamorelli** [comment]
ok, so I think I can't do anything else in this situation

**Comment by mhegazy** [comment]
no, it is a bug and we need to fix it :)

**Comment by lucamorelli** [comment]
ok, can you give me some advice about the problem with the  angular-ui-bootstrap and ui-grid .d.ts files?

**Comment by mhegazy** [comment]
i am not sure i understand the issue with angular-ui-bootstrap and ui-grid. they are both working for me fine

**Comment by mhegazy** [comment]
MSBuild error reporting tracked by https://github.com/Microsoft/TypeScript/issues/9878

**Comment by lucamorelli** [comment]
this is the package,json

```
{
  "version": "1.0.0",
  "name": "asp.net",
  "private": true,
  "devDependencies": {
    "@types/angular": "^1.5.8",
    "@types/angular-ui-bootstrap": "^0.13.30",
    "@types/ui-grid": "^0.0.29",
    "del": "^2.2.1",
    "gulp": "^3.9.1"
  },
  "dependencies": {
    "angular": "^1.5.7",
    "bootstrap": "^3.3.6",
    "jquery": "^2.2.4",
    "jquery-validation": "^1.15.0",
    "jquery-validation-unobtrusive": "^3.2.6",
    "angular-ui-bootstrap": "^1.3.3",
    "angular-ui-grid": "^3.2.6"
  }
}
```

this is the tsconfig.json

```
{
  "compileOnSave": true,
  "compilerOptions": {
    "module": "amd",
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": false,
    "target": "es5",
    "inlineSources": true,
    "inlineSourceMap": true,
    "sourceMap": true,
    "outFile": "wwwroot/js/application.js"
  },
  "exclude": [
    "node_modules",
    "wwwroot"
  ]
}

```
this is the compilation log

```
Target "CompileTypeScriptWithTSConfig" in file "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets" from project "D:\Sorgenti\HotelPerformance\src\HotelPerformance\HotelPerformance.xproj" (target "Compile" depends on it):
       Task "VsTsc"
         C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.0\tsc.exe --project "D:\Sorgenti\HotelPerformance\src\HotelPerformance\tsconfig.json" --listEmittedFiles
D:\Sorgenti\HotelPerformance\src\HotelPerformance\node_modules\@types\angular-ui-bootstrap\index.d.ts(8,26): error TS2307: Build:Cannot find module 'angular'.
D:\Sorgenti\HotelPerformance\src\HotelPerformance\node_modules\@types\ui-grid\index.d.ts(20,21): error TS2307: Build:Cannot find module 'angular'.
         The command exited with code 1.
       Done executing task "VsTsc" -- FAILED.
Done building target "CompileTypeScriptWithTSConfig" in project "HotelPerformance.xproj" -- FAILED.
Target "CompileTypeScriptWithTSConfig" in file "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets" from project "D:\Sorgenti\HotelPerformance\src\HotelPerformance\HotelPerformance.xproj" (target "Compile" depends on it):
       Task "VsTsc"
         C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.0\tsc.exe --project "D:\Sorgenti\HotelPerformance\src\HotelPerformance\tsconfig.json" --listEmittedFiles
D:\Sorgenti\HotelPerformance\src\HotelPerformance\node_modules\@types\angular-ui-bootstrap\index.d.ts(8,26): error TS2307: Build:Cannot find module 'angular'.
D:\Sorgenti\HotelPerformance\src\HotelPerformance\node_modules\@types\ui-grid\index.d.ts(20,21): error TS2307: Build:Cannot find module 'angular'.
         The command exited with code 1.
       Done executing task "VsTsc" -- FAILED.
Done building target "CompileTypeScriptWithTSConfig" in project "HotelPerformance.xproj" -- FAILED.

```

**Comment by lucamorelli** [comment]
could be that I have to add "moduleResolution": "node" to the tsconfig.json?

**Comment by mhegazy** [comment]
aah. that is it. this is tracked by https://github.com/Microsoft/TypeScript/issues/9831. for now you need to specify the "node" module resolution explicitly.
